<a href="https://colab.research.google.com/github/harshbansal-ai/Almabetter-Capstone-Project---HDFC-Bank-Service-Resolution-Analyzer/blob/main/HDFC_Bank_Service_Request_Resolution_Analyzer_Student_Colab_Problem_Statement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HDFC Bank Service Request Resolution Analyzer
## Python Developer Handover Challenge

**Simulation type:** Python Developer codebase handover challenge  
**Company context:** HDFC Bank customer service operations case study  
**Runtime:** Google Colab  
**Core tools:** Python, Pandas, ipywidgets, file handling  

A Product Manager has shared the PRD for an internal service request resolution tool. A previous developer started the work and resigned before completing it. Only the basic service request loading feature is stable. Your task is to understand the PRD, debug the existing notebook, complete the missing features, build the Colab interface, export final reports, and maintain traceability.

## Required Final Submission

Submit **one completed Colab notebook only**.

Everything required for evaluation must be visible inside this same notebook:

- Fixed code
- Visible output after every major section
- Debug fix log
- AI prompt usage log
- PRD completion mapping
- Assumption and limitation log
- Final reports preview
- Final product walkthrough
- Evaluation-ready explanation

The notebook may generate CSV files as product outputs, but those files are **not separate required submissions**.

# Meeting Handover Summary

**Product Manager:** The customer service operations team needs a tool to identify SLA-breached service requests, high-priority pending cases, repeated complaints, branch-wise operational risk, and recommended actions.

**Engineering Manager:** The previous developer resigned. Only basic service request loading works. The remaining code contains broken file loading, incorrect validation, buggy cleaning logic, wrong SLA calculations, incomplete priority rules, missing exports, and an unfinished Colab GUI.

**You:** You are the Python Developer now responsible for completing the product as per the PRD.

# Supporting Documents to Read

Before solving the notebook, read the two supporting documents in the `HDFC_Bank_Service_Request_Resolution_Analyser_Student_Resources` folder:

1. **Meeting_Transcript_HDFC_Bank_Service_Request_Resolution_Analyzer.docx** — explains the workplace handover meeting.
2. **PRD_HDFC_Bank_Service_Request_Resolution_Analyzer.docx** — defines the product requirements, business rules, reports, acceptance criteria, and constraints.

Your implementation should map back to the PRD. Keep the mapping and explanation inside this same notebook.

# Dataset Upload Instructions

Upload `hdfc_service_request_resolution_dataset.zip` when prompted. The code below will extract it automatically.

Expected files:

- `service_requests.csv` — 5,000 rows
- `request_status_updates.xlsx` — 1,300 rows
- `customer_complaints.json` — 1,500 rows
- `support_tickets.csv` — 1,500 rows
- `customers.csv` — 1,200 rows
- `branches.csv` — 1,000 rows
- `status_notes.txt` — 100 notes

In [ ]:


import os, zipfile, glob, json, warnings
from pathlib import Path

try:
    from google.colab import files
    IN_COLAB = True
except Exception:
    IN_COLAB = False

DATASET_FOLDER_NAME = "hdfc_service_request_resolution_dataset"
DATASET_ZIP_NAME = "hdfc_service_request_resolution_dataset.zip"

def prepare_dataset():
    """Find or extract the dataset folder in the current Colab/session directory."""
    if os.path.isdir(DATASET_FOLDER_NAME):
        print(f"Dataset folder found: {DATASET_FOLDER_NAME}")
        return DATASET_FOLDER_NAME

    search_candidates = [
        DATASET_ZIP_NAME,
        os.path.join("..", "HDFC_Bank_Service_Request_Resolution_Analyser_Student_Resources", DATASET_ZIP_NAME),
        os.path.join("HDFC_Bank_Service_Request_Resolution_Analyser_Student_Resources", DATASET_ZIP_NAME),
    ]

    zip_path = None
    for candidate in search_candidates:
        if os.path.exists(candidate):
            zip_path = candidate
            break

    if zip_path:
        print(f"Extracting existing {zip_path}...")
        with zipfile.ZipFile(zip_path, "r") as z:
            z.extractall(".")
        print(f"Dataset extracted to: {DATASET_FOLDER_NAME}")
        return DATASET_FOLDER_NAME

    if IN_COLAB:
        print("Upload hdfc_service_request_resolution_dataset.zip when prompted.")
        uploaded = files.upload()
        zip_candidates = [name for name in uploaded.keys() if name.endswith(".zip")]
        if not zip_candidates:
            raise FileNotFoundError("No ZIP file uploaded. Please upload hdfc_service_request_resolution_dataset.zip")
        with zipfile.ZipFile(zip_candidates[0], "r") as z:
            z.extractall(".")
        print(f"Dataset extracted to: {DATASET_FOLDER_NAME}")
        return DATASET_FOLDER_NAME

    raise FileNotFoundError("Dataset ZIP/folder not found. Place hdfc_service_request_resolution_dataset.zip in the current folder.")

DATASET_PATH = prepare_dataset()
print("DATASET_PATH:", DATASET_PATH)
print("Files found:", sorted(os.listdir(DATASET_PATH)))

Dataset folder found: hdfc_service_request_resolution_dataset
DATASET_PATH: hdfc_service_request_resolution_dataset
Files found: ['branches.csv', 'customer_complaints.json', 'customers.csv', 'request_status_updates.xlsx', 'service_requests.csv', 'status_notes.txt', 'support_tickets.csv']

In [ ]:
# ============================================================
# Section 1: Imports and configuration
# Status: Working
# ============================================================

import pandas as pd
import numpy as np
from datetime import datetime

ANALYSIS_DATE = pd.Timestamp("2026-06-30")
OUTPUT_PATH = Path("hdfc_service_request_outputs")

pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 160)

print("Libraries imported successfully.")
print("Analysis date:", ANALYSIS_DATE.date())
print("Output path:", OUTPUT_PATH)

Libraries imported successfully.
Analysis date: 2026-06-30
Output path: hdfc_service_request_outputs

### Expected Output — Section 1: Imports and Configuration

**Datasets to use:**

- No dataset required in this section.

**How to approach:**

- Import only libraries needed for this Colab product.
- Keep configuration values such as `ANALYSIS_DATE` and `OUTPUT_PATH` in one place.
- Use the fixed analysis date from the PRD so SLA and ticket ageing calculations are reproducible.

**Expected output format:**

Show clear confirmation output:

| Configuration | Expected Value |
|---|---|
| Libraries | Imported successfully |
| `ANALYSIS_DATE` | `2026-06-30` |
| `OUTPUT_PATH` | `hdfc_service_request_outputs` |

**Hint:** If you later need constants such as SLA thresholds or valid priority labels, define them here instead of hard-coding them across many cells.

In [ ]:
# ============================================================
# Section 2: Working feature - Load service_requests.csv
# Status: Working
# ============================================================

service_requests_path = os.path.join(DATASET_PATH, "service_requests.csv")
service_requests_df = pd.read_csv(service_requests_path)

print("service_requests.csv loaded successfully")
print("Shape:", service_requests_df.shape)
service_requests_df.head()

service_requests.csv loaded successfully
Shape: (5000, 14)

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,In Progress,72,Customer Grievance,240247.88,2026-04-27,NaN
1,REQ0000010,CUST000649,BR0980,2026-05-17,22:31:00,Card,Failed ATM Withdrawal,WhatsApp,Pending Customer,36,Cards Operations,24383.2,2026-05-18,NaN
2,REQ0000011,CUST000817,BR0045,2026-06-19,04:47:00,Digital Banking,NetBanking Login,Email,Closed,24,Digital Banking Support,193459.78,2026-06-19,2026-06-19
3,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,In Progress,72,Customer Grievance,3879.56,2026-04-21,NaN
4,REQ0000013,CUST001137,BR0081,2026-06-13,07:18:00,Account,Balance Mismatch,NetBanking,Closed,48,Account Servicing,NaN,2026-06-16,2026-06-16

### Expected Output — Section 2: Load `service_requests.csv`

**Datasets to use:**

- `service_requests.csv`

**How to approach:**

- Confirm the dataset folder path is correct.
- Use `pd.read_csv()` to load the service request file.
- Do not clean the data in this section yet; only verify that the raw file loads.

**Expected output format:**

- A success message such as `service_requests.csv loaded successfully`.
- Shape close to **`(5000, 14)`**.
- A visible `head()` preview with columns like:
  - `request_id`
  - `customer_id`
  - `branch_id`
  - `request_created_date`
  - `request_category`
  - `request_status`
  - `sla_hours`

**Student note:** This is the only feature the previous developer completed properly. Use this section as your reference style for clear output messages.

In [ ]:
# ============================================================
# Section 3: Working feature - Basic service request summary
# Status: Working but too basic
# ============================================================

print("Total rows:", len(service_requests_df))
print("Total columns:", len(service_requests_df.columns))
print("Available columns:")
print(list(service_requests_df.columns))

service_requests_df["request_status"].value_counts(dropna=False)

Total rows: 5000
Total columns: 14
Available columns:
['request_id', 'customer_id', 'branch_id', 'request_created_date', 'request_created_time', 'request_category', 'request_subcategory', 'channel', 'request_status', 'sla_hours', 'assigned_team', 'reported_amount', 'last_updated_date', 'resolved_date']

request_status
Resolved            1404
In Progress         1193
Closed               863
Open                 537
Pending Customer     495
Escalated            299
resolved              59
in_progress           58
closed                34
escalated             24
pending_customer      21
open                  13
Name: count, dtype: int64

### Expected Output — Section 3: Basic Service Request Summary

**Datasets to use:**

- `service_requests.csv`

**How to approach:**

- Display total rows, total columns, and the raw column list.
- Check raw value counts for `request_status`.
- Observe messy status values before cleaning. Do not fix them here yet.

**Expected output format:**

Create visible output showing:

| Output Item | Expected Evidence |
|---|---|
| Total rows | Around `5000` |
| Total columns | Around `14` |
| Column list | All service request columns visible |
| Raw status counts | Includes clean and messy values such as open/in-progress/pending variants |

**Hint:** Later sections should standardize these messy status values into business-ready categories such as `Open`, `In Progress`, `Pending Customer`, `Escalated`, `Resolved`, and `Closed`.

---
# Developer Work Starts Here

The following code was left by the previous developer. Some sections are broken, some are incomplete, and some produce incorrect business results even if they run.

Rules:

1. Do not simply delete the notebook and start from scratch.
2. Debug and improve the existing codebase section by section.
3. Maintain a debug log.
4. Map every completed feature to the PRD completion checklist.
5. Use AI if needed, but verify every answer and maintain an AI prompt log.

In [ ]:
import pandas as pd
from IPython.display import display

DEBUG_LOG_COLUMNS = [
    "issue_id",
    "code_section",
    "issue_type",
    "issue_description",
    "root_cause",
    "fix_summary",
    "tested_status",
    "remarks"
]

debug_log = []

def add_debug_log(
    issue_id,
    section,
    issue_type,
    description,
    root_cause,
    fix_summary,
    tested_status,
    remarks=""
):

    if tested_status not in ["Passed", "Failed"]:
        raise ValueError(
            "tested_status must be 'Passed' or 'Failed'."
        )

    if issue_type not in [
        "Syntax", "runtime", "logic", "data",
        "OOP", "export", "GUI", "handover"
    ]:
        raise ValueError(
            "Invalid issue_type. Use an approved category."
        )

    if any(row["issue_id"] == issue_id for row in debug_log):
        raise ValueError(f"Duplicate issue_id: {issue_id}")

    entry = {
        "issue_id": issue_id,
        "code_section": section,
        "issue_type": issue_type,
        "issue_description": description,
        "root_cause": root_cause,
        "fix_summary": fix_summary,
        "tested_status": tested_status,
        "remarks": remarks
    }

    debug_log.append(entry)

    global debug_fix_log_df
    debug_fix_log_df = pd.DataFrame(
        debug_log,
        columns=DEBUG_LOG_COLUMNS
    )

    return debug_fix_log_df

add_debug_log(
    issue_id="BUG-001",
    section="Section 4 - Debug Log Setup",
    issue_type="OOP",
    description="The original logging function captured only four fields.",
    root_cause="The function parameters and stored records did not include all eight required columns.",
    fix_summary="Implemented a reusable logging function with all eight fields, input validation, duplicate ID checks, and automatic DataFrame refresh.",
    tested_status="Passed",
    remarks="No dataset required. Export will be performed during final submission."
)

print("Section 4: Debug Log Setup")
print("Current documented issues:", len(debug_log))
display(debug_fix_log_df)

Section 4: Debug Log Setup
Current documented issues: 1

,issue_id,code_section,issue_type,issue_description,root_cause,fix_summary,tested_status,remarks
0,BUG-001,Section 4 - Debug Log Setup,OOP,The original logging function captured only fo...,The function parameters and stored records did...,Implemented a reusable logging function with a...,Passed,No dataset required. Export will be performed ...

### Expected Output — Section 4: Debug Log Setup

**Datasets to use:**

- No dataset required in this section.

**How to approach:**

- Create a reusable debug log structure before fixing the product.
- Every time you fix a meaningful bug, add one row to the log.
- Keep this log visible inside the notebook and export it at the end.

**Expected output format:**

Create a visible table named `debug_fix_log_df` with these columns:

| Column | What to write |
|---|---|
| `issue_id` | Example: `BUG-001` |
| `code_section` | Example: `Section 5 - DataLoader` |
| `issue_type` | Syntax, runtime, logic, data, OOP, export, GUI |
| `issue_description` | What was broken |
| `root_cause` | Why it was broken |
| `fix_summary` | What you changed |
| `tested_status` | Passed / Failed |
| `remarks` | Any extra note |

**Minimum requirement:** At least **10 meaningful fixes** must be documented before final submission.

**Hint:** Do not fill this only at the end from memory. Update it section by section while you debug.

In [ ]:
from pathlib import Path
import pandas as pd
import json

class DataLoader:

    def __init__(self, folder_path):
        self.folder_path = Path(folder_path)

    def _get_path(self, file_name):
        file_path = self.folder_path / file_name

        if not file_path.is_file():
            raise FileNotFoundError(
                f"File not found: {file_path}"
            )

        return file_path

    def load_csv(self, file_name):
        return pd.read_csv(
            self._get_path(file_name),
            encoding="utf-8-sig"
        )

    def load_excel(self, file_name):
        return pd.read_excel(
            self._get_path(file_name)
        )

    def load_json(self, file_name):
        file_path = self._get_path(file_name)

        with open(file_path, "r", encoding="utf-8-sig") as file:
            data = json.load(file)

        if isinstance(data, list):
            return pd.DataFrame(data)

        if isinstance(data, dict):
            list_values = [
                value for value in data.values()
                if isinstance(value, list)
            ]

            if len(list_values) == 1:
                return pd.DataFrame(list_values[0])

            return pd.json_normalize(data)

        raise ValueError(
            f"Unsupported JSON structure in {file_name}"
        )

    def load_text(self, file_name):
        file_path = self._get_path(file_name)

        for encoding in ("utf-8-sig", "cp1252", "latin-1"):
            try:
                with open(
                    file_path, "r", encoding=encoding
                ) as file:
                    return [
                        line.strip()
                        for line in file
                        if line.strip()
                    ]
            except UnicodeDecodeError:
                continue

        raise UnicodeError(
            f"Could not decode text file: {file_name}"
        )

loader = DataLoader(DATASET_PATH)

file_loaders = {
    "service_requests.csv":
        lambda: loader.load_csv("service_requests.csv"),

    "request_status_updates.xlsx":
        lambda: loader.load_excel("request_status_updates.xlsx"),

    "customer_complaints.json":
        lambda: loader.load_json("customer_complaints.json"),

    "support_tickets.csv":
        lambda: loader.load_csv("support_tickets.csv"),

    "customers.csv":
        lambda: loader.load_csv("customers.csv"),

    "branches.csv":
        lambda: loader.load_csv("branches.csv"),

    "status_notes.txt":
        lambda: loader.load_text("status_notes.txt"),
}

expected_rows = {
    "service_requests.csv": 5000,
    "request_status_updates.xlsx": 1300,
    "customer_complaints.json": 1500,
    "support_tickets.csv": 1500,
    "customers.csv": 1200,
    "branches.csv": 1000,
    "status_notes.txt": 100,
}

loaded_data = {}
load_errors = {}
summary_rows = []

for file_name, load_function in file_loaders.items():
    try:
        data = load_function()
        loaded_data[file_name] = data

        if isinstance(data, pd.DataFrame):
            actual_rows = len(data)
            columns_or_items = len(data.columns)
        else:
            actual_rows = len(data)
            columns_or_items = "text lines"

        expected = expected_rows[file_name]

        status = (
            "Loaded"
            if actual_rows == expected
            else "Loaded - row count differs"
        )

        summary_rows.append({
            "file_name": file_name,
            "expected_rows": expected,
            "actual_rows": actual_rows,
            "columns_or_items": columns_or_items,
            "status": status
        })

    except Exception as error:
        load_errors[file_name] = str(error)

        summary_rows.append({
            "file_name": file_name,
            "expected_rows": expected_rows[file_name],
            "actual_rows": None,
            "columns_or_items": None,
            "status": f"Failed: {error}"
        })

loading_summary_df = pd.DataFrame(summary_rows)

print("SECTION 5: MULTI-FILE DATA LOADING SUMMARY")
display(loading_summary_df)

print(
    f"Successfully loaded: {len(loaded_data)} "
    f"out of {len(file_loaders)} files"
)

if load_errors:
    print("\nFiles requiring attention:")
    for file_name, error in load_errors.items():
        print(f"- {file_name}: {error}")

SECTION 5: MULTI-FILE DATA LOADING SUMMARY

                     file_name  expected_rows  actual_rows columns_or_items  status
0         service_requests.csv           5000         5000               14  Loaded
1  request_status_updates.xlsx           1300         1300                8  Loaded
2     customer_complaints.json           1500         1500                8  Loaded
3          support_tickets.csv           1500         1500                8  Loaded
4                customers.csv           1200         1200                6  Loaded
5                 branches.csv           1000         1000                6  Loaded
6             status_notes.txt            100          100       text lines  Loaded

Successfully loaded: 7 out of 7 files

### Expected Output — Section 5: Multi-File Data Loader

**Datasets to use:**

- `service_requests.csv`
- `request_status_updates.xlsx`
- `customer_complaints.json`
- `support_tickets.csv`
- `customers.csv`
- `branches.csv`
- `status_notes.txt`

**How to approach:**

- Fix the `DataLoader` class so it can load CSV, Excel, JSON list, and text files.
- Excel files should use `pd.read_excel()`.
- The complaint JSON is a JSON list, not line-delimited JSON.
- Text notes should load with safe encoding and return clean lines.
- Create a loading summary table after all files are loaded.

**Expected output format:**

Display a table similar to this:

| file_name | expected_rows | actual_rows | columns_or_items | status |
|---|---:|---:|---:|---|
| service_requests.csv | 5000 | 5000 | 14 | Loaded |
| request_status_updates.xlsx | 1300 | 1300 | 8 | Loaded |
| customer_complaints.json | 1500 | 1500 | 8 | Loaded |
| support_tickets.csv | 1500 | 1500 | 8 | Loaded |
| customers.csv | 1200 | 1200 | 6 | Loaded |
| branches.csv | 1000 | 1000 | 6 | Loaded |
| status_notes.txt | 100 | 100 | text lines | Loaded |

**Hint:** Make the loader reusable. Do not write seven unrelated loading statements if a class or helper function can handle this more cleanly.

In [ ]:
import pandas as pd
from IPython.display import display


required_columns = {
    "service_requests": [
        "request_id", "customer_id", "branch_id",
        "request_created_date", "request_status"
    ],
    "updates": [
        "update_id", "request_id", "update_date",
        "status_from", "status_to"
    ],
    "complaints": [
        "complaint_id", "request_id", "customer_id",
        "complaint_date", "complaint_status"
    ],
    "tickets": [
        "ticket_id", "request_id", "customer_id",
        "ticket_created_date", "ticket_status"
    ],
    "customers": ["customer_id", "preferred_branch_id"],
    "branches": ["branch_id", "branch_name", "branch_city"]
}

primary_keys = {
    "service_requests": "request_id",
    "updates": "update_id",
    "complaints": "complaint_id",
    "tickets": "ticket_id",
    "customers": "customer_id",
    "branches": "branch_id"
}

expected_columns = {
    "service_requests": [
        "request_id", "customer_id", "branch_id",
        "request_created_date", "request_created_time",
        "request_category", "request_subcategory", "channel",
        "request_status", "sla_hours", "assigned_team",
        "reported_amount", "last_updated_date", "resolved_date"
    ],
    "updates": [
        "update_id", "request_id", "update_date",
        "status_from", "status_to", "updated_by_role",
        "reassignment_flag", "update_note"
    ],
    "complaints": [
        "complaint_id", "request_id", "customer_id",
        "complaint_date", "complaint_type",
        "complaint_description", "complaint_status",
        "sentiment_tag"
    ],
    "tickets": [
        "ticket_id", "request_id", "customer_id",
        "ticket_created_date", "ticket_status",
        "assigned_team", "resolution_time_hours",
        "escalation_flag"
    ],
    "customers": [
        "customer_id", "customer_name", "customer_segment",
        "account_type", "relationship_age_days",
        "preferred_branch_id"
    ],
    "branches": [
        "branch_id", "branch_name", "branch_city",
        "branch_state", "branch_zone", "branch_type"
    ]
}

dataset_files = {
    "service_requests": "service_requests.csv",
    "updates": "request_status_updates.xlsx",
    "complaints": "customer_complaints.json",
    "tickets": "support_tickets.csv",
    "customers": "customers.csv",
    "branches": "branches.csv"
}

expected_row_counts = {
    "service_requests": 5000,
    "updates": 1300,
    "complaints": 1500,
    "tickets": 1500,
    "customers": 1200,
    "branches": 1000
}

date_columns = {
    "service_requests": [
        "request_created_date", "last_updated_date",
        "resolved_date"
    ],
    "updates": ["update_date"],
    "complaints": ["complaint_date"],
    "tickets": ["ticket_created_date"]
}

relationships = [
    ("service_requests", "customer_id", "customers", "customer_id"),
    ("service_requests", "branch_id", "branches", "branch_id"),
    ("updates", "request_id", "service_requests", "request_id"),
    ("complaints", "request_id", "service_requests", "request_id"),
    ("complaints", "customer_id", "customers", "customer_id"),
    ("tickets", "request_id", "service_requests", "request_id"),
    ("tickets", "customer_id", "customers", "customer_id"),
    ("customers", "preferred_branch_id", "branches", "branch_id")
]

missing_tokens = {
    "", "not_available", "n/a", "na", "null", "none"
}

missing_files = [
    filename for filename in dataset_files.values()
    if not isinstance(loaded_data.get(filename), pd.DataFrame)
]

if missing_files:
    raise ValueError(
        "Section 5 data is missing or is not a DataFrame: "
        + ", ".join(missing_files)
    )

cleaned_data = {
    name: loaded_data[filename].copy(deep=True)
    for name, filename in dataset_files.items()
}

cleaning_log = []
invalid_date_records = []
duplicate_quarantine = pd.DataFrame()

requests_df = cleaned_data["service_requests"]

duplicate_mask = requests_df["request_id"].notna() & (
    requests_df["request_id"].duplicated(keep="first")
)

duplicate_quarantine = requests_df.loc[duplicate_mask].copy()

if not duplicate_quarantine.empty:
    duplicate_quarantine["quarantine_reason"] = (
        "Repeated request_id; later occurrence isolated for review"
    )

    cleaned_data["service_requests"] = (
        requests_df.loc[~duplicate_mask].copy()
    )

cleaning_log.append({
    "dataset": "service_requests",
    "action": "Quarantine repeated request IDs",
    "rows_affected": len(duplicate_quarantine),
    "status": (
        "Review required" if len(duplicate_quarantine) else "Passed"
    )
})

for dataset_name, columns in date_columns.items():
    source_df = loaded_data[dataset_files[dataset_name]]
    working_df = cleaned_data[dataset_name]

    for column in columns:
        if column not in source_df.columns:
            continue

        raw = source_df[column]
        text_values = raw.astype("string").str.strip()

        missing_mask = (
            raw.isna()
            | text_values.eq("").fillna(False)
            | text_values.str.lower().isin(missing_tokens)
        )

        parsed_source = pd.to_datetime(
            raw.where(~missing_mask),
            format="%Y-%m-%d",
            errors="coerce"
        )

        invalid_mask = ~missing_mask & parsed_source.isna()

        for idx in source_df.index[invalid_mask]:
            invalid_date_records.append({
                "dataset": dataset_files[dataset_name],
                "row_index": idx,
                "column": column,
                "original_value": raw.loc[idx]
            })

        work_raw = working_df[column]
        work_text = work_raw.astype("string").str.strip()

        work_missing = (
            work_raw.isna()
            | work_text.eq("").fillna(False)
            | work_text.str.lower().isin(missing_tokens)
        )

        working_df[column] = pd.to_datetime(
            work_raw.where(~work_missing),
            format="%Y-%m-%d",
            errors="coerce"
        )

        cleaning_log.append({
            "dataset": dataset_files[dataset_name],
            "action": f"Normalize {column}",
            "rows_affected": int(invalid_mask.sum()),
            "status": (
                "Review required" if invalid_mask.any() else "Passed"
            )
        })

invalid_date_audit_df = pd.DataFrame(
    invalid_date_records,
    columns=["dataset", "row_index", "column", "original_value"]
)

cleaning_log_df = pd.DataFrame(cleaning_log)

class DataValidator:

    def __init__(
        self, required_columns, primary_keys,
        expected_columns, date_columns
    ):
        self.required_columns = required_columns
        self.primary_keys = primary_keys
        self.expected_columns = expected_columns
        self.date_columns = date_columns
        self.report = []

    def add_result(
        self, dataset, check_type, column_or_key,
        issue_count, severity, status, message
    ):
        self.report.append({
            "dataset": dataset,
            "check_type": check_type,
            "column_or_key": column_or_key,
            "issue_count": int(issue_count),
            "severity": severity,
            "status": status,
            "message": message
        })

    def validate(self, dataset_name, df):
        if not isinstance(df, pd.DataFrame):
            self.add_result(
                dataset_name, "Dataset Availability", "-",
                1, "Critical", "Failed",
                "Dataset is unavailable or is not a DataFrame."
            )
            return

        required = self.required_columns[dataset_name]

        missing = [
            col for col in required if col not in df.columns
        ]

        self.add_result(
            dataset_name, "Required Columns",
            ", ".join(missing) if missing else "All required",
            len(missing), "Critical",
            "Failed" if missing else "Passed",
            "Required columns are missing."
            if missing else "All required columns are present."
        )

        extras = sorted(
            set(df.columns) - set(self.expected_columns[dataset_name])
        )

        self.add_result(
            dataset_name, "Extra Columns",
            ", ".join(extras) if extras else "-",
            len(extras), "Warning",
            "Review" if extras else "Passed",
            "Unexpected columns detected."
            if extras else "Schema matches configured columns."
        )

        for col in [
            key for key in required if key.endswith("_id")
        ]:
            if col not in df.columns:
                continue

            count = int(df[col].isna().sum())

            self.add_result(
                dataset_name, "Critical Nulls", col,
                count, "Critical",
                "Failed" if count else "Passed",
                f"{count} missing identifier values."
                if count else "No missing identifier values."
            )

        key = self.primary_keys[dataset_name]

        if key in df.columns:
            non_null = df.loc[df[key].notna(), key]
            count = int(non_null.duplicated(keep=False).sum())

            self.add_result(
                dataset_name, "Duplicate IDs", key,
                count, "Critical",
                "Failed" if count else "Passed",
                f"{count} rows belong to duplicated IDs."
                if count else "Primary keys are unique."
            )

        for col in self.date_columns.get(dataset_name, []):
            if col not in df.columns:
                continue

            invalid_count = int(
                df[col].notna().sum()
                - pd.to_datetime(df[col], errors="coerce").notna().sum()
            )

            self.add_result(
                dataset_name, "Invalid Dates", col,
                invalid_count, "Warning",
                "Review" if invalid_count else "Passed",
                f"{invalid_count} invalid dates remain."
                if invalid_count else
                "No invalid non-missing dates remain in working copy."
            )

    def validate_relationship(
        self, child_name, child_df, child_col,
        parent_name, parent_df, parent_col
    ):
        if child_col not in child_df.columns:
            self.add_result(
                child_name, "Orphan Records", child_col,
                0, "Warning", "Skipped",
                f"Child key {child_col} is missing."
            )
            return

        if parent_col not in parent_df.columns:
            self.add_result(
                child_name, "Orphan Records", child_col,
                0, "Warning", "Skipped",
                f"Parent key {parent_col} is missing."
            )
            return

        child_ids = child_df[child_col].dropna()
        parent_ids = set(parent_df[parent_col].dropna())

        count = int((~child_ids.isin(parent_ids)).sum())

        self.add_result(
            child_name, "Orphan Records",
            f"{child_col} -> {parent_name}.{parent_col}",
            count, "Warning",
            "Review" if count else "Passed",
            f"{count} references have no matching parent."
            if count else "All non-null references match."
        )

    def to_dataframe(self):
        return pd.DataFrame(
            self.report,
            columns=[
                "dataset", "check_type", "column_or_key",
                "issue_count", "severity", "status", "message"
            ]
        )
datasets = cleaned_data

validator = DataValidator(
    required_columns,
    primary_keys,
    expected_columns,
    date_columns
)

for dataset_name, df in datasets.items():
    validator.validate(dataset_name, df)

for child, child_col, parent, parent_col in relationships:
    child_df = datasets.get(child)
    parent_df = datasets.get(parent)

    if isinstance(child_df, pd.DataFrame) and isinstance(
        parent_df, pd.DataFrame
    ):
        validator.validate_relationship(
            child, child_df, child_col,
            parent, parent_df, parent_col
        )
    else:
        validator.add_result(
            child, "Orphan Records",
            f"{child_col} -> {parent}.{parent_col}",
            0, "Warning", "Skipped",
            "One or both datasets are unavailable."
        )

for dataset_name, expected_count in expected_row_counts.items():
    source_df = loaded_data[dataset_files[dataset_name]]
    actual_count = len(source_df)
    mismatch = actual_count != expected_count

    validator.add_result(
        dataset_name, "Source Row Count", "Total rows",
        abs(actual_count - expected_count),
        "Warning",
        "Review" if mismatch else "Passed",
        f"Expected {expected_count}; found {actual_count}."
    )

for dataset_name, columns in date_columns.items():
    filename = dataset_files[dataset_name]

    for column in columns:
        count = int(
            (
                (invalid_date_audit_df["dataset"] == filename)
                & (invalid_date_audit_df["column"] == column)
            ).sum()
        )

        validator.add_result(
            dataset_name, "Source Date Quality", column,
            count, "Warning",
            "Review" if count else "Passed",
            f"{count} invalid non-empty source date values; "
            "see invalid_date_audit_df."
            if count else "No invalid non-empty source date values."
        )

validator.add_result(
    "service_requests", "Duplicate Quarantine", "request_id",
    len(duplicate_quarantine), "Warning",
    "Review" if len(duplicate_quarantine) else "Passed",
    f"{len(duplicate_quarantine)} duplicate rows isolated. "
    "The first-occurrence retention rule remains provisional."
    if len(duplicate_quarantine) else "No duplicate rows quarantined."
)

notes = loaded_data.get("status_notes.txt")

if isinstance(notes, list):
    validator.add_result(
        "status_notes", "Dataset Availability", "Text lines",
        0, "Warning", "Passed",
        f"Loaded {len(notes)} non-empty text lines."
    )
else:
    validator.add_result(
        "status_notes", "Dataset Availability", "Text lines",
        1, "Warning", "Failed",
        "Text notes unavailable or in an unexpected format."
    )

data_validation_report = validator.to_dataframe()

print("=" * 65)
print("SECTION 6: DATA VALIDATION REPORT")
print("=" * 65)
display(data_validation_report)

print("\nCLEANING LOG")
display(cleaning_log_df)

print("\nDUPLICATE QUARANTINE")
display(duplicate_quarantine)

print("\nINVALID SOURCE DATE AUDIT")
display(invalid_date_audit_df)

critical_failures = data_validation_report[
    (data_validation_report["severity"] == "Critical")
    & (data_validation_report["status"] == "Failed")
]

review_items = data_validation_report[
    data_validation_report["status"].isin(["Review", "Skipped"])
]

print("\nTOTAL CHECKS:", len(data_validation_report))
print("CRITICAL FAILURES:", len(critical_failures))
print("ITEMS REQUIRING REVIEW:", len(review_items))

if not critical_failures.empty:
    print("PIPELINE STATUS: BLOCKED - critical failures remain.")
elif not review_items.empty:
    print("PIPELINE STATUS: REVIEW REQUIRED - inspect flagged items.")
else:
    print("PIPELINE STATUS: PASSED - no flagged items detected.")

print("\nOriginal loaded_data was not modified.")

=================================================================
SECTION 6: DATA VALIDATION REPORT
=================================================================

,dataset,check_type,column_or_key,issue_count,severity,status,message
0,service_requests,Required Columns,All required,0,Critical,Passed,All required columns are present.
1,service_requests,Extra Columns,-,0,Warning,Passed,Schema matches configured columns.
2,service_requests,Critical Nulls,request_id,0,Critical,Passed,No missing identifier values.
3,service_requests,Critical Nulls,customer_id,0,Critical,Passed,No missing identifier values.
4,service_requests,Critical Nulls,branch_id,0,Critical,Passed,No missing identifier values.
5,service_requests,Duplicate IDs,request_id,0,Critical,Passed,Primary keys are unique.
6,service_requests,Invalid Dates,request_created_date,0,Warning,Passed,No invalid non-missing dates remain in working...
7,service_requests,Invalid Dates,last_updated_date,0,Warning,Passed,No invalid non-missing dates remain in working...
8,service_requests,Invalid Dates,resolved_date,0,Warning,Passed,No invalid non-missing dates remain in working...
9,updates,Required Columns,All required,0,Critical,Passed,All required columns are present.
10,updates,Extra Columns,-,0,Warning,Passed,Schema matches configured columns.
11,updates,Critical Nulls,update_id,0,Critical,Passed,No missing identifier values.
12,updates,Critical Nulls,request_id,0,Critical,Passed,No missing identifier values.
13,updates,Duplicate IDs,update_id,0,Critical,Passed,Primary keys are unique.
14,updates,Invalid Dates,update_date,0,Warning,Passed,No invalid non-missing dates remain in working...
15,complaints,Required Columns,All required,0,Critical,Passed,All required columns are present.
16,complaints,Extra Columns,-,0,Warning,Passed,Schema matches configured columns.
17,complaints,Critical Nulls,complaint_id,0,Critical,Passed,No missing identifier values.
18,complaints,Critical Nulls,request_id,0,Critical,Passed,No missing identifier values.
19,complaints,Critical Nulls,customer_id,0,Critical,Passed,No missing identifier values.
20,complaints,Duplicate IDs,complaint_id,0,Critical,Passed,Primary keys are unique.
21,complaints,Invalid Dates,complaint_date,0,Warning,Passed,No invalid non-missing dates remain in working...
22,tickets,Required Columns,All required,0,Critical,Passed,All required columns are present.
23,tickets,Extra Columns,-,0,Warning,Passed,Schema matches configured columns.
24,tickets,Critical Nulls,ticket_id,0,Critical,Passed,No missing identifier values.
25,tickets,Critical Nulls,request_id,0,Critical,Passed,No missing identifier values.
26,tickets,Critical Nulls,customer_id,0,Critical,Passed,No missing identifier values.
27,tickets,Duplicate IDs,ticket_id,0,Critical,Passed,Primary keys are unique.
28,tickets,Invalid Dates,ticket_created_date,0,Warning,Passed,No invalid non-missing dates remain in working...
29,customers,Required Columns,All required,0,Critical,Passed,All required columns are present.
30,customers,Extra Columns,-,0,Warning,Passed,Schema matches configured columns.
31,customers,Critical Nulls,customer_id,0,Critical,Passed,No missing identifier values.
32,customers,Critical Nulls,preferred_branch_id,0,Critical,Passed,No missing identifier values.
33,customers,Duplicate IDs,customer_id,0,Critical,Passed,Primary keys are unique.
34,branches,Required Columns,All required,0,Critical,Passed,All required columns are present.
35,branches,Extra Columns,-,0,Warning,Passed,Schema matches configured columns.
36,branches,Critical Nulls,branch_id,0,Critical,Passed,No missing identifier values.
37,branches,Duplicate IDs,branch_id,0,Critical,Passed,Primary keys are unique.
38,service_requests,Orphan Records,customer_id -> customers.customer_id,14,Warning,Review,14 references have no matching parent.
39,service_requests,Orphan Records,branch_id -> branches.branch_id,11,Warning,Review,11 references have no matching parent.
40,updates,Orphan Records,request_id -> service_requests.request_id,30,Warning,Review,30 references have no matching parent.
41,complaints,Orphan Records,request_id -> service_requests.request_id,29,Warning,Review,29 references have no matching parent.
42,complaints,Orphan Records,customer_id -> customers.customer_id,21,Warning,Review,21 references have no matching parent.
43,tickets,Orphan Records,request_id -> service_requests.request_id,31,Warning,Review,31 references have no matching parent.
44,tickets,Orphan Records,customer_id -> customers.customer_id,24,Warning,Review,24 references have no matching parent.
45,customers,Orphan Records,preferred_branch_id -> branches.branch_id,0,Warning,Passed,All non-null references match.
46,service_requests,Source Row Count,Total rows,0,Warning,Passed,Expected 5000; found 5000.
47,updates,Source Row Count,Total rows,0,Warning,Passed,Expected 1300; found 1300.
48,complaints,Source Row Count,Total rows,0,Warning,Passed,Expected 1500; found 1500.
49,tickets,Source Row Count,Total rows,0,Warning,Passed,Expected 1500; found 1500.
50,customers,Source Row Count,Total rows,0,Warning,Passed,Expected 1200; found 1200.
51,branches,Source Row Count,Total rows,0,Warning,Passed,Expected 1000; found 1000.
52,service_requests,Source Date Quality,request_created_date,6,Warning,Review,6 invalid non-empty source date values; see in...
53,service_requests,Source Date Quality,last_updated_date,0,Warning,Passed,No invalid non-empty source date values.
54,service_requests,Source Date Quality,resolved_date,0,Warning,Passed,No invalid non-empty source date values.
55,updates,Source Date Quality,update_date,5,Warning,Review,5 invalid non-empty source date values; see in...
56,complaints,Source Date Quality,complaint_date,8,Warning,Review,8 invalid non-empty source date values; see in...
57,tickets,Source Date Quality,ticket_created_date,6,Warning,Review,6 invalid non-empty source date values; see in...
58,service_requests,Duplicate Quarantine,request_id,8,Warning,Review,8 duplicate rows isolated. The first-occurrenc...
59,status_notes,Dataset Availability,Text lines,0,Warning,Passed,Loaded 100 non-empty text lines.

CLEANING LOG

                       dataset                           action  rows_affected           status
0             service_requests  Quarantine repeated request IDs              8  Review required
1         service_requests.csv   Normalize request_created_date              6  Review required
2         service_requests.csv      Normalize last_updated_date              0           Passed
3         service_requests.csv          Normalize resolved_date              0           Passed
4  request_status_updates.xlsx            Normalize update_date              5  Review required
5     customer_complaints.json         Normalize complaint_date              8  Review required
6          support_tickets.csv    Normalize ticket_created_date              6  Review required

DUPLICATE QUARANTINE

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,quarantine_reason
4992,REQ0001651,CUST000742,BR0292,2026-05-03,08:02:00,Complaint,Fraud Concern,call center,in_progress,72,Customer Grievance,0.0,2026-05-06,NaN,Repeated request_id; later occurrence isolated...
4993,REQ0000952,CUST000073,BR0204,2026-06-20,10:27:00,Card,Chargeback,Branch,in_progress,36,Cards Operations,0.0,2026-06-22,NaN,Repeated request_id; later occurrence isolated...
4994,REQ0003223,CUST001183,BR0953,2026-05-31,00:41:00,Account,Balance Mismatch,Branch,in_progress,48,Account Servicing,NaN,2026-06-02,NaN,Repeated request_id; later occurrence isolated...
4995,REQ0002230,CUST001040,BR0461,2026-03-18,10:07:00,Card,Failed ATM Withdrawal,Email,in_progress,36,Cards Operations,0.0,2026-03-20,NaN,Repeated request_id; later occurrence isolated...
4996,REQ0000432,CUST000049,BR0109,2026-06-05,04:21:00,digital banking,Beneficiary Issue,WhatsApp,in_progress,24,Digital Banking Support,10010.29,2026-06-06,2026-06-06,Repeated request_id; later occurrence isolated...
4997,REQ0001769,CUST000433,BR0516,2026-03-09,06:10:00,Card,Chargeback,Call Center,in_progress,36,Cards Operations,26071.49,2026-03-11,NaN,Repeated request_id; later occurrence isolated...
4998,REQ0004378,CUST000876,BR0929,2026-02-02,16:30:00,Card,PIN Reset,NetBanking,in_progress,36,Cards Operations,0.0,2026-02-04,NaN,Repeated request_id; later occurrence isolated...
4999,REQ0003027,CUST000096,BR0749,2026-03-22,03:43:00,Digital Banking,UPI Issue,Email,in_progress,24,Digital Banking Support,109794.42,2026-03-23,2026-03-22,Repeated request_id; later occurrence isolated...

INVALID SOURCE DATE AUDIT

                        dataset  row_index                column original_value
0          service_requests.csv         35  request_created_date     2026-02-30
1          service_requests.csv        746  request_created_date     2026-02-30
2          service_requests.csv       1701  request_created_date     2026-02-30
3          service_requests.csv       2592  request_created_date     2026-02-30
4          service_requests.csv       4081  request_created_date     2026-02-30
5          service_requests.csv       4879  request_created_date     2026-02-30
6   request_status_updates.xlsx        147           update_date     2026-15-02
7   request_status_updates.xlsx        364           update_date     2026-15-02
8   request_status_updates.xlsx        378           update_date     2026-15-02
9   request_status_updates.xlsx        837           update_date     2026-15-02
10  request_status_updates.xlsx       1112           update_date     2026-15-02
11     customer_complaints.json         58        complaint_date     2026-13-10
12     customer_complaints.json         71        complaint_date     2026-13-10
13     customer_complaints.json        736        complaint_date     2026-13-10
14     customer_complaints.json        795        complaint_date     2026-13-10
15     customer_complaints.json        804        complaint_date     2026-13-10
16     customer_complaints.json        978        complaint_date     2026-13-10
17     customer_complaints.json        983        complaint_date     2026-13-10
18     customer_complaints.json        996        complaint_date     2026-13-10
19          support_tickets.csv        340   ticket_created_date     not_a_date
20          support_tickets.csv        653   ticket_created_date     not_a_date
21          support_tickets.csv        967   ticket_created_date     not_a_date
22          support_tickets.csv       1108   ticket_created_date     not_a_date
23          support_tickets.csv       1122   ticket_created_date     not_a_date
24          support_tickets.csv       1158   ticket_created_date     not_a_date

TOTAL CHECKS: 60
CRITICAL FAILURES: 0
ITEMS REQUIRING REVIEW: 12
PIPELINE STATUS: REVIEW REQUIRED - inspect flagged items.

Original loaded_data was not modified.

### Expected Output — Section 6: Data Validation Engine

**Datasets to use:**

- All loaded datasets from Section 5.

**How to approach:**

- Create a dictionary of required columns for each dataset.
- Validate required columns, extra columns, duplicate IDs, nulls in critical columns, orphan records, and invalid dates.
- Critical fields include IDs such as `request_id`, `customer_id`, `branch_id`, `update_id`, `complaint_id`, and `ticket_id`.
- Keep validation warnings visible instead of silently ignoring issues.

**Expected output format:**

Create a visible table named `data_validation_report` with columns like:

| dataset | check_type | column_or_key | issue_count | severity | status | message |
|---|---|---|---:|---|---|---|
| service_requests | Required Columns | request_id | 0 | Critical | Passed | Required column present |
| complaints | Orphan Request IDs | request_id | some number | Warning | Review | Some complaint records may not match service requests |

**Hint:** Separate **critical errors** from **warnings**. Critical errors should stop the pipeline; warnings should be logged and reviewed.

In [ ]:
import pandas as pd
import numpy as np
import re

print("SECTION 7: DATA CLEANING AND STANDARDIZATION")

if "loaded_data" not in globals():
    raise RuntimeError("loaded_data is missing. Run Section 5 first.")

required_datasets = {
    "service_requests": "service_requests.csv",
    "updates": "request_status_updates.xlsx",
    "complaints": "customer_complaints.json",
    "tickets": "support_tickets.csv",
    "customers": "customers.csv",
    "branches": "branches.csv",
}

missing_datasets = [
    filename for filename in required_datasets.values()
    if filename not in loaded_data
    or not isinstance(loaded_data[filename], pd.DataFrame)
]

if missing_datasets:
    raise ValueError(f"Missing or invalid source datasets: {missing_datasets}")

if "cleaned_data" in globals():
    source_working_data = cleaned_data
else:
    source_working_data = {
        name: loaded_data[filename].copy(deep=True)
        for name, filename in required_datasets.items()
    }

missing_working_datasets = [
    name for name in required_datasets
    if name not in source_working_data
    or not isinstance(source_working_data[name], pd.DataFrame)
]

if missing_working_datasets:
    raise ValueError(
        f"Missing Section 6 working datasets: {missing_working_datasets}"
    )

standardized_data = {
    name: df.copy(deep=True)
    for name, df in source_working_data.items()
}

cleaning_log = []
evidence_rows = []
invalid_date_rows = []
invalid_numeric_rows = []
missing_field_rows = []
review_rows = []

date_columns = {
    "service_requests": [
        "request_created_date", "last_updated_date", "resolved_date"
    ],
    "updates": ["update_date"],
    "complaints": ["complaint_date"],
    "tickets": ["ticket_created_date"],
    "customers": [],
    "branches": [],
}

numeric_columns = {
    "service_requests": ["sla_hours", "reported_amount"],
    "updates": [],
    "complaints": [],
    "tickets": ["resolution_time_hours"],
    "customers": ["relationship_age_days"],
    "branches": [],
}

category_map = {
    "account": "Account",
    "card": "Card",
    "loan": "Loan",
    "kyc": "KYC",
    "complaint": "Complaint",
    "digital banking": "Digital Banking",
    "digitalbanking": "Digital Banking",
    "digital banking support": "Digital Banking",
}

channel_map = {
    "call center": "Call Center",
    "callcentre": "Call Center",
    "call centre": "Call Center",
    "callcenter": "Call Center",
    "branch": "Branch",
    "email": "Email",
    "whatsapp": "WhatsApp",
    "netbanking": "NetBanking",
    "net banking": "NetBanking",
    "mobile banking": "Mobile Banking",
    "mobile app": "Mobile Banking",
    "website": "Website",
    "web": "Website",
}

missing_tokens = {
    "", "not_available", "not available", "n/a",
    "na", "null", "none", "nan"
}

id_columns = {
    "request_id", "customer_id", "branch_id", "update_id",
    "complaint_id", "ticket_id", "preferred_branch_id",
    "assigned_team"
}

def normalize_text(value):
    """Trim edges and collapse repeated whitespace."""
    if pd.isna(value):
        return value

    text = str(value).strip()
    text = re.sub(r"\s+", " ", text)

    if text.lower() in missing_tokens:
        return np.nan

    return text


def normalize_status(value):
    """Standardize status spelling to lowercase snake_case."""
    value = normalize_text(value)

    if pd.isna(value):
        return np.nan

    value = value.lower()
    value = re.sub(r"[\s-]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")

    return value

def normalize_category(value):
    """Map recognized categories to canonical business labels."""
    value = normalize_text(value)

    if pd.isna(value):
        return np.nan

    key = value.lower()
    if key in category_map:
        return category_map[key]

    review_rows.append({
        "dataset": "service_requests",
        "column": "request_category",
        "value": value,
        "reason": "Unrecognized category; original meaning preserved."
    })
    return value

def normalize_channel(value):
    """Standardize recognized channel names."""
    value = normalize_text(value)

    if pd.isna(value):
        return np.nan

    key = value.lower()
    if key in channel_map:
        return channel_map[key]

    review_rows.append({
        "dataset": "service_requests",
        "column": "channel",
        "value": value,
        "reason": "Unrecognized channel; original meaning preserved."
    })
    return value


def add_log(dataset, column, action, affected, status, notes=""):
    cleaning_log.append({
        "dataset": dataset,
        "column": column,
        "action": action,
        "rows_affected": int(affected),
        "status": status,
        "notes": notes,
    })

def source_frame(dataset_name):
    filename = required_datasets[dataset_name]
    return loaded_data[filename]


def add_value_count_evidence(dataset, column, before, after):
    before_counts = (
        before.astype("string").fillna("<MISSING>")
        .value_counts(dropna=False).to_dict()
    )
    after_counts = (
        after.astype("string").fillna("<MISSING>")
        .value_counts(dropna=False).to_dict()
    )

    evidence_rows.append({
        "dataset": dataset,
        "cleaning_area": column,
        "before_evidence": str(before_counts),
        "after_evidence": str(after_counts),
    })

for dataset_name, df in standardized_data.items():
    original = source_frame(dataset_name)

    excluded_text_columns = (
        set(date_columns.get(dataset_name, []))
        | set(numeric_columns.get(dataset_name, []))
        | id_columns
    )

    for column in df.select_dtypes(include=["object", "string"]).columns:
        if column in excluded_text_columns:
            continue

        before = original[column] if column in original.columns else df[column].copy()
        old_values = df[column].copy()
        df[column] = df[column].map(normalize_text)

        changed = int(
            old_values.astype("string").fillna("<MISSING>").ne(
                df[column].astype("string").fillna("<MISSING>")
            ).sum()
        )

        if changed:
            add_log(
                dataset_name, column, "Trim/standardize text",
                changed, "Passed",
                "Whitespace and recognized missing-value tokens standardized."
            )

    if dataset_name == "service_requests" and "request_category" in df.columns:
        before = original["request_category"].copy()
        df["request_category"] = df["request_category"].map(normalize_category)
        add_value_count_evidence(
            dataset_name, "request_category", before, df["request_category"]
        )
        add_log(
            dataset_name, "request_category",
            "Map recognized categories to canonical labels",
            int(before.astype("string").fillna("<MISSING>").ne(
                df["request_category"].astype("string").fillna("<MISSING>")
            ).sum()),
            "Review required" if review_rows else "Passed",
            "Unrecognized categories are preserved and flagged."
        )

    if dataset_name == "service_requests" and "channel" in df.columns:
        before = original["channel"].copy()
        df["channel"] = df["channel"].map(normalize_channel)
        add_value_count_evidence(dataset_name, "channel", before, df["channel"])

    status_columns = {
        "service_requests": ["request_status"],
        "updates": ["status_from", "status_to"],
        "complaints": ["complaint_status"],
        "tickets": ["ticket_status"],
    }.get(dataset_name, [])

    for column in status_columns:
        if column not in df.columns:
            continue

        before = original[column].copy()
        old_values = df[column].copy()
        df[column] = df[column].map(normalize_status)

        add_value_count_evidence(
            dataset_name, column, before, df[column]
        )

        changed = int(
            old_values.astype("string").fillna("<MISSING>").ne(
                df[column].astype("string").fillna("<MISSING>")
            ).sum()
        )
        add_log(
            dataset_name, column, "Standardize status labels",
            changed, "Passed",
            "Lowercase snake_case; no rows deleted."
        )


    for column in date_columns.get(dataset_name, []):
        if column not in df.columns:
            continue

        raw = (
            original[column].reindex(df.index)
            if column in original.columns
            else df[column].copy()
        )

        raw_text = raw.astype("string").str.strip()
        is_missing = (
            raw.isna()
            | raw_text.fillna("").eq("")
            | raw_text.fillna("").str.lower().isin(missing_tokens)
        )

        parsed_source = pd.to_datetime(raw, errors="coerce")
        invalid_mask = (~is_missing) & parsed_source.isna()

        for idx in raw.index[invalid_mask]:
            invalid_date_rows.append({
                "dataset": required_datasets[dataset_name],
                "row_index": idx,
                "column": column,
                "original_value": raw.loc[idx],
            })

        old_values = df[column].copy()
        df[column] = pd.to_datetime(df[column], errors="coerce")


        flag_column = f"{column}_invalid_flag"
        df[flag_column] = invalid_mask.reindex(df.index, fill_value=False).astype(bool)

        invalid_count = int(invalid_mask.sum())
        add_log(
            dataset_name, column, "Parse date with errors='coerce'",
            invalid_count,
            "Review required" if invalid_count else "Passed",
            f"Invalid source values flagged in {flag_column}; rows retained."
        )

        evidence_rows.append({
            "dataset": dataset_name,
            "cleaning_area": f"{column} (date)",
            "before_evidence": f"Source dtype: {raw.dtype}; invalid values: {invalid_count}",
            "after_evidence": (
                f"Working dtype: {df[column].dtype}; "
                f"invalid flags: {int(df[flag_column].sum())}"
            ),
        })

    for column in numeric_columns.get(dataset_name, []):
        if column not in df.columns:
            continue

        raw = (
            original[column].reindex(df.index)
            if column in original.columns
            else df[column].copy()
        )

        raw_text = raw.astype("string").str.strip()
        is_missing = (
            raw.isna()
            | raw_text.fillna("").eq("")
            | raw_text.fillna("").str.lower().isin(missing_tokens)
        )


        numeric_text = (
            df[column].astype("string").str.strip()
            .str.replace(",", "", regex=False)
            .str.replace(r"^[₹$]\s*", "", regex=True)
        )
        converted = pd.to_numeric(numeric_text, errors="coerce")

        invalid_numeric_mask = (~is_missing) & converted.isna()

        for idx in raw.index[invalid_numeric_mask]:
            invalid_numeric_rows.append({
                "dataset": required_datasets[dataset_name],
                "row_index": idx,
                "column": column,
                "original_value": raw.loc[idx],
            })

        before_dtype = str(df[column].dtype)
        df[column] = converted

        add_log(
            dataset_name, column, "Convert to numeric",
            int(invalid_numeric_mask.sum()),
            "Review required" if invalid_numeric_mask.any() else "Passed",
            f"{before_dtype} -> {df[column].dtype}; invalid values become NaN."
        )

        evidence_rows.append({
            "dataset": dataset_name,
            "cleaning_area": f"{column} (numeric)",
            "before_evidence": f"dtype: {before_dtype}",
            "after_evidence": (
                f"dtype: {df[column].dtype}; "
                f"invalid values: {int(invalid_numeric_mask.sum())}"
            ),
        })

business_fields = {
    "service_requests": [
        "request_category", "request_status", "channel",
        "assigned_team", "sla_hours"
    ],
    "updates": ["status_from", "status_to", "updated_by_role"],
    "complaints": ["complaint_type", "complaint_status", "sentiment_tag"],
    "tickets": ["ticket_status", "assigned_team", "resolution_time_hours"],
    "customers": ["customer_segment", "account_type"],
    "branches": ["branch_city", "branch_state", "branch_zone", "branch_type"],
}

for dataset_name, columns in business_fields.items():
    df = standardized_data[dataset_name]

    for column in columns:
        if column not in df.columns:
            continue

        missing_count = int(df[column].isna().sum())
        if missing_count:
            missing_field_rows.append({
                "dataset": dataset_name,
                "column": column,
                "missing_count": missing_count,
                "action": "Flagged for review; no invented default applied."
            })


cleaning_log_df = pd.DataFrame(cleaning_log)
cleaning_evidence_df = pd.DataFrame(evidence_rows)
invalid_date_audit_df = pd.DataFrame(invalid_date_rows)
invalid_numeric_audit_df = pd.DataFrame(invalid_numeric_rows)
missing_business_fields_df = pd.DataFrame(missing_field_rows)
standardization_review_df = pd.DataFrame(review_rows)

cleaned_data = standardized_data

print("BEFORE/AFTER CLEANING EVIDENCE")
display(cleaning_evidence_df)


print("CLEANING LOG")
display(cleaning_log_df)


print("INVALID SOURCE DATE AUDIT")
display(invalid_date_audit_df)


print("INVALID NUMERIC VALUE AUDIT")
display(invalid_numeric_audit_df)

print("MISSING BUSINESS FIELDS")
display(missing_business_fields_df)

print("UNRECOGNIZED CATEGORY / CHANNEL VALUES")
display(standardization_review_df)

print("SECTION 7 SUMMARY")
print("Datasets standardized:", len(cleaned_data))
print("Rows deleted by Section 7: 0")
print("Invalid source dates flagged:", len(invalid_date_audit_df))
print("Invalid numeric values flagged:", len(invalid_numeric_audit_df))
print("Missing business-field checks:", len(missing_business_fields_df))
print("Original loaded_data modified: No")
print("Output dictionary: cleaned_data")
print("Section 7 completed. Review the audit tables above.")

SECTION 7: DATA CLEANING AND STANDARDIZATION
BEFORE/AFTER CLEANING EVIDENCE

             dataset                    cleaning_area                                    before_evidence                                     after_evidence
0   service_requests                 request_category  {'Account': 844, 'Digital Banking': 822, 'Card...  {'Account': 866, 'Digital Banking': 841, 'Loan...
1   service_requests                          channel  {'Call Center': 840, 'NetBanking': 829, 'Mobil...  {'Call Center': 863, 'Mobile Banking': 845, 'N...
2   service_requests                   request_status  {'Resolved': 1404, 'In Progress': 1193, 'Close...  {'resolved': 1463, 'in_progress': 1243, 'close...
3   service_requests      request_created_date (date)            Source dtype: object; invalid values: 6    Working dtype: datetime64[ns]; invalid flags: 6
4   service_requests         last_updated_date (date)            Source dtype: object; invalid values: 0    Working dtype: datetime64[ns]; invalid flags: 0
5   service_requests             resolved_date (date)            Source dtype: object; invalid values: 0    Working dtype: datetime64[ns]; invalid flags: 0
6   service_requests              sla_hours (numeric)                                       dtype: int64                    dtype: Int64; invalid values: 0
7   service_requests        reported_amount (numeric)                                      dtype: object                  dtype: Float64; invalid values: 3
8            updates                      status_from  {'Escalated': 354, 'Pending Customer': 342, 'I...  {'escalated': 354, 'pending_customer': 342, 'i...
9            updates                        status_to  {'Resolved': 270, 'In Progress': 270, 'Escalat...  {'resolved': 270, 'in_progress': 270, 'escalat...
10           updates               update_date (date)            Source dtype: object; invalid values: 5    Working dtype: datetime64[ns]; invalid flags: 5
11        complaints                 complaint_status  {'Reopened': 263, 'Resolved': 251, 'Escalated'...  {'reopened': 274, 'resolved': 255, 'escalated'...
12        complaints            complaint_date (date)            Source dtype: object; invalid values: 8    Working dtype: datetime64[ns]; invalid flags: 8
13           tickets                    ticket_status  {'Open': 262, 'Reopened': 250, 'Escalated': 24...  {'open': 268, 'reopened': 258, 'escalated': 24...
14           tickets       ticket_created_date (date)            Source dtype: object; invalid values: 6    Working dtype: datetime64[ns]; invalid flags: 6
15           tickets  resolution_time_hours (numeric)                                     dtype: float64                  dtype: Float64; invalid values: 0
16         customers  relationship_age_days (numeric)                                       dtype: int64                    dtype: Int64; invalid values: 0

CLEANING LOG

,dataset,column,action,rows_affected,status,notes
0,service_requests,request_category,Trim/standardize text,134,Passed,Whitespace and recognized missing-value tokens...
1,service_requests,channel,Trim/standardize text,131,Passed,Whitespace and recognized missing-value tokens...
2,service_requests,request_category,Map recognized categories to canonical labels,134,Passed,Unrecognized categories are preserved and flag...
3,service_requests,request_status,Standardize status labels,4791,Passed,Lowercase snake_case; no rows deleted.
4,service_requests,request_created_date,Parse date with errors='coerce',6,Review required,Invalid source values flagged in request_creat...
5,service_requests,last_updated_date,Parse date with errors='coerce',0,Passed,Invalid source values flagged in last_updated_...
6,service_requests,resolved_date,Parse date with errors='coerce',0,Passed,Invalid source values flagged in resolved_date...
7,service_requests,sla_hours,Convert to numeric,0,Passed,int64 -> Int64; invalid values become NaN.
8,service_requests,reported_amount,Convert to numeric,3,Review required,object -> Float64; invalid values become NaN.
9,updates,status_from,Standardize status labels,1300,Passed,Lowercase snake_case; no rows deleted.
10,updates,status_to,Standardize status labels,1300,Passed,Lowercase snake_case; no rows deleted.
11,updates,update_date,Parse date with errors='coerce',5,Review required,Invalid source values flagged in update_date_i...
12,complaints,complaint_status,Standardize status labels,1472,Passed,Lowercase snake_case; no rows deleted.
13,complaints,complaint_date,Parse date with errors='coerce',8,Review required,Invalid source values flagged in complaint_dat...
14,tickets,ticket_status,Standardize status labels,1464,Passed,Lowercase snake_case; no rows deleted.
15,tickets,ticket_created_date,Parse date with errors='coerce',6,Review required,Invalid source values flagged in ticket_create...
16,tickets,resolution_time_hours,Convert to numeric,0,Passed,float64 -> Float64; invalid values become NaN.
17,customers,customer_segment,Trim/standardize text,42,Passed,Whitespace and recognized missing-value tokens...
18,customers,relationship_age_days,Convert to numeric,0,Passed,int64 -> Int64; invalid values become NaN.

INVALID SOURCE DATE AUDIT

                        dataset  row_index                column original_value
0          service_requests.csv         35  request_created_date     2026-02-30
1          service_requests.csv        746  request_created_date     2026-02-30
2          service_requests.csv       1701  request_created_date     2026-02-30
3          service_requests.csv       2592  request_created_date     2026-02-30
4          service_requests.csv       4081  request_created_date     2026-02-30
5          service_requests.csv       4879  request_created_date     2026-02-30
6   request_status_updates.xlsx        147           update_date     2026-15-02
7   request_status_updates.xlsx        364           update_date     2026-15-02
8   request_status_updates.xlsx        378           update_date     2026-15-02
9   request_status_updates.xlsx        837           update_date     2026-15-02
10  request_status_updates.xlsx       1112           update_date     2026-15-02
11     customer_complaints.json         58        complaint_date     2026-13-10
12     customer_complaints.json         71        complaint_date     2026-13-10
13     customer_complaints.json        736        complaint_date     2026-13-10
14     customer_complaints.json        795        complaint_date     2026-13-10
15     customer_complaints.json        804        complaint_date     2026-13-10
16     customer_complaints.json        978        complaint_date     2026-13-10
17     customer_complaints.json        983        complaint_date     2026-13-10
18     customer_complaints.json        996        complaint_date     2026-13-10
19          support_tickets.csv        340   ticket_created_date     not_a_date
20          support_tickets.csv        653   ticket_created_date     not_a_date
21          support_tickets.csv        967   ticket_created_date     not_a_date
22          support_tickets.csv       1108   ticket_created_date     not_a_date
23          support_tickets.csv       1122   ticket_created_date     not_a_date
24          support_tickets.csv       1158   ticket_created_date     not_a_date

INVALID NUMERIC VALUE AUDIT

                dataset  row_index           column  original_value
0  service_requests.csv        698  reported_amount  amount_pending
1  service_requests.csv       1698  reported_amount  amount_pending
2  service_requests.csv       2698  reported_amount  amount_pending

MISSING BUSINESS FIELDS

   dataset                 column  missing_count                                            action
0  tickets  resolution_time_hours            499  Flagged for review; no invented default applied.

UNRECOGNIZED CATEGORY / CHANNEL VALUES

Empty DataFrame
Columns: []
Index: []

SECTION 7 SUMMARY
Datasets standardized: 6
Rows deleted by Section 7: 0
Invalid source dates flagged: 25
Invalid numeric values flagged: 3
Missing business-field checks: 1
Original loaded_data modified: No
Output dictionary: cleaned_data
Section 7 completed. Review the audit tables above.

### Expected Output — Section 7: Data Cleaning and Standardization

**Datasets to use:**

- `service_requests.csv`
- `request_status_updates.xlsx`
- `customer_complaints.json`
- `support_tickets.csv`
- `customers.csv`
- `branches.csv`

**How to approach:**

- Standardize request statuses, categories, complaint statuses, ticket statuses, channels, dates, text fields, and amounts.
- Convert date columns using `pd.to_datetime(..., errors='coerce')`.
- Convert amount columns using numeric conversion with safe error handling.
- Fill missing business fields using PRD rules.
- Preserve raw IDs; do not create random IDs during cleaning.

**Expected output format:**

Show before/after evidence, for example:

| Cleaning Area | Before Evidence | After Evidence |
|---|---|---|
| Request status | Raw messy value counts | Standardized value counts |
| Request category | Raw messy categories | Account/Card/Loan/KYC/Complaint/Digital Banking |
| Date columns | Object/string types | Datetime types with invalid flags |
| Amount columns | Mixed/string values | Numeric dtype |

**Hint:** Do not over-clean by deleting rows aggressively. Most issues should be standardized, flagged, or filled according to business rules.

In [ ]:

import pandas as pd
import numpy as np

print("SECTION 8: SLA BREACH ANALYSIS")

# --------------------------------------------------
# 1. INPUT VALIDATION
# --------------------------------------------------
if "cleaned_data" not in globals():
    raise RuntimeError("cleaned_data is missing. Run Sections 5-7 first.")

if "service_requests" not in cleaned_data:
    raise KeyError("cleaned_data['service_requests'] was not found.")

required_columns = [
    "request_id",
    "request_created_date",
    "resolved_date",
    "request_status",
    "sla_hours",
    "request_category",
]

requests = cleaned_data["service_requests"].copy(deep=True)

missing_columns = [
    col for col in required_columns if col not in requests.columns
]

if missing_columns:
    raise ValueError(f"Missing required columns: {missing_columns}")

if requests["request_id"].isna().any():
    raise ValueError("Missing request_id values found in service requests.")

if requests["request_id"].duplicated().any():
    raise ValueError(
        "Duplicate request_id values found. Resolve them before SLA analysis."
    )

if "ANALYSIS_DATE" not in globals():
    ANALYSIS_DATE = pd.Timestamp.today().normalize()
else:
    ANALYSIS_DATE = pd.Timestamp(ANALYSIS_DATE)

if pd.isna(ANALYSIS_DATE):
    raise ValueError("ANALYSIS_DATE must be a valid date.")

NEAR_BREACH_THRESHOLD = 0.80

print("Analysis date:", ANALYSIS_DATE.date())
print("Near-breach threshold:", f"{NEAR_BREACH_THRESHOLD:.0%} of SLA")

# --------------------------------------------------
# 2. DATA TYPE CLEANING
# --------------------------------------------------
requests["request_created_date"] = pd.to_datetime(
    requests["request_created_date"], errors="coerce"
)

requests["resolved_date"] = pd.to_datetime(
    requests["resolved_date"], errors="coerce"
)

requests["sla_hours"] = pd.to_numeric(
    requests["sla_hours"], errors="coerce"
)

# Preserve existing cleaning flags when available.
invalid_flag_column = "request_created_date_invalid_flag"

if invalid_flag_column in requests.columns:
    requests["invalid_created_date_flag"] = (
        requests[invalid_flag_column]
        .fillna(False)
        .astype(bool)
    )
else:
    requests["invalid_created_date_flag"] = (
        requests["request_created_date"].isna()
    )

# Normalize request status.
requests["request_status"] = (
    requests["request_status"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"[\s-]+", "_", regex=True)
)

# --------------------------------------------------
# 3. REQUEST STATUS AND ELAPSED TIME
# --------------------------------------------------
completed_statuses = {"resolved", "closed"}

requests["is_resolved_or_closed"] = (
    requests["request_status"].isin(completed_statuses)
)

requests["is_pending_unresolved"] = (
    ~requests["is_resolved_or_closed"]
    & requests["request_status"].notna()
)

requests["elapsed_time_basis"] = np.where(
    requests["resolved_date"].notna(),
    "resolved_date",
    "ANALYSIS_DATE"
)

requests["elapsed_end_date"] = requests["resolved_date"].fillna(
    ANALYSIS_DATE
)

requests["missing_resolved_date_flag"] = (
    requests["is_resolved_or_closed"]
    & requests["resolved_date"].isna()
)

requests["elapsed_hours"] = (
    requests["elapsed_end_date"] - requests["request_created_date"]
).dt.total_seconds() / 3600

requests["negative_elapsed_flag"] = (
    requests["elapsed_hours"] < 0
)

requests["invalid_elapsed_flag"] = (
    requests["request_created_date"].isna()
    | requests["elapsed_hours"].isna()
    | requests["negative_elapsed_flag"]
)

requests["invalid_sla_flag"] = (
    requests["sla_hours"].isna()
    | (requests["sla_hours"] <= 0)
)

requests["sla_assessable_flag"] = (
    ~requests["invalid_elapsed_flag"]
    & ~requests["invalid_sla_flag"]
)

# --------------------------------------------------
# 4. SLA BREACH AND NEAR-BREACH FLAGS
# --------------------------------------------------
requests["sla_breached"] = (
    requests["sla_assessable_flag"]
    & (requests["elapsed_hours"] > requests["sla_hours"])
)

requests["near_sla_breach"] = (
    requests["sla_assessable_flag"]
    & ~requests["sla_breached"]
    & (
        requests["elapsed_hours"]
        >= requests["sla_hours"] * NEAR_BREACH_THRESHOLD
    )
)

# --------------------------------------------------
# 5. FIX: CREATE THE REQUIRED SLA STATUS COLUMN
# --------------------------------------------------
# Invalid/unassessable requests are kept separate from
# requests confirmed to be within SLA.
requests["sla_status"] = "Within SLA"

requests.loc[
    ~requests["sla_assessable_flag"],
    "sla_status"
] = "Not Assessable"

requests.loc[
    requests["near_sla_breach"],
    "sla_status"
] = "Near Breach"

requests.loc[
    requests["sla_breached"],
    "sla_status"
] = "Breached"

# --------------------------------------------------
# 6. SERVICE REQUEST HEALTH SUMMARY
# --------------------------------------------------
health_metrics = {
    "total_requests": int(len(requests)),
    "resolved_or_closed_requests": int(
        requests["is_resolved_or_closed"].sum()
    ),
    "pending_unresolved_requests": int(
        requests["is_pending_unresolved"].sum()
    ),
    "sla_breached_requests": int(requests["sla_breached"].sum()),
    "near_sla_breach_requests": int(requests["near_sla_breach"].sum()),
    "invalid_created_date_records": int(
        requests["invalid_created_date_flag"].sum()
    ),
    "unassessable_sla_requests": int(
        (~requests["sla_assessable_flag"]).sum()
    ),
}

service_request_health_summary = pd.DataFrame(
    [
        {"Metric": metric, "Value": value}
        for metric, value in health_metrics.items()
    ]
)

# --------------------------------------------------
# 7. CATEGORY-WISE SLA SUMMARY
# --------------------------------------------------
requests["category_for_summary"] = (
    requests["request_category"].astype("string").fillna("Unknown")
)

sla_category_summary = (
    requests.groupby("category_for_summary", dropna=False)
    .agg(
        total_requests=("request_id", "size"),
        pending_requests=("is_pending_unresolved", "sum"),
        sla_breaches=("sla_breached", "sum"),
        near_sla_breaches=("near_sla_breach", "sum"),
        avg_elapsed_hours=("elapsed_hours", "mean"),
    )
    .reset_index()
    .rename(columns={"category_for_summary": "request_category"})
)

for col in [
    "total_requests",
    "pending_requests",
    "sla_breaches",
    "near_sla_breaches",
]:
    sla_category_summary[col] = sla_category_summary[col].astype(int)

sla_category_summary["avg_elapsed_hours"] = (
    sla_category_summary["avg_elapsed_hours"].round(2)
)

# --------------------------------------------------
# 8. SLA DATA QUALITY REVIEW
# --------------------------------------------------
sla_data_quality_review = pd.DataFrame({
    "check": [
        "Invalid created-date records",
        "Missing resolved date on resolved/closed requests",
        "Missing or non-positive SLA values",
        "Negative elapsed durations",
        "Requests excluded from SLA assessment",
    ],
    "issue_count": [
        int(requests["invalid_created_date_flag"].sum()),
        int(requests["missing_resolved_date_flag"].sum()),
        int(requests["invalid_sla_flag"].sum()),
        int(requests["negative_elapsed_flag"].sum()),
        int((~requests["sla_assessable_flag"]).sum()),
    ],
})

# --------------------------------------------------
# 9. SAVE SECTION OUTPUT
# --------------------------------------------------
service_request_sla_analysis = requests.copy(deep=True)

# --------------------------------------------------
# 10. VALIDATION AND DISPLAY
# --------------------------------------------------
assert len(service_request_sla_analysis) == len(
    cleaned_data["service_requests"]
), "SLA analysis unexpectedly changed the request row count."

assert service_request_sla_analysis["request_id"].is_unique, (
    "SLA analysis contains duplicate request IDs."
)

assert "sla_status" in service_request_sla_analysis.columns

print("\nSERVICE REQUEST HEALTH SUMMARY")
display(service_request_health_summary)

print("\nCATEGORY-WISE SLA SUMMARY")
display(sla_category_summary)

print("\nSLA DATA QUALITY REVIEW")
display(sla_data_quality_review)

print("\nSLA STATUS COUNTS")
display(
    service_request_sla_analysis["sla_status"]
    .value_counts(dropna=False)
    .rename_axis("sla_status")
    .reset_index(name="request_count")
)

print("\nSECTION 8 SUMMARY")
print("Analysis date:", ANALYSIS_DATE.date())
print("Total requests analyzed:", len(service_request_sla_analysis))
print("SLA breaches:", health_metrics["sla_breached_requests"])
print("Near SLA breaches:", health_metrics["near_sla_breach_requests"])
print(
    "Unassessable SLA requests:",
    health_metrics["unassessable_sla_requests"]
)
print("Missing SLA status values:",
      service_request_sla_analysis["sla_status"].isna().sum())
print("Original cleaned_data modified: No")
print("Section 8 completed successfully.")

SECTION 8: SLA BREACH ANALYSIS
Analysis date: 2026-06-30
Near-breach threshold: 80% of SLA

SERVICE REQUEST HEALTH SUMMARY

                         Metric  Value
0                total_requests   4992
1   resolved_or_closed_requests   2360
2   pending_unresolved_requests   2632
3         sla_breached_requests   3432
4      near_sla_breach_requests    522
5  invalid_created_date_records      6
6     unassessable_sla_requests      8

CATEGORY-WISE SLA SUMMARY

  request_category  total_requests  pending_requests  sla_breaches  near_sla_breaches  avg_elapsed_hours
0          Account             866               467           594                106            1256.71
1             Card             825               438           620                  0            1265.18
2        Complaint             822               415           549                 81            1181.43
3  Digital Banking             841               466           545                205            1297.31
4              KYC             802               416           545                 74            1234.19
5             Loan             836               430           579                 56            1157.47

SLA DATA QUALITY REVIEW

                                               check  issue_count
0                       Invalid created-date records            6
1  Missing resolved date on resolved/closed requests            2
2                 Missing or non-positive SLA values            0
3                         Negative elapsed durations            2
4              Requests excluded from SLA assessment            8

SLA STATUS COUNTS

       sla_status  request_count
0        Breached           3432
1      Within SLA           1030
2     Near Breach            522
3  Not Assessable              8

SECTION 8 SUMMARY
Analysis date: 2026-06-30
Total requests analyzed: 4992
SLA breaches: 3432
Near SLA breaches: 522
Unassessable SLA requests: 8
Missing SLA status values: 0
Original cleaned_data modified: No
Section 8 completed successfully.

### Expected Output — Section 8: SLA Breach Analysis

**Datasets to use:**

- Cleaned `service_requests.csv`

**How to approach:**

- Use standardized `request_status` values.
- Calculate elapsed hours using `resolved_date` when available and `ANALYSIS_DATE` for unresolved requests.
- Compare elapsed hours with row-level `sla_hours`.
- Flag invalid created dates instead of silently dropping records.
- Create service request health metrics and category-wise SLA summary.

**Expected output format:**

Create a visible `service_request_health_summary` table with:

| Metric | Expected Type |
|---|---|
| total_requests | integer |
| resolved_or_closed_requests | integer |
| pending_unresolved_requests | integer |
| sla_breached_requests | integer |
| near_sla_breach_requests | integer |
| invalid_created_date_records | integer |

Also create `sla_category_summary` with `request_category`, `total_requests`, `pending_requests`, `sla_breaches`, and `avg_elapsed_hours`.

**Hint:** This section should not depend on complaints or tickets yet. Keep it focused on SLA and request status health.

In [ ]:
import pandas as pd
import numpy as np

if "cleaned_data" not in globals():
    raise RuntimeError("cleaned_data not found. Run Sections 5-7 first.")

if "service_request_sla_analysis" not in globals():
    raise RuntimeError("Run Section 8 before running Section 9.")

if "branches" not in cleaned_data:
    raise KeyError("Cleaned branch master is missing from cleaned_data.")

requests = service_request_sla_analysis.copy(deep=True)
branches = cleaned_data["branches"].copy(deep=True)

required_request_columns = [
    "request_id", "branch_id", "request_category", "request_status",
    "elapsed_hours", "is_pending_unresolved", "sla_breached",
    "near_sla_breach"
]

required_branch_columns = [
    "branch_id", "branch_name", "branch_city", "branch_zone"
]

missing_request_columns = [
    col for col in required_request_columns if col not in requests.columns
]
missing_branch_columns = [
    col for col in required_branch_columns if col not in branches.columns
]

if missing_request_columns:
    raise ValueError(
        f"Missing Section 8 fields: {missing_request_columns}"
    )

if missing_branch_columns:
    raise ValueError(
        f"Missing branch master fields: {missing_branch_columns}"
    )

if branches["branch_id"].duplicated().any():
    duplicate_branch_ids = branches.loc[
        branches["branch_id"].duplicated(keep=False), "branch_id"
    ].unique().tolist()
    raise ValueError(
        "Branch master contains duplicate branch IDs. "
        f"Resolve these before merging: {duplicate_branch_ids[:10]}"
    )

for col in [
    "is_pending_unresolved", "sla_breached", "near_sla_breach"
]:
    requests[col] = requests[col].fillna(False).astype(bool)

requests["request_category"] = (
    requests["request_category"].astype("string").fillna("Unknown")
)
requests["request_status"] = (
    requests["request_status"].astype("string").fillna("Unknown")
)

branch_metrics = (
    requests.groupby("branch_id", dropna=False)
    .agg(
        total_requests=("request_id", "size"),
        pending_requests=("is_pending_unresolved", "sum"),
        sla_breaches=("sla_breached", "sum"),
        near_sla_breaches=("near_sla_breach", "sum"),
        avg_elapsed_hours=("elapsed_hours", "mean"),
    )
    .reset_index()
)

branch_issue_summary = branches[
    ["branch_id", "branch_name", "branch_city", "branch_zone"]
].merge(
    branch_metrics,
    on="branch_id",
    how="left",
    validate="one_to_one",
    indicator=True
)

branch_issue_summary["branch_has_requests"] = (
    branch_issue_summary["_merge"] == "both"
)
branch_issue_summary = branch_issue_summary.drop(columns="_merge")

count_columns = [
    "total_requests", "pending_requests",
    "sla_breaches", "near_sla_breaches"
]

for col in count_columns:
    branch_issue_summary[col] = (
        branch_issue_summary[col].fillna(0).astype(int)
    )

has_requests = branch_issue_summary["total_requests"] > 0

branch_issue_summary["pending_rate_pct"] = np.where(
    has_requests,
    branch_issue_summary["pending_requests"]
    / branch_issue_summary["total_requests"] * 100,
    np.nan
)

branch_issue_summary["sla_breach_rate_pct"] = np.where(
    has_requests,
    branch_issue_summary["sla_breaches"]
    / branch_issue_summary["total_requests"] * 100,
    np.nan
)

branch_issue_summary["near_breach_rate_pct"] = np.where(
    has_requests,
    branch_issue_summary["near_sla_breaches"]
    / branch_issue_summary["total_requests"] * 100,
    np.nan
)

branch_issue_summary["branch_risk_score"] = (
    0.50 * branch_issue_summary["sla_breach_rate_pct"]
    + 0.30 * branch_issue_summary["pending_rate_pct"]
    + 0.20 * branch_issue_summary["near_breach_rate_pct"]
).round(2)

branch_issue_summary.loc[
    ~has_requests, "branch_risk_score"
] = np.nan

branch_issue_summary = branch_issue_summary[
    [
        "branch_id",
        "branch_name",
        "branch_city",
        "branch_zone",
        "total_requests",
        "pending_requests",
        "sla_breaches",
        "branch_risk_score",
        "near_sla_breaches",
        "avg_elapsed_hours",
        "pending_rate_pct",
        "sla_breach_rate_pct",
        "near_breach_rate_pct",
    ]
].sort_values(
    "branch_risk_score", ascending=False, na_position="last"
).reset_index(drop=True)

category_status_summary = (
    requests.groupby(
        ["request_category", "request_status"],
        dropna=False
    )
    .agg(
        total_requests=("request_id", "size"),
        pending_requests=("is_pending_unresolved", "sum"),
        sla_breaches=("sla_breached", "sum"),
        avg_elapsed_hours=("elapsed_hours", "mean"),
    )
    .reset_index()
)

category_status_summary["total_requests"] = (
    category_status_summary["total_requests"].astype(int)
)
category_status_summary["pending_requests"] = (
    category_status_summary["pending_requests"].astype(int)
)
category_status_summary["sla_breaches"] = (
    category_status_summary["sla_breaches"].astype(int)
)
category_status_summary["avg_elapsed_hours"] = (
    category_status_summary["avg_elapsed_hours"].round(2)
)

category_status_summary = category_status_summary.sort_values(
    ["sla_breaches", "pending_requests", "total_requests"],
    ascending=False
).reset_index(drop=True)

branch_id_lookup = branches["branch_id"].dropna().unique()

unmatched_branch_mask = (
    requests["branch_id"].isna()
    | ~requests["branch_id"].isin(branch_id_lookup)
)

unmatched_branch_requests = requests.loc[
    unmatched_branch_mask,
    ["request_id", "branch_id", "request_status", "request_category"]
].copy()

print("BRANCH ISSUE SUMMARY")
display(branch_issue_summary)

print("CATEGORY / STATUS SUMMARY")
display(category_status_summary)

print("UNMATCHED BRANCH REFERENCES")
print("Requests with missing/unmatched branch IDs:",
      len(unmatched_branch_requests))
display(unmatched_branch_requests.head(20))

print("Branches in master:", len(branches))
print("Branches with requests:", int(has_requests.sum()))
print("Branches without requests:", int((~has_requests).sum()))
print("Requests analyzed:", len(requests))
print("Unmatched branch references:", len(unmatched_branch_requests))
print("Original loaded_data modified: No")
print("SECTION 9 COMPLETED")

BRANCH ISSUE SUMMARY

,branch_id,branch_name,branch_city,branch_zone,total_requests,pending_requests,sla_breaches,branch_risk_score,near_sla_breaches,avg_elapsed_hours,pending_rate_pct,sla_breach_rate_pct,near_breach_rate_pct
0,BR0002,HDFC Kanpur Service Branch 0002,Kanpur,North,3,3,3,80.0,0,2744.0,100.0,100.0,0.0
1,BR0978,HDFC Nagpur Service Branch 0978,Nagpur,West,2,2,2,80.0,0,2652.0,100.0,100.0,0.0
2,BR0976,HDFC Noida Service Branch 0976,Noida,North,4,4,4,80.0,0,2298.0,100.0,100.0,0.0
3,BR0453,HDFC Varanasi Service Branch 0453,Varanasi,North,1,1,1,80.0,0,264.0,100.0,100.0,0.0
4,BR0462,HDFC Noida Service Branch 0462,Noida,North,3,3,3,80.0,0,2872.0,100.0,100.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,BR0115,HDFC Varanasi Service Branch 0115,Varanasi,North,0,0,0,NaN,0,NaN,NaN,NaN,NaN
996,BR0425,HDFC Gurugram Service Branch 0425,Gurugram,North,0,0,0,NaN,0,NaN,NaN,NaN,NaN
997,BR0716,HDFC Vadodara Service Branch 0716,Vadodara,West,0,0,0,NaN,0,NaN,NaN,NaN,NaN
998,BR0868,HDFC Nagpur Service Branch 0868,Nagpur,West,0,0,0,NaN,0,NaN,NaN,NaN,NaN
999,BR0982,HDFC Mysuru Service Branch 0982,Mysuru,South,0,0,0,NaN,0,NaN,NaN,NaN,NaN

CATEGORY / STATUS SUMMARY

   request_category    request_status  total_requests  pending_requests  sla_breaches  avg_elapsed_hours
0   Digital Banking       in_progress             232               232           232            2301.62
1           Account       in_progress             216               216           216            2352.56
2              Card       in_progress             215               215           214            2358.14
3               KYC       in_progress             198               198           198            2351.64
4         Complaint       in_progress             191               191           191            2128.08
5              Loan       in_progress             191               191           191            2282.89
6              Card          resolved             249                 0           115              33.29
7           Account              open             108               108           108            2203.78
8           Account  pending_customer              98                98            98            2175.67
9              Loan          resolved             258                 0            96              86.01
10  Digital Banking              open              95                95            95            2351.49
11        Complaint              open              92                92            91            2452.43
12             Loan  pending_customer              92                92            91            2163.43
13             Loan              open              91                91            91            1954.81
14        Complaint  pending_customer              86                86            86            2301.21
15              KYC  pending_customer              86                86            86            2310.98
16             Card              open              83                83            83            2380.63
17             Card  pending_customer              83                83            83            2361.25
18              KYC              open              81                81            81            2205.04
19              KYC          resolved             247                 0            79              64.13
20  Digital Banking  pending_customer              71                71            71            2440.56
21          Account          resolved             228                 0            71              44.09
22        Complaint          resolved             251                 0            70              62.73
23  Digital Banking         escalated              68                68            68            2211.53
24             Card            closed             138                 0            68              61.22
25        Complaint            closed             156                 0            65              69.69
26             Card         escalated              57                57            57            2197.05
27             Loan         escalated              56                56            56            2136.00
28          Account            closed             171                 0            56              44.91
29             Loan            closed             148                 0            54              86.59
30  Digital Banking          resolved             230                 0            52              23.79
31              KYC         escalated              51                51            51            2328.47
32              KYC            closed             139                 0            50              79.83
33        Complaint         escalated              46                46            46            2489.74
34          Account         escalated              45                45            45            2444.27
35  Digital Banking            closed             145                 0            27              22.50

UNMATCHED BRANCH REFERENCES
Requests with missing/unmatched branch IDs: 11

     request_id branch_id    request_status request_category
171  REQ0000180   BRX0180          resolved          Account
172  REQ0000181   BRX0181              open             Loan
173  REQ0000182   BRX0182       in_progress        Complaint
174  REQ0000183   BRX0183       in_progress  Digital Banking
175  REQ0000184   BRX0184          resolved          Account
176  REQ0000185   BRX0185       in_progress          Account
177  REQ0000186   BRX0186  pending_customer  Digital Banking
178  REQ0000187   BRX0187          resolved             Loan
179  REQ0000188   BRX0188            closed             Loan
180  REQ0000189   BRX0189       in_progress  Digital Banking
181  REQ0000190   BRX0190         escalated             Card

Branches in master: 1000
Branches with requests: 995
Branches without requests: 5
Requests analyzed: 4992
Unmatched branch references: 11
Original loaded_data modified: No
SECTION 9 COMPLETED

### Expected Output — Section 9: Branch-Wise SLA and Pending Request Analysis

**Datasets to use:**

- Cleaned `service_requests.csv`
- Cleaned `branches.csv`

**How to approach:**

- Merge service requests with branch master data using `branch_id`.
- Calculate total requests, pending requests, SLA breaches, near breaches, and average elapsed hours by branch.
- Create a branch risk score.
- Also create category/status-level summary for operations review.

**Expected output format:**

Create visible tables:

| Table | Required Columns |
|---|---|
| `branch_issue_summary` | `branch_id`, `branch_name`, `branch_city`, `branch_zone`, `total_requests`, `pending_requests`, `sla_breaches`, `branch_risk_score` |
| `category_status_summary` | `request_category`, `request_status`, `total_requests`, `pending_requests`, `sla_breaches`, `avg_elapsed_hours` |

**Hint:** Branch analysis must use `branches.csv`; do not rely only on `branch_id` counts from the main file.

In [ ]:
import pandas as pd
import numpy as np

service_requests_df = cleaned_data["service_requests"].copy(deep=True)
complaints_df = cleaned_data["complaints"].copy(deep=True)

request_required = {"request_id", "customer_id"}
complaint_required = {
    "complaint_id", "request_id", "customer_id",
    "complaint_date", "complaint_type",
    "complaint_status", "sentiment_tag"
}

missing_request = request_required - set(service_requests_df.columns)
missing_complaint = complaint_required - set(complaints_df.columns)

if missing_request:
    raise ValueError(f"Missing service-request columns: {sorted(missing_request)}")
if missing_complaint:
    raise ValueError(f"Missing complaint columns: {sorted(missing_complaint)}")

for df in (service_requests_df, complaints_df):
    df["request_id"] = df["request_id"].astype("string").str.strip()
    df["customer_id"] = df["customer_id"].astype("string").str.strip()

complaints_df["complaint_date"] = pd.to_datetime(
    complaints_df["complaint_date"], errors="coerce"
)

for col in ["complaint_status", "complaint_type", "sentiment_tag"]:
    complaints_df[col] = (
        complaints_df[col]
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"[\s-]+", "_", regex=True)
    )

request_keys = service_requests_df[
    ["request_id", "customer_id"]
].drop_duplicates("request_id")

complaints_checked = complaints_df.merge(
    request_keys,
    on="request_id",
    how="left",
    suffixes=("_complaint", "_request"),
    indicator="_request_match",
    validate="many_to_one"
)

orphan_complaints = complaints_checked.loc[
    complaints_checked["_request_match"] == "left_only"
].copy()

customer_mismatch_mask = (
    complaints_checked["_request_match"].eq("both")
    & complaints_checked["customer_id_complaint"].notna()
    & complaints_checked["customer_id_request"].notna()
    & complaints_checked["customer_id_complaint"].ne(
        complaints_checked["customer_id_request"]
    )
)

customer_mismatch_complaints = complaints_checked.loc[
    customer_mismatch_mask
].copy()

valid_complaints = complaints_checked.loc[
    complaints_checked["_request_match"].eq("both")
    & ~customer_mismatch_mask
].copy()

reopened_statuses = {"reopened", "re_opened"}
unresolved_statuses = {
    "open", "pending", "in_progress", "in_review",
    "awaiting_response", "under_review", "escalated"
}
negative_sentiments = {
    "angry", "very_angry", "negative", "very_negative",
    "frustrated", "dissatisfied"
}

valid_complaints["is_reopened"] = (
    valid_complaints["complaint_status"].isin(reopened_statuses)
)
valid_complaints["is_unresolved"] = (
    valid_complaints["complaint_status"].isin(unresolved_statuses)
)
valid_complaints["is_angry"] = (
    valid_complaints["sentiment_tag"].isin(negative_sentiments)
)

customer_complaint_counts = (
    valid_complaints.groupby("customer_id_complaint")["complaint_id"]
    .nunique()
    .to_dict()
)

valid_complaints["customer_complaint_count"] = (
    valid_complaints["customer_id_complaint"]
    .map(customer_complaint_counts)
    .fillna(0)
    .astype(int)
)

valid_complaints["repeated_complaint_flag"] = (
    valid_complaints["customer_complaint_count"] > 1
).astype(bool)

def complaint_severity(row):
    if row["is_angry"] or row["is_reopened"]:
        return "Severe"
    if row["is_unresolved"] or row["repeated_complaint_flag"]:
        return "Moderate"
    return "Low"

valid_complaints["complaint_severity"] = valid_complaints.apply(
    complaint_severity, axis=1
)

severity_rank = {"None": 0, "Low": 1, "Moderate": 2, "Severe": 3}
valid_complaints["_severity_rank"] = (
    valid_complaints["complaint_severity"].map(severity_rank)
)

status_rank = {
    "reopened": 7,
    "re_opened": 7,
    "escalated": 6,
    "open": 5,
    "pending": 5,
    "in_progress": 4,
    "in_review": 4,
    "resolved": 2,
    "closed": 1
}
valid_complaints["_status_rank"] = (
    valid_complaints["complaint_status"].map(status_rank).fillna(0)
)

sentiment_rank = {
    "very_angry": 7,
    "angry": 6,
    "very_negative": 5,
    "negative": 4,
    "frustrated": 3,
    "dissatisfied": 3,
    "neutral": 2,
    "positive": 1
}
valid_complaints["_sentiment_rank"] = (
    valid_complaints["sentiment_tag"].map(sentiment_rank).fillna(0)
)


valid_complaints = valid_complaints.sort_values(
    ["_severity_rank", "_status_rank", "_sentiment_rank", "complaint_date"],
    ascending=[False, False, False, False],
    na_position="last"
)

def unique_values(series):
    values = []
    for value in series:
        if pd.notna(value):
            value = str(value).strip()
            if value and value not in values:
                values.append(value)
    return ", ".join(values) if values else "Unknown"

complaint_summary = (
    valid_complaints.groupby("request_id", as_index=False)
    .agg(
        complaint_count=("complaint_id", "nunique"),
        customer_complaint_count=("customer_complaint_count", "max"),
        complaint_status=("complaint_status", "first"),
        complaint_type=("complaint_type", unique_values),
        sentiment_tag=("sentiment_tag", "first"),
        complaint_severity=(
            "complaint_severity",
            lambda x: max(x, key=lambda v: severity_rank.get(v, 0))
        ),
        repeated_complaint_flag=("repeated_complaint_flag", "max"),
        reopened_complaint_flag=("is_reopened", "max"),
        angry_complaint_flag=("is_angry", "max"),
        unresolved_complaint_flag=("is_unresolved", "max")
    )
)

complaint_join = service_requests_df.merge(
    complaint_summary,
    on="request_id",
    how="left",
    validate="one_to_one"
)

complaint_join["complaint_count"] = (
    complaint_join["complaint_count"].fillna(0).astype(int)
)
complaint_join["customer_complaint_count"] = (
    complaint_join["customer_complaint_count"].fillna(0).astype(int)
)

for col in [
    "repeated_complaint_flag",
    "reopened_complaint_flag",
    "angry_complaint_flag",
    "unresolved_complaint_flag"
]:
    complaint_join[col] = (
        complaint_join[col].astype("boolean").fillna(False).astype(bool)
    )

complaint_join["complaint_status"] = (
    complaint_join["complaint_status"].fillna("No complaint")
)
complaint_join["complaint_type"] = (
    complaint_join["complaint_type"].fillna("None")
)
complaint_join["sentiment_tag"] = (
    complaint_join["sentiment_tag"].fillna("None")
)
complaint_join["complaint_severity"] = (
    complaint_join["complaint_severity"].fillna("None")
)

assert len(complaint_join) == len(service_requests_df), (
    "Row count changed during complaint linking."
)
assert complaint_join["request_id"].is_unique, (
    "Duplicate request IDs found after complaint linking."
)

complaint_linking_summary = pd.DataFrame({
    "Metric": [
        "Service requests before linking",
        "Service requests after linking",
        "Source complaints",
        "Valid linked complaints",
        "Orphan complaints",
        "Customer-ID mismatch complaints",
        "Requests with complaints",
        "Requests without complaints",
        "Requests with reopened complaints",
        "Requests with angry/negative complaints",
        "Requests with unresolved complaints",
        "Customers with repeated complaints",
        "Duplicate request IDs after linking"
    ],
    "Value": [
        len(service_requests_df),
        len(complaint_join),
        len(complaints_df),
        len(valid_complaints),
        len(orphan_complaints),
        len(customer_mismatch_complaints),
        int((complaint_join["complaint_count"] > 0).sum()),
        int((complaint_join["complaint_count"] == 0).sum()),
        int(complaint_join["reopened_complaint_flag"].sum()),
        int(complaint_join["angry_complaint_flag"].sum()),
        int(complaint_join["unresolved_complaint_flag"].sum()),
        int(
            valid_complaints.loc[
                valid_complaints["repeated_complaint_flag"],
                "customer_id_complaint"
            ].nunique()
        ),
        int(complaint_join["request_id"].duplicated().sum())
    ]
})

print("Section 10: Complaint Linking Engine completed.")
display(complaint_linking_summary)
display(complaint_join.head())
display(orphan_complaints.head())
display(customer_mismatch_complaints.head())

Section 10: Complaint Linking Engine completed.

                                     Metric  Value
0           Service requests before linking   4992
1            Service requests after linking   4992
2                         Source complaints   1500
3                   Valid linked complaints   1457
4                         Orphan complaints     29
5           Customer-ID mismatch complaints     14
6                  Requests with complaints   1266
7               Requests without complaints   3726
8         Requests with reopened complaints    259
9   Requests with angry/negative complaints    996
10      Requests with unresolved complaints    659
11       Customers with repeated complaints    398
12      Duplicate request IDs after linking      0

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,complaint_count,customer_complaint_count,complaint_status,complaint_type,sentiment_tag,complaint_severity,repeated_complaint_flag,reopened_complaint_flag,angry_complaint_flag,unresolved_complaint_flag
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,0,0,No complaint,None,None,None,False,False,False,False
1,REQ0000010,CUST000649,BR0980,2026-05-17,22:31:00,Card,Failed ATM Withdrawal,WhatsApp,pending_customer,36,Cards Operations,24383.2,2026-05-18,NaT,False,False,False,0,0,No complaint,None,None,None,False,False,False,False
2,REQ0000011,CUST000817,BR0045,2026-06-19,04:47:00,Digital Banking,NetBanking Login,Email,closed,24,Digital Banking Support,193459.78,2026-06-19,2026-06-19,False,False,False,0,0,No complaint,None,None,None,False,False,False,False
3,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,0,0,No complaint,None,None,None,False,False,False,False
4,REQ0000013,CUST001137,BR0081,2026-06-13,07:18:00,Account,Balance Mismatch,NetBanking,closed,48,Account Servicing,<NA>,2026-06-16,2026-06-16,False,False,False,0,0,No complaint,None,None,None,False,False,False,False

,complaint_id,request_id,customer_id_complaint,complaint_date,complaint_type,complaint_description,complaint_status,sentiment_tag,complaint_date_invalid_flag,customer_id_request,_request_match
28,CMP000029,REQX0000029,CUST001063,2026-03-06,loan_servicing,Customer requests supervisor callback and writ...,resolved,negative,False,<NA>,left_only
43,CMP000044,REQX0000044,CUST000481,2026-03-01,loan_servicing,Customer claims commitment date was missed.,resolved,negative,False,<NA>,left_only
55,CMP000056,REQX0000056,CUST000956,2026-03-05,kyc_delay,Customer is upset because financial work is bl...,reopened,negative,False,<NA>,left_only
201,CMP000202,REQX0000202,CUST000516,2026-03-09,loan_servicing,Customer received conflicting updates from bra...,resolved,positive,False,<NA>,left_only
202,CMP000203,REQX0000203,CUST000576,2026-03-19,digital_login_issue,Customer is upset because financial work is bl...,escalated,very_angry,False,<NA>,left_only

,complaint_id,request_id,customer_id_complaint,complaint_date,complaint_type,complaint_description,complaint_status,sentiment_tag,complaint_date_invalid_flag,customer_id_request,_request_match
33,CMP000034,REQ0004273,CUSTORPH000034,2026-02-20,poor_branch_experience,Customer received conflicting updates from bra...,escalated,angry,False,CUST000059,both
130,CMP000131,REQ0001916,CUSTORPH000131,2026-06-11,digital_login_issue,Customer is upset because financial work is bl...,reopened,positive,False,CUST000997,both
136,CMP000137,REQ0004712,CUSTORPH000137,2026-01-14,digital_login_issue,Customer claims commitment date was missed.,reopened,angry,False,CUST000014,both
315,CMP000316,REQ0002341,CUSTORPH000316,2026-04-12,loan_servicing,Customer claims commitment date was missed.,reopened,neutral,False,CUST000800,both
322,CMP000323,REQ0002330,CUSTORPH000323,2026-02-25,poor_branch_experience,Customer received conflicting updates from bra...,in_review,very_angry,False,CUST000138,both

### Expected Output — Section 10: Complaint Linking Engine

**Datasets to use:**

- Cleaned `service_requests.csv`
- Cleaned `customer_complaints.json`
- Cleaned `customers.csv` if needed for customer-level repeat history

**How to approach:**

- Link complaints using `request_id` and verify `customer_id` consistency.
- Count complaints per request.
- Count complaints per customer.
- Identify reopened, angry, unresolved, repeated, and orphan complaints.
- Aggregate complaint details before merging into final request-level data.

**Expected output format:**

Create request-level columns such as:

| Column | Meaning |
|---|---|
| `complaint_count` | Number of complaints linked to the request |
| `customer_complaint_count` | Complaints raised by the customer across requests |
| `complaint_status` | Latest or highest-priority complaint status |
| `complaint_type` | Main complaint category |
| `sentiment_tag` | Latest/highest-severity sentiment |
| `complaint_severity` | `Severe`, `Moderate`, `Low`, `None` |
| `repeated_complaint_flag` | Yes/No |

**Hint:** If multiple complaints exist for one request, group first, then merge. Direct merging can accidentally increase the number of rows.

In [ ]:
import pandas as pd
import numpy as np

service_requests_df = cleaned_data["service_requests"].copy(deep=True)
tickets_df = cleaned_data["tickets"].copy(deep=True)

if "ANALYSIS_DATE" not in globals():
    raise NameError("ANALYSIS_DATE is missing. Run Section 8 first.")


required_request_cols = {"request_id", "customer_id", "sla_hours"}
required_ticket_cols = {
    "ticket_id", "request_id", "customer_id",
    "ticket_created_date", "ticket_status", "assigned_team",
    "resolution_time_hours", "escalation_flag"
}

missing_requests = required_request_cols - set(service_requests_df.columns)
missing_tickets = required_ticket_cols - set(tickets_df.columns)

if missing_requests:
    raise ValueError(f"Missing service request columns: {sorted(missing_requests)}")
if missing_tickets:
    raise ValueError(f"Missing ticket columns: {sorted(missing_tickets)}")

for df in [service_requests_df, tickets_df]:
    df["request_id"] = df["request_id"].astype("string").str.strip()
    df["customer_id"] = df["customer_id"].astype("string").str.strip()

tickets_df["ticket_status"] = (
    tickets_df["ticket_status"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"[\s-]+", "_", regex=True)
)

tickets_df["ticket_created_date"] = pd.to_datetime(
    tickets_df["ticket_created_date"], errors="coerce"
)
tickets_df["resolution_time_hours"] = pd.to_numeric(
    tickets_df["resolution_time_hours"], errors="coerce"
)
service_requests_df["sla_hours"] = pd.to_numeric(
    service_requests_df["sla_hours"], errors="coerce"
)

analysis_timestamp = pd.Timestamp(ANALYSIS_DATE)
if analysis_timestamp.tz is not None:
    analysis_timestamp = analysis_timestamp.tz_localize(None)
analysis_timestamp = analysis_timestamp.normalize()

request_lookup = service_requests_df[
    ["request_id", "customer_id", "sla_hours"]
].drop_duplicates("request_id")

tickets_checked = tickets_df.merge(
    request_lookup,
    on="request_id",
    how="left",
    suffixes=("_ticket", "_request"),
    indicator="_request_match",
    validate="many_to_one"
)

orphan_tickets = tickets_checked.loc[
    tickets_checked["_request_match"] == "left_only"
].copy()

mismatch_mask = (
    tickets_checked["_request_match"].eq("both")
    & tickets_checked["customer_id_ticket"].notna()
    & tickets_checked["customer_id_request"].notna()
    & tickets_checked["customer_id_ticket"].ne(
        tickets_checked["customer_id_request"]
    )
)

ticket_customer_mismatches = tickets_checked.loc[mismatch_mask].copy()

valid_tickets = tickets_checked.loc[
    tickets_checked["_request_match"].eq("both") & ~mismatch_mask
].copy()


def normalize_escalation(value):
    if pd.isna(value):
        return False
    if isinstance(value, (bool, np.bool_)):
        return bool(value)
    return str(value).strip().lower() in {
        "true", "1", "yes", "y", "t", "escalated"
    }

valid_tickets["escalation_flag"] = (
    valid_tickets["escalation_flag"]
    .map(normalize_escalation)
    .astype(bool)
)

active_statuses = {
    "open", "pending", "pending_customer", "in_progress",
    "in_review", "escalated", "reopened"
}
closed_statuses = {"resolved", "closed"}

valid_tickets["ticket_age_hours"] = np.nan

active_mask = valid_tickets["ticket_status"].isin(active_statuses)
closed_mask = valid_tickets["ticket_status"].isin(closed_statuses)

active_age = (
    analysis_timestamp - valid_tickets["ticket_created_date"]
).dt.total_seconds() / 3600

valid_tickets.loc[active_mask, "ticket_age_hours"] = active_age.loc[active_mask]

future_dates = (
    valid_tickets["ticket_created_date"].notna()
    & (valid_tickets["ticket_created_date"] > analysis_timestamp)
)
valid_tickets.loc[future_dates, "ticket_age_hours"] = np.nan

valid_tickets.loc[closed_mask, "ticket_age_hours"] = (
    valid_tickets.loc[closed_mask, "resolution_time_hours"]
)

valid_tickets.loc[
    valid_tickets["ticket_age_hours"] < 0, "ticket_age_hours"
] = np.nan
valid_tickets.loc[
    valid_tickets["resolution_time_hours"] < 0,
    "resolution_time_hours"
] = np.nan

has_sla = (
    valid_tickets["sla_hours"].notna()
    & (valid_tickets["sla_hours"] > 0)
)

valid_tickets["ticket_sla_breached_flag"] = (
    has_sla
    & valid_tickets["ticket_age_hours"].notna()
    & (valid_tickets["ticket_age_hours"] > valid_tickets["sla_hours"])
)

valid_tickets["ticket_delay_warning_flag"] = (
    has_sla
    & valid_tickets["ticket_age_hours"].notna()
    & (valid_tickets["ticket_age_hours"] >= 0.80 * valid_tickets["sla_hours"])
    & ~valid_tickets["ticket_sla_breached_flag"]
)

valid_tickets["slow_resolution_flag"] = (
    closed_mask.loc[valid_tickets.index]
    & valid_tickets["resolution_time_hours"].notna()
    & has_sla
    & (
        valid_tickets["resolution_time_hours"]
        > 0.80 * valid_tickets["sla_hours"]
    )
)

def assign_ticket_severity(row):
    if row["ticket_sla_breached_flag"] or row["escalation_flag"]:
        return "Severe"
    if (
        row["ticket_delay_warning_flag"]
        or row["slow_resolution_flag"]
        or row["ticket_status"] in active_statuses
    ):
        return "Moderate"
    if row["ticket_status"] in closed_statuses:
        return "Low"
    return "None"

valid_tickets["ticket_severity"] = valid_tickets.apply(
    assign_ticket_severity, axis=1
)

def assign_ticket_tags(row):
    tags = []
    if row["ticket_sla_breached_flag"]:
        tags.append("Ticket SLA Breach")
    if row["ticket_delay_warning_flag"]:
        tags.append("Ticket Delay Warning")
    if row["escalation_flag"]:
        tags.append("Escalated Case")
    if row["slow_resolution_flag"]:
        tags.append("Slow Resolution")
    if row["ticket_status"] in active_statuses:
        tags.append("Active Ticket")
    if (
        row["ticket_status"] in closed_statuses
        and pd.isna(row["resolution_time_hours"])
    ):
        tags.append("Missing Resolution Time")
    return "; ".join(tags) if tags else "No Ticket Issue"

valid_tickets["ticket_issue_tag"] = valid_tickets.apply(
    assign_ticket_tags, axis=1
)
status_priority = {
    "reopened": 7,
    "escalated": 6,
    "open": 5,
    "pending": 5,
    "pending_customer": 5,
    "in_progress": 4,
    "in_review": 4,
    "resolved": 2,
    "closed": 1
}

valid_tickets["_status_priority"] = (
    valid_tickets["ticket_status"].map(status_priority).fillna(0)
)

valid_tickets = valid_tickets.sort_values(
    ["_status_priority", "ticket_created_date"],
    ascending=[False, False],
    na_position="last"
)

severity_priority = {
    "None": 0, "Low": 1, "Moderate": 2, "Severe": 3
}

def highest_severity(values):
    return max(
        values,
        key=lambda value: severity_priority.get(value, 0)
    )

def combine_unique(values):
    result = []
    for value in values:
        if pd.notna(value):
            value = str(value).strip()
            if value and value not in result:
                result.append(value)
    return ", ".join(result) if result else "Unassigned"

def combine_tags(values):
    result = []
    for value in values:
        if pd.notna(value):
            for tag in str(value).split("; "):
                if tag and tag != "No Ticket Issue" and tag not in result:
                    result.append(tag)
    return "; ".join(result) if result else "No Ticket Issue"

ticket_summary = (
    valid_tickets.groupby("request_id", as_index=False)
    .agg(
        ticket_count=("ticket_id", "nunique"),
        ticket_status=("ticket_status", "first"),
        assigned_team_ticket=("assigned_team", combine_unique),
        escalation_flag=("escalation_flag", "max"),
        max_ticket_age_hours=("ticket_age_hours", "max"),
        ticket_sla_breached_flag=("ticket_sla_breached_flag", "max"),
        ticket_delay_warning_flag=("ticket_delay_warning_flag", "max"),
        slow_resolution_flag=("slow_resolution_flag", "max"),
        ticket_severity=("ticket_severity", highest_severity),
        ticket_issue_tag=("ticket_issue_tag", combine_tags)
    )
)

ticket_join = service_requests_df.merge(
    ticket_summary,
    on="request_id",
    how="left",
    validate="one_to_one"
)

ticket_join["ticket_count"] = (
    ticket_join["ticket_count"].fillna(0).astype(int)
)

for col in [
    "escalation_flag",
    "ticket_sla_breached_flag",
    "ticket_delay_warning_flag",
    "slow_resolution_flag"
]:
    ticket_join[col] = (
        ticket_join[col].astype("boolean").fillna(False).astype(bool)
    )

ticket_join["ticket_status"] = ticket_join["ticket_status"].fillna("No Ticket")
ticket_join["assigned_team_ticket"] = (
    ticket_join["assigned_team_ticket"].fillna("Unassigned")
)
ticket_join["ticket_severity"] = (
    ticket_join["ticket_severity"].fillna("None")
)
ticket_join["ticket_issue_tag"] = (
    ticket_join["ticket_issue_tag"].fillna("No Ticket Issue")
)

assert len(ticket_join) == len(service_requests_df), (
    "ERROR: Service request row count changed."
)
assert ticket_join["request_id"].is_unique, (
    "ERROR: Duplicate request IDs found after mapping."
)

ticket_mapping_summary = pd.DataFrame({
    "Metric": [
        "Service requests before mapping",
        "Service requests after mapping",
        "Source tickets",
        "Valid linked tickets",
        "Orphan tickets",
        "Customer-ID mismatch tickets",
        "Requests with tickets",
        "Requests without tickets",
        "Requests with SLA-breached tickets",
        "Requests with escalated tickets",
        "Requests with Severe ticket severity",
        "Duplicate request IDs after mapping"
    ],
    "Value": [
        len(service_requests_df),
        len(ticket_join),
        len(cleaned_data["tickets"]),
        len(valid_tickets),
        len(orphan_tickets),
        len(ticket_customer_mismatches),
        int((ticket_join["ticket_count"] > 0).sum()),
        int((ticket_join["ticket_count"] == 0).sum()),
        int(ticket_join["ticket_sla_breached_flag"].sum()),
        int(ticket_join["escalation_flag"].sum()),
        int((ticket_join["ticket_severity"] == "Severe").sum()),
        int(ticket_join["request_id"].duplicated().sum())
    ]
})

print("Section 11: Support Ticket Mapping completed.")
display(ticket_mapping_summary)
display(ticket_join.head())
display(orphan_tickets.head())
display(ticket_customer_mismatches.head())

Section 11: Support Ticket Mapping completed.

/tmp/ipykernel_1487/3760040751.py:124: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<FloatingArray>
[ 56.0,  <NA>, 156.0,  60.0,  <NA>,   4.0, 139.0,  <NA>,  59.0,  <NA>,
 ...
 107.0,  <NA>,  28.0,  38.0,  <NA>,  43.0, 111.0, 130.0, 121.0, 114.0]
Length: 474, dtype: Float64' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  valid_tickets.loc[closed_mask, "ticket_age_hours"] = (

                                  Metric  Value
0        Service requests before mapping   4992
1         Service requests after mapping   4992
2                         Source tickets   1500
3                   Valid linked tickets   1447
4                         Orphan tickets     31
5           Customer-ID mismatch tickets     22
6                  Requests with tickets   1255
7               Requests without tickets   3737
8     Requests with SLA-breached tickets   1076
9        Requests with escalated tickets    559
10  Requests with Severe ticket severity   1155
11   Duplicate request IDs after mapping      0

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,ticket_count,ticket_status,assigned_team_ticket,escalation_flag,max_ticket_age_hours,ticket_sla_breached_flag,ticket_delay_warning_flag,slow_resolution_flag,ticket_severity,ticket_issue_tag
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,0,No Ticket,Unassigned,False,<NA>,False,False,False,None,No Ticket Issue
1,REQ0000010,CUST000649,BR0980,2026-05-17,22:31:00,Card,Failed ATM Withdrawal,WhatsApp,pending_customer,36,Cards Operations,24383.2,2026-05-18,NaT,False,False,False,0,No Ticket,Unassigned,False,<NA>,False,False,False,None,No Ticket Issue
2,REQ0000011,CUST000817,BR0045,2026-06-19,04:47:00,Digital Banking,NetBanking Login,Email,closed,24,Digital Banking Support,193459.78,2026-06-19,2026-06-19,False,False,False,0,No Ticket,Unassigned,False,<NA>,False,False,False,None,No Ticket Issue
3,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,1,open,Customer Care,False,1704.0,True,False,False,Severe,Ticket SLA Breach; Active Ticket
4,REQ0000013,CUST001137,BR0081,2026-06-13,07:18:00,Account,Balance Mismatch,NetBanking,closed,48,Account Servicing,<NA>,2026-06-16,2026-06-16,False,False,False,0,No Ticket,Unassigned,False,<NA>,False,False,False,None,No Ticket Issue

,ticket_id,request_id,customer_id_ticket,ticket_created_date,ticket_status,assigned_team,resolution_time_hours,escalation_flag,ticket_created_date_invalid_flag,customer_id_request,sla_hours,_request_match
18,TKT000019,REQTKT0000019,CUST000936,2026-02-03,closed,Branch Ops,132.0,No,False,<NA>,<NA>,left_only
112,TKT000113,REQTKT0000113,CUST001066,2026-02-03,pending,Branch Ops,<NA>,yes,False,<NA>,<NA>,left_only
134,TKT000135,REQTKT0000135,CUST001145,2026-02-05,open,Customer Care,212.0,No,False,<NA>,<NA>,left_only
156,TKT000157,REQTKT0000157,CUST000730,2026-02-03,pending,Digital Banking,109.0,Yes,False,<NA>,<NA>,left_only
189,TKT000190,REQTKT0000190,CUST000430,2026-02-01,escalated,Customer Care,158.0,No,False,<NA>,<NA>,left_only

,ticket_id,request_id,customer_id_ticket,ticket_created_date,ticket_status,assigned_team,resolution_time_hours,escalation_flag,ticket_created_date_invalid_flag,customer_id_request,sla_hours,_request_match
5,TKT000006,REQ0004890,CUSTT000006,2026-06-20,pending,KYC Ops,<NA>,No,False,CUST000190,24,both
64,TKT000065,REQ0001564,CUSTT000065,2026-02-25,closed,Customer Care,185.0,No,False,CUST001168,96,both
127,TKT000128,REQ0001935,CUSTT000128,2026-04-21,resolved,Cards Ops,80.0,No,False,CUST000148,72,both
246,TKT000247,REQ0000584,CUSTT000247,2026-02-10,open,Branch Ops,<NA>,No,False,CUST001109,96,both
256,TKT000257,REQ0000241,CUSTT000257,2026-04-24,reopened,Cards Ops,107.0,Yes,False,CUST000462,36,both

### Expected Output — Section 11: Support Ticket Mapping

**Datasets to use:**

- Cleaned `service_requests.csv`
- Cleaned `support_tickets.csv`
- Complaint summary from Section 10 if needed

**How to approach:**

- Link tickets using `request_id`.
- Calculate ticket age using `ANALYSIS_DATE` for open/pending/escalated tickets.
- Use `resolution_time_hours` for resolved/closed tickets.
- Group multiple tickets per request before merging.
- Create ticket severity based on PRD SLA rules.

**Expected output format:**

Create columns such as:

| Column | Meaning |
|---|---|
| `ticket_count` | Number of tickets linked to the request |
| `ticket_status` | Latest/highest-priority ticket status |
| `assigned_team_ticket` | Team handling the ticket |
| `escalation_flag` | Yes/No |
| `max_ticket_age_hours` | Age for active tickets |
| `ticket_severity` | `Severe`, `Moderate`, `Low`, `None` |
| `ticket_issue_tag` | `Ticket SLA Breach`, `Ticket Delay Warning`, `Escalated Case`, `Slow Resolution`, etc. |

**Hint:** Ticket SLA logic should not depend only on `ticket_status`; escalation and resolution time also matter.

In [ ]:
import pandas as pd
import numpy as np

service_requests_df = cleaned_data["service_requests"].copy(deep=True)

required_columns = {
    "request_id",
    "customer_id",
    "branch_id",
    "request_category",
    "request_subcategory",
    "request_created_date",
    "request_status"
}

missing_columns = required_columns - set(service_requests_df.columns)

if missing_columns:
    raise ValueError(
        f"Missing required columns: {sorted(missing_columns)}"
    )

comparison_columns = [
    "customer_id",
    "branch_id",
    "request_category",
    "request_subcategory",
    "request_status"
]

for col in comparison_columns:
    service_requests_df[col] = (
        service_requests_df[col]
        .astype("string")
        .str.strip()
        .str.lower()
        .replace("", pd.NA)
    )

service_requests_df["request_id"] = (
    service_requests_df["request_id"]
    .astype("string")
    .str.strip()
)

service_requests_df["request_created_date"] = pd.to_datetime(
    service_requests_df["request_created_date"],
    errors="coerce"
)

service_requests_df["request_date"] = (
    service_requests_df["request_created_date"].dt.date
)

service_requests_df["duplicate_id_flag"] = (
    service_requests_df["request_id"].duplicated(keep=False)
)

group_columns = [
    "customer_id",
    "branch_id",
    "request_category",
    "request_subcategory",
    "request_date"
]

complete_group_mask = service_requests_df[group_columns].notna().all(axis=1)

service_requests_df["duplicate_group_key"] = pd.NA

service_requests_df.loc[complete_group_mask, "duplicate_group_key"] = (
    service_requests_df.loc[complete_group_mask, group_columns]
    .astype("string")
    .agg("|".join, axis=1)
)


service_requests_df["same_day_repeat_flag"] = False

service_requests_df.loc[complete_group_mask, "same_day_repeat_flag"] = (
    service_requests_df.loc[complete_group_mask]
    .duplicated(subset=group_columns, keep=False)
)


unresolved_statuses = {
    "open",
    "pending",
    "in_progress",
    "in_review",
    "pending_customer",
    "escalated",
    "reopened"
}

service_requests_df["unresolved_flag"] = (
    service_requests_df["request_status"]
    .isin(unresolved_statuses)
)


repeat_pattern_columns = [
    "customer_id",
    "branch_id",
    "request_category",
    "request_subcategory"
]

complete_pattern_mask = (
    service_requests_df[repeat_pattern_columns].notna().all(axis=1)
)

service_requests_df["recurring_issue_flag"] = False

service_requests_df.loc[complete_pattern_mask, "recurring_issue_flag"] = (
    service_requests_df.loc[complete_pattern_mask]
    .duplicated(subset=repeat_pattern_columns, keep=False)
)

service_requests_df["unresolved_repeat_count"] = 0

if complete_pattern_mask.any():
    unresolved_repeat_counts = (
        service_requests_df.loc[
            complete_pattern_mask & service_requests_df["unresolved_flag"]
        ]
        .groupby(repeat_pattern_columns)["request_id"]
        .transform("size")
    )

    service_requests_df.loc[
        complete_pattern_mask & service_requests_df["unresolved_flag"],
        "unresolved_repeat_count"
    ] = unresolved_repeat_counts.to_numpy()

# 9. Flag suspicious cases without deleting any records
service_requests_df["duplicate_suspected"] = (
    service_requests_df["duplicate_id_flag"]
    | service_requests_df["same_day_repeat_flag"]
    | (
        service_requests_df["recurring_issue_flag"]
        & service_requests_df["unresolved_flag"]
    )
)

def explain_duplicate(row):
    reasons = []

    if row["duplicate_id_flag"]:
        reasons.append("Duplicate request ID")

    if row["same_day_repeat_flag"]:
        reasons.append("Same customer, branch, issue and date")

    if row["recurring_issue_flag"] and row["unresolved_flag"]:
        reasons.append("Recurring issue with unresolved request")

    return "; ".join(reasons) if reasons else "No duplicate pattern detected"

service_requests_df["duplicate_reason"] = (
    service_requests_df.apply(explain_duplicate, axis=1)
)

suspicious_requests = service_requests_df.loc[
    service_requests_df["duplicate_suspected"]
].copy()

duplicate_id_records = service_requests_df.loc[
    service_requests_df["duplicate_id_flag"]
].copy()

duplicate_detection_summary = pd.DataFrame({
    "Metric": [
        "Total service request rows",
        "Unique request IDs",
        "Rows with duplicate request IDs",
        "Same-day repeated issue rows",
        "Recurring issue rows",
        "Unresolved requests",
        "Suspicious requests flagged",
        "Rows removed automatically"
    ],
    "Value": [
        len(service_requests_df),
        service_requests_df["request_id"].nunique(dropna=True),
        int(service_requests_df["duplicate_id_flag"].sum()),
        int(service_requests_df["same_day_repeat_flag"].sum()),
        int(service_requests_df["recurring_issue_flag"].sum()),
        int(service_requests_df["unresolved_flag"].sum()),
        int(service_requests_df["duplicate_suspected"].sum()),
        0
    ]
})

assert len(service_requests_df) == len(cleaned_data["service_requests"]), (
    "Row count changed during duplicate detection."
)

print("Section 12: Repeated/Duplicate Request Detection completed.")
display(duplicate_detection_summary)

print("Suspicious request preview:")
display(
    suspicious_requests[
        [
            "request_id",
            "customer_id",
            "branch_id",
            "request_category",
            "request_subcategory",
            "request_created_date",
            "request_status",
            "duplicate_suspected",
            "duplicate_group_key",
            "duplicate_reason"
        ]
    ].head(10)
)

Section 12: Repeated/Duplicate Request Detection completed.

                            Metric  Value
0       Total service request rows   4992
1               Unique request IDs   4992
2  Rows with duplicate request IDs      0
3     Same-day repeated issue rows      0
4             Recurring issue rows      0
5              Unresolved requests   2632
6      Suspicious requests flagged      0
7       Rows removed automatically      0

Suspicious request preview:

Empty DataFrame
Columns: [request_id, customer_id, branch_id, request_category, request_subcategory, request_created_date, request_status, duplicate_suspected, duplicate_group_key, duplicate_reason]
Index: []

### Expected Output — Section 12: Repeated or Duplicate Request Detection

**Datasets to use:**

- Cleaned `service_requests.csv`

**How to approach:**

- Compare requests for the same `customer_id`, `branch_id`, `request_category`, `request_subcategory`, and request date.
- Flag duplicate extract rows and repeated service request patterns.
- Flag suspicious records; do not delete them.
- The PRD expects repeated/duplicate suspicion, not automatic removal.

**Expected output format:**

Create columns such as:

| Column | Meaning |
|---|---|
| `duplicate_suspected` | Yes/No |
| `duplicate_group_key` | Optional grouping key used for detection |
| `duplicate_reason` | Short explanation of why duplicate/repeated request is suspected |

Show:

- Count of duplicate/repeated cases.
- A preview of 5–10 suspicious records.

**Hint:** Start simple with groupby on customer, branch, category, subcategory, and date. Then improve by considering unresolved status and duplicate request IDs.

In [ ]:
import pandas as pd
import numpy as np

final_feature_df = cleaned_data["service_requests"].copy(deep=True)

if "request_id" not in final_feature_df.columns:
    raise ValueError("service_requests is missing request_id.")

final_feature_df["request_id"] = (
    final_feature_df["request_id"].astype("string").str.strip()
)

if final_feature_df["request_id"].duplicated().any():
    raise ValueError(
        "Service-request master contains duplicate request_id values. "
        "Resolve these before building the final feature table."
    )

initial_request_count = len(final_feature_df)


def merge_unique_features(master, source, key, label, include=None):
    if source is None or not isinstance(source, pd.DataFrame):
        print(f"INFO: {label} unavailable; skipping.")
        return master

    if key not in master.columns or key not in source.columns:
        print(f"INFO: {label} has no usable {key}; skipping.")
        return master

    source = source.copy()

    if source[key].duplicated().any():
        raise ValueError(
            f"{label} is not unique on {key}. "
            "Aggregate it to one row per key before merging."
        )

    if include is None:
        candidates = [c for c in source.columns if c != key]
    else:
        candidates = [c for c in include if c in source.columns and c != key]


    candidates = [
        c for c in candidates
        if c not in master.columns
    ]

    if not candidates:
        print(f"INFO: No new columns to add from {label}.")
        return master

    source = source[[key] + candidates]

    master = master.merge(
        source,
        on=key,
        how="left",
        validate="one_to_one" if key == "request_id" else "many_to_one"
    )

    print(f"Added {len(candidates)} feature columns from {label}.")
    return master

customers_master = cleaned_data["customers"].copy(deep=True)

if "customer_id" in customers_master.columns:
    customers_master["customer_id"] = (
        customers_master["customer_id"].astype("string").str.strip()
    )

    customer_features = [
        "customer_name",
        "customer_segment",
        "account_type",
        "relationship_age_days",
        "preferred_branch_id"
    ]

    final_feature_df = merge_unique_features(
        final_feature_df,
        customers_master,
        key="customer_id",
        label="Customer master",
        include=customer_features
    )

branches_master = cleaned_data["branches"].copy(deep=True)

if "branch_id" in branches_master.columns:
    branches_master["branch_id"] = (
        branches_master["branch_id"].astype("string").str.strip()
    )

    branch_features = [
        "branch_name",
        "branch_city",
        "branch_state",
        "branch_zone",
        "branch_type"
    ]


    if "branch_id" in final_feature_df.columns:
        final_feature_df["branch_id"] = (
            final_feature_df["branch_id"].astype("string").str.strip()
        )

    final_feature_df = merge_unique_features(
        final_feature_df,
        branches_master,
        key="branch_id",
        label="Branch master",
        include=branch_features
    )


sla_features = [
    "sla_status",
    "sla_category",
    "sla_breached_flag",
    "near_breach_flag",
    "elapsed_hours",
    "sla_remaining_hours",
    "sla_breach_risk"
]

sla_source = globals().get("service_request_sla_analysis")

if isinstance(sla_source, pd.DataFrame):
    final_feature_df = merge_unique_features(
        final_feature_df,
        sla_source,
        key="request_id",
        label="SLA analysis",
        include=sla_features
    )
else:
    print(
        "INFO: service_request_sla_analysis unavailable. "
        "Run Section 8 to add SLA features."
    )

complaint_source = globals().get("complaint_summary")

if not isinstance(complaint_source, pd.DataFrame):
    complaint_source = globals().get("complaint_join")

complaint_features = [
    "complaint_count",
    "customer_complaint_count",
    "complaint_status",
    "complaint_type",
    "sentiment_tag",
    "complaint_severity",
    "repeated_complaint_flag",
    "reopened_complaint_flag",
    "angry_complaint_flag",
    "unresolved_complaint_flag"
]

if isinstance(complaint_source, pd.DataFrame):
    final_feature_df = merge_unique_features(
        final_feature_df,
        complaint_source,
        key="request_id",
        label="Complaint analysis",
        include=complaint_features
    )
else:
    print("INFO: Complaint analysis unavailable. Run Section 10.")

ticket_source = globals().get("ticket_summary")

if not isinstance(ticket_source, pd.DataFrame):
    ticket_source = globals().get("ticket_join")

ticket_features = [
    "ticket_count",
    "ticket_status",
    "assigned_team_ticket",
    "escalation_flag",
    "max_ticket_age_hours",
    "ticket_severity",
    "ticket_issue_tag",
    "ticket_sla_breached_flag",
    "ticket_delay_warning_flag",
    "slow_resolution_flag"
]

if isinstance(ticket_source, pd.DataFrame):
    final_feature_df = merge_unique_features(
        final_feature_df,
        ticket_source,
        key="request_id",
        label="Ticket analysis",
        include=ticket_features
    )
else:
    print("INFO: Ticket analysis unavailable. Run Section 11.")

duplicate_source = globals().get("suspicious_requests")

if not isinstance(duplicate_source, pd.DataFrame):
    duplicate_source = globals().get("service_requests_df")

duplicate_features = [
    "duplicate_suspected",
    "duplicate_group_key",
    "duplicate_reason",
    "duplicate_id_flag",
    "same_day_repeat_flag",
    "recurring_issue_flag",
    "unresolved_repeat_count"
]

if isinstance(duplicate_source, pd.DataFrame):
    duplicate_source = duplicate_source.drop_duplicates(
        subset=["request_id"]
    )

    final_feature_df = merge_unique_features(
        final_feature_df,
        duplicate_source,
        key="request_id",
        label="Duplicate/repeated-request analysis",
        include=duplicate_features
    )
else:
    print("INFO: Duplicate analysis unavailable. Run Section 12.")

updates_df = cleaned_data.get("updates")

if isinstance(updates_df, pd.DataFrame) and {
    "request_id", "update_id"
}.issubset(updates_df.columns):

    updates_work = updates_df.copy(deep=True)
    updates_work["request_id"] = (
        updates_work["request_id"].astype("string").str.strip()
    )

    if "update_date" in updates_work.columns:
        updates_work["update_date"] = pd.to_datetime(
            updates_work["update_date"], errors="coerce"
        )
        updates_work = updates_work.sort_values(
            "update_date", ascending=True, na_position="first"
        )

    updates_work["reassignment_flag"] = (
        updates_work["reassignment_flag"]
        .astype("string").str.strip().str.lower()
        .isin(["true", "1", "yes", "y", "t"])
        if "reassignment_flag" in updates_work.columns
        else False
    )

    aggregation = {
        "update_id": ("update_id", "nunique")
    }

    if "update_date" in updates_work.columns:
        aggregation["last_update_date"] = ("update_date", "max")

    if "status_to" in updates_work.columns:
        aggregation["latest_status_from_update"] = ("status_to", "last")

    if "reassignment_flag" in updates_work.columns:
        aggregation["reassignment_count"] = (
            "reassignment_flag", "sum"
        )

    update_summary = (
        updates_work.groupby("request_id", as_index=False)
        .agg(**aggregation)
        .rename(columns={"update_id": "status_update_count"})
    )

    final_feature_df = merge_unique_features(
        final_feature_df,
        update_summary,
        key="request_id",
        label="Status-update summary"
    )
else:
    print("INFO: Status updates unavailable or required columns are missing.")


branch_analysis = globals().get("branch_issue_summary")

if isinstance(branch_analysis, pd.DataFrame) and "branch_id" in branch_analysis.columns:
    branch_analysis = branch_analysis.copy()
    branch_analysis["branch_id"] = (
        branch_analysis["branch_id"].astype("string").str.strip()
    )

    branch_metric_candidates = [
        c for c in branch_analysis.columns
        if c not in {
            "branch_id", "branch_name", "branch_city",
            "branch_state", "branch_zone", "branch_type"
        }
    ]

    if "branch_id" in final_feature_df.columns:
        final_feature_df = merge_unique_features(
            final_feature_df,
            branch_analysis,
            key="branch_id",
            label="Branch risk analysis",
            include=branch_metric_candidates
        )

text_defaults = {
    "branch_name": "Unknown Branch",
    "branch_city": "Unknown",
    "branch_state": "Unknown",
    "branch_zone": "Unknown",
    "branch_type": "Unknown",
    "customer_segment": "Unknown",
    "account_type": "Unknown",
    "complaint_status": "No Complaint",
    "complaint_type": "None",
    "sentiment_tag": "None",
    "complaint_severity": "None",
    "ticket_status": "No Ticket",
    "assigned_team_ticket": "Unassigned",
    "ticket_severity": "None",
    "ticket_issue_tag": "No Ticket Issue",
    "duplicate_reason": "No duplicate pattern detected"
}

for col, default in text_defaults.items():
    if col in final_feature_df.columns:
        final_feature_df[col] = final_feature_df[col].fillna(default)

count_columns = [
    "complaint_count",
    "customer_complaint_count",
    "ticket_count",
    "status_update_count",
    "reassignment_count",
    "unresolved_repeat_count"
]

for col in count_columns:
    if col in final_feature_df.columns:
        final_feature_df[col] = (
            pd.to_numeric(final_feature_df[col], errors="coerce")
            .fillna(0)
            .astype(int)
        )

boolean_columns = [
    "repeated_complaint_flag",
    "reopened_complaint_flag",
    "angry_complaint_flag",
    "unresolved_complaint_flag",
    "escalation_flag",
    "ticket_sla_breached_flag",
    "ticket_delay_warning_flag",
    "slow_resolution_flag",
    "duplicate_suspected",
    "duplicate_id_flag",
    "same_day_repeat_flag",
    "recurring_issue_flag",
    "sla_breached_flag",
    "near_breach_flag"
]

for col in boolean_columns:
    if col in final_feature_df.columns:
        final_feature_df[col] = (
            final_feature_df[col]
            .astype("boolean")
            .fillna(False)
            .astype(bool)
        )

assert len(final_feature_df) == initial_request_count, (
    "ERROR: Final merge changed the service-request row count."
)

assert final_feature_df["request_id"].is_unique, (
    "ERROR: Duplicate request IDs found in final feature table."
)

final_feature_summary = pd.DataFrame({
    "Metric": [
        "Input service-request rows",
        "Final feature-table rows",
        "Unique request IDs",
        "Final feature columns",
        "Duplicate request IDs",
        "Requests with complaints",
        "Requests with tickets",
        "Requests flagged as duplicate/repeated"
    ],
    "Value": [
        initial_request_count,
        len(final_feature_df),
        final_feature_df["request_id"].nunique(),
        len(final_feature_df.columns),
        int(final_feature_df["request_id"].duplicated().sum()),
        int(
            (final_feature_df["complaint_count"] > 0).sum()
        ) if "complaint_count" in final_feature_df.columns else "Not available",
        int(
            (final_feature_df["ticket_count"] > 0).sum()
        ) if "ticket_count" in final_feature_df.columns else "Not available",
        int(
            final_feature_df["duplicate_suspected"].sum()
        ) if "duplicate_suspected" in final_feature_df.columns else "Not available"
    ]
})

print("Section 13: Final Feature Table / Master Merge completed.")
print("Final table shape:", final_feature_df.shape)

display(final_feature_summary)
display(final_feature_df.head(10))
display(final_feature_df.dtypes.to_frame("data_type"))

Added 5 feature columns from Customer master.
Added 5 feature columns from Branch master.
Added 2 feature columns from SLA analysis.
Added 10 feature columns from Complaint analysis.
Added 10 feature columns from Ticket analysis.
Added 7 feature columns from Duplicate/repeated-request analysis.
Added 4 feature columns from Status-update summary.
Added 9 feature columns from Branch risk analysis.
Section 13: Final Feature Table / Master Merge completed.
Final table shape: (4992, 69)

                                   Metric  Value
0              Input service-request rows   4992
1                Final feature-table rows   4992
2                      Unique request IDs   4992
3                   Final feature columns     69
4                   Duplicate request IDs      0
5                Requests with complaints   1266
6                   Requests with tickets   1255
7  Requests flagged as duplicate/repeated      0

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,customer_name,customer_segment,account_type,relationship_age_days,preferred_branch_id,branch_name,branch_city,branch_state,branch_zone,branch_type,sla_status,elapsed_hours,complaint_count,customer_complaint_count,complaint_status,complaint_type,sentiment_tag,complaint_severity,repeated_complaint_flag,reopened_complaint_flag,angry_complaint_flag,unresolved_complaint_flag,ticket_count,ticket_status,assigned_team_ticket,escalation_flag,max_ticket_age_hours,ticket_severity,ticket_issue_tag,ticket_sla_breached_flag,ticket_delay_warning_flag,slow_resolution_flag,duplicate_suspected,duplicate_group_key,duplicate_reason,duplicate_id_flag,same_day_repeat_flag,recurring_issue_flag,unresolved_repeat_count,status_update_count,last_update_date,latest_status_from_update,reassignment_count,total_requests,pending_requests,sla_breaches,branch_risk_score,near_sla_breaches,avg_elapsed_hours,pending_rate_pct,sla_breach_rate_pct,near_breach_rate_pct
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,Vikram Khan,Corporate,Savings,499,BR0574,HDFC Jodhpur Service Branch 0566,Jodhpur,Rajasthan,North,Urban,Breached,1536.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,10.0,6.0,8.0,58.00,0.0,1243.200000,60.000000,80.000000,0.000000
1,REQ0000010,CUST000649,BR0980,2026-05-17,22:31:00,Card,Failed ATM Withdrawal,WhatsApp,pending_customer,36,Cards Operations,24383.2,2026-05-18,NaT,False,False,False,Vivaan Mehta,Corporate,NRI Savings,3430,BR0458,HDFC Kozhikode Service Branch 0980,Kozhikode,Kerala,South,Metro,Breached,1056.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,9.0,5.0,6.0,50.00,0.0,1157.333333,55.555556,66.666667,0.000000
2,REQ0000011,CUST000817,BR0045,2026-06-19,04:47:00,Digital Banking,NetBanking Login,Email,closed,24,Digital Banking Support,193459.78,2026-06-19,2026-06-19,False,False,False,Vivaan Agarwal,Senior Citizen,Current,872,BR0509,HDFC Noida Service Branch 0045,Noida,Delhi NCR,North,Semi-Urban,Within SLA,0.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,1,2026-07-01,resolved,0,5.0,2.0,3.0,46.00,1.0,720.000000,40.000000,60.000000,20.000000
3,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,Reyansh Malhotra,NRI,Savings,2590,BR0622,HDFC Hyderabad Service Branch 0335,Hyderabad,Telangana,South,Rural,Breached,1704.0,0,0,No Complaint,None,None,None,False,False,False,False,1,open,Customer Care,False,1704.0,Severe,Ticket SLA Breach; Active Ticket,True,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,1.0,2.0,32.50,0.0,456.000000,25.000000,50.000000,0.000000
4,REQ0000013,CUST001137,BR0081,2026-06-13,07:18:00,Account,Balance Mismatch,NetBanking,closed,48,Account Servicing,<NA>,2026-06-16,2026-06-16,False,False,False,Saanvi Iyer,Corporate,Loan Account,950,BR0144,HDFC Kochi Service Branch 0081,Kochi,Kerala,South,Urban,Breached,72.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,5.0,0.0,1.0,14.00,1.0,38.400000,0.000000,20.000000,20.000000
5,REQ0000014,CUST000892,BR0091,2026-04-25,06:03:00,KYC,Document Rejected,Call Center,closed,72,KYC Operations,<NA>,2026-04-26,2026-04-26,False,False,False,Aditya Chopra,Senior Citizen,Salary,801,BR0772,HDFC Mysuru Service Branch 0091,Mysuru,Karnataka,South,Semi-Urban,Within SLA,24.0,1,2,resolved,loan_servicing,neutral,Moderate,True,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,3.0,2.0,2.0,53.33,0.0,1616.000000,66.666667,66.666667,0.000000
6,REQ0000015,CUST001118,BR0262,2026-02-22,19:15:00,Account,Account Freeze,Email,resolved,48,Account Servicing,<NA>,2026-02-25,2026-02-24,False,False,False,Sai Bhat,Preferred,NRI Savings,3178,BR0894,HDFC Coimbatore Service Branch 0262,Coimbatore,TAMIL NADU,South,Metro,Near Breach,48.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,7.0,2.0,4.0,40.00,1.0,466.285714,28.571429,57.142857,14.285714
7,REQ0000016,CUST000669,BR0422,2026-05-25,15:46:00,Account,Account Freeze,Branch,resolved,48,Account Servicing,<NA>,2026-05-27,2026-05-27,False,False,False,Saanvi Nair,Preferred,NRI Savings,884,BR0874,HDFC Lucknow Service Branch 0422,Lucknow,Uttar Pradesh,North,Rural,Near Breach,48.0,0,0,No Complaint,None,None,None,False,False,False,False,1,open,Grievance Desk,False,744.0,Severe,Ticket SLA Breach; Active Ticket,True,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,6.0,3.0,4.0,51.67,1.0,1272.000000,50.000000,66.666667,16.666667
8,REQ0000017,CUST000492,BR0179,2026-04-21,18:52:00,Digital Banking,NetBanking Login,WhatsApp,pending_customer,24,Digital Banking Support,158525.74,2026-04-22,NaT,False,False,False,Dev Singh,Student,Savings,811,BR0121,HDFC Thiruvananthapuram Service Branch 0179,Thiruvananthapuram,Kerala,South,Digital Service Hub,Breached,1680.0,1,3,in_review,sla_delay,negative,Severe,True,False,True,True,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,2.0,3.0,52.50,0.0,558.000000,50.000000,75.000000,0.000000
9,REQ0000018,CUST000133,BR0198,2026-04-24,02:08:00,Complaint,Fraud Concern,WhatsApp,resolved,72,Customer Grievance,13453.42,2026-04-28,2026-04-28,False,False,False,Navya Sharma,Senior Citizen,NRI Savings,199,BR0587,HDFC Salem Service Branch 0198,Salem,Tamil Nadu,South,Digital Service Hub,Breached,96.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,12.0,7.0,9.0,56.67,1.0,1940.000000,58.333333,75.000000,8.333333

                           data_type
request_id                    object
customer_id                   object
branch_id             string[python]
request_created_date  datetime64[ns]
request_created_time          object
...                              ...
near_sla_breaches            float64
avg_elapsed_hours            float64
pending_rate_pct             float64
sla_breach_rate_pct          float64
near_breach_rate_pct         float64

[69 rows x 1 columns]

### Expected Output — Section 13: Final Feature Table / Master Merge

**Datasets to use:**

- Cleaned service requests
- SLA analysis output
- Branch analysis output
- Complaint summary output
- Ticket summary output
- Customers master
- Branches master
- Duplicate/repeated request output
- Status update output

**How to approach:**

- Build one request-level master table.
- Preserve one row per `request_id` as much as possible.
- Use left joins from service requests to all feature tables.
- Fill missing feature columns with business-readable defaults such as `No Complaint`, `No Ticket`, `Unknown Branch`, or `No`.

**Expected output format:**

Create a DataFrame such as `final_feature_df` with one row per request and columns from all business areas:

| Area | Example Columns |
|---|---|
| Request | `request_id`, `customer_id`, `branch_id`, `request_category`, `request_status`, `sla_status` |
| Branch | `branch_name`, `branch_city`, `branch_zone`, `branch_type` |
| Complaint | `complaint_count`, `complaint_status`, `complaint_severity`, `sentiment_tag` |
| Ticket | `ticket_count`, `ticket_status`, `ticket_severity`, `escalation_flag` |
| Customer | `customer_segment`, `account_type`, `relationship_age_days` |
| Duplicate | `duplicate_suspected`, `duplicate_reason` |

**Hint:** A final feature table is the backbone for priority classification, recommended actions, GUI, and export. Make it stable before moving forward.

In [ ]:

import pandas as pd
import numpy as np

if "final_feature_df" not in globals():
    raise NameError("final_feature_df is missing. Run Section 13 first.")

priority_df = final_feature_df.copy(deep=True)

if "request_id" not in priority_df.columns:
    raise ValueError("final_feature_df must contain request_id.")

if priority_df["request_id"].duplicated().any():
    raise ValueError(
        "Duplicate request_id values found. Fix Section 13 before proceeding."
    )

def flag_series(df, column):
    """Return a reliable Boolean series; absent flags default to False."""
    if column not in df.columns:
        return pd.Series(False, index=df.index, dtype=bool)

    values = df[column]

    if pd.api.types.is_bool_dtype(values.dtype):
        return values.fillna(False).astype(bool)

    true_values = {
        "true", "1", "yes", "y", "t", "breached",
        "breach", "escalated", "severe"
    }

    return (
        values.astype("string")
        .str.strip()
        .str.lower()
        .isin(true_values)
        .fillna(False)
    )


def numeric_series(df, column):
    if column not in df.columns:
        return pd.Series(0.0, index=df.index)

    return pd.to_numeric(df[column], errors="coerce").fillna(0)


def normalized_series(df, column, default=""):
    if column not in df.columns:
        return pd.Series(default, index=df.index, dtype="string")

    return (
        df[column]
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"[\s-]+", "_", regex=True)
        .fillna(default)
    )


request_status = normalized_series(priority_df, "request_status")
sla_status = normalized_series(priority_df, "sla_status")
complaint_severity = normalized_series(priority_df, "complaint_severity")
ticket_severity = normalized_series(priority_df, "ticket_severity")
sentiment = normalized_series(priority_df, "sentiment_tag")

sla_breached = (
    flag_series(priority_df, "sla_breached_flag")
    | sla_status.str.contains(r"breach|overdue|missed", regex=True)
)

near_breach = (
    flag_series(priority_df, "near_breach_flag")
    | flag_series(priority_df, "ticket_delay_warning_flag")
    | sla_status.str.contains(r"near.?breach|at.?risk|warning", regex=True)
)

escalated = (
    flag_series(priority_df, "escalation_flag")
    | request_status.eq("escalated")
    | ticket_severity.eq("severe")
)

severe_complaint = complaint_severity.eq("severe")
moderate_complaint = complaint_severity.eq("moderate")
reopened_complaint = flag_series(priority_df, "reopened_complaint_flag")
angry_complaint = (
    flag_series(priority_df, "angry_complaint_flag")
    | sentiment.isin(["angry", "very_angry", "negative", "very_negative"])
)

unresolved_complaint = flag_series(
    priority_df, "unresolved_complaint_flag"
)
repeated_complaint = flag_series(
    priority_df, "repeated_complaint_flag"
)
duplicate_suspected = flag_series(
    priority_df, "duplicate_suspected"
)

ticket_sla_breach = flag_series(
    priority_df, "ticket_sla_breached_flag"
)
slow_resolution = flag_series(priority_df, "slow_resolution_flag")

active_ticket = (
    request_status.isin([
        "open", "pending", "pending_customer", "in_progress",
        "in_review", "reopened", "escalated"
    ])
    | normalized_series(priority_df, "ticket_status").isin([
        "open", "pending", "pending_customer", "in_progress",
        "in_review", "reopened", "escalated"
    ])
)

complaint_count = numeric_series(priority_df, "complaint_count")
customer_complaint_count = numeric_series(
    priority_df, "customer_complaint_count"
)
ticket_count = numeric_series(priority_df, "ticket_count")


def is_p0(i):

    return bool(
        (sla_breached.iloc[i] and escalated.iloc[i])
        or (
            sla_breached.iloc[i]
            and (severe_complaint.iloc[i] or angry_complaint.iloc[i])
        )
        or (ticket_sla_breach.iloc[i] and escalated.iloc[i])
    )


def is_p1(i):
    return bool(
        sla_breached.iloc[i]
        or escalated.iloc[i]
        or severe_complaint.iloc[i]
        or angry_complaint.iloc[i]
        or reopened_complaint.iloc[i]
        or ticket_sla_breach.iloc[i]
    )


def is_p2(i):
    return bool(
        near_breach.iloc[i]
        or moderate_complaint.iloc[i]
        or unresolved_complaint.iloc[i]
        or repeated_complaint.iloc[i]
        or duplicate_suspected.iloc[i]
        or slow_resolution.iloc[i]
        or (
            active_ticket.iloc[i]
            and ticket_count.iloc[i] > 0
        )
        or customer_complaint_count.iloc[i] >= 3
    )


def is_p3(i):
    return bool(
        active_ticket.iloc[i]
        or request_status.iloc[i] in {
            "open", "pending", "pending_customer",
            "in_progress", "in_review", "reopened"
        }
        or complaint_count.iloc[i] > 0
        or ticket_count.iloc[i] > 0
    )

def classify_request(i):
    if is_p0(i):
        return "P0"
    if is_p1(i):
        return "P1"
    if is_p2(i):
        return "P2"
    if is_p3(i):
        return "P3"
    return "No Issue"


priority_df["request_priority"] = [
    classify_request(i) for i in range(len(priority_df))
]

def explain_priority(i, priority):
    reasons = []

    if sla_breached.iloc[i]:
        reasons.append("Request SLA breached")
    if ticket_sla_breach.iloc[i]:
        reasons.append("Ticket SLA breached")
    if escalated.iloc[i]:
        reasons.append("Escalated or severe ticket")
    if severe_complaint.iloc[i]:
        reasons.append("Severe complaint")
    if angry_complaint.iloc[i]:
        reasons.append("Angry/negative customer sentiment")
    if reopened_complaint.iloc[i]:
        reasons.append("Reopened complaint")
    if near_breach.iloc[i]:
        reasons.append("SLA near breach or delay warning")
    if moderate_complaint.iloc[i]:
        reasons.append("Moderate complaint severity")
    if unresolved_complaint.iloc[i]:
        reasons.append("Unresolved complaint")
    if repeated_complaint.iloc[i]:
        reasons.append("Repeated customer complaints")
    if duplicate_suspected.iloc[i]:
        reasons.append("Possible duplicate/repeated request")
    if slow_resolution.iloc[i]:
        reasons.append("Slow ticket resolution")
    if customer_complaint_count.iloc[i] >= 3:
        reasons.append("Customer has multiple complaints")
    if active_ticket.iloc[i]:
        reasons.append("Request or ticket remains active")
    if complaint_count.iloc[i] > 0 and not reasons:
        reasons.append("Complaint linked; no higher-level risk detected")
    if ticket_count.iloc[i] > 0 and not reasons:
        reasons.append("Ticket linked; no higher-level risk detected")

    if not reasons:
        if priority == "No Issue":
            return "No identified SLA, complaint, escalation, or repeat-request issue"
        return "Routine request requiring monitoring"

    return "; ".join(dict.fromkeys(reasons))


priority_df["priority_reason"] = [
    explain_priority(i, priority_df.iloc[i]["request_priority"])
    for i in range(len(priority_df))
]

impact_score = pd.Series(0.0, index=priority_df.index)

impact_score += sla_breached.astype(float) * 30
impact_score += ticket_sla_breach.astype(float) * 20
impact_score += escalated.astype(float) * 25
impact_score += severe_complaint.astype(float) * 25
impact_score += angry_complaint.astype(float) * 15
impact_score += reopened_complaint.astype(float) * 10
impact_score += near_breach.astype(float) * 15
impact_score += moderate_complaint.astype(float) * 10
impact_score += unresolved_complaint.astype(float) * 10
impact_score += repeated_complaint.astype(float) * 10
impact_score += duplicate_suspected.astype(float) * 10
impact_score += slow_resolution.astype(float) * 10
impact_score += (customer_complaint_count >= 3).astype(float) * 10

priority_df["customer_impact_score"] = (
    impact_score.clip(lower=0, upper=100).round(0).astype(int)
)

def impact_level(score):
    if score >= 80:
        return "Critical"
    if score >= 60:
        return "High"
    if score >= 30:
        return "Moderate"
    return "Low"

priority_df["customer_impact_level"] = (
    priority_df["customer_impact_score"].map(impact_level)
)

allowed_priorities = {"P0", "P1", "P2", "P3", "No Issue"}

assert priority_df["request_priority"].notna().all(), (
    "Some requests have no priority."
)
assert set(priority_df["request_priority"].unique()).issubset(
    allowed_priorities
), "Unexpected priority label found."

assert priority_df["customer_impact_score"].between(0, 100).all(), (
    "Impact score outside 0–100."
)

assert len(priority_df) == len(final_feature_df), (
    "Row count changed during priority classification."
)

assert priority_df["request_id"].is_unique, (
    "Duplicate request IDs found."
)

final_feature_df = priority_df.copy(deep=True)

print("Section 14: Request Priority Classification completed.")
print("\nPriority counts:")
display(
    final_feature_df["request_priority"]
    .value_counts()
    .reindex(["P0", "P1", "P2", "P3", "No Issue"], fill_value=0)
    .rename_axis("request_priority")
    .to_frame("request_count")
)

print("\nCustomer impact levels:")
display(final_feature_df["customer_impact_level"].value_counts())

sample_columns = [
    "request_id",
    "request_status",
    "request_priority",
    "priority_reason",
    "customer_impact_score",
    "customer_impact_level"
]

sample_columns = [
    col for col in sample_columns if col in final_feature_df.columns
]

for label in ["P0", "P1", "P2", "P3", "No Issue"]:
    print(f"\nSample records — {label}")
    sample = final_feature_df.loc[
        final_feature_df["request_priority"] == label,
        sample_columns
    ].head(5)
    display(sample)

Section 14: Request Priority Classification completed.

Priority counts:

                  request_count
request_priority
P0                         1956
P1                         2418
P2                           27
P3                           20
No Issue                    571

Customer impact levels:

customer_impact_level
Moderate    2647
Critical    1068
High         669
Low          608
Name: count, dtype: int64

Sample records — P0

    request_id    request_status request_priority                                    priority_reason  customer_impact_score customer_impact_level
3   REQ0000012       in_progress               P0  Request SLA breached; Ticket SLA breached; Esc...                     75                  High
7   REQ0000016          resolved               P0  Request SLA breached; Ticket SLA breached; Esc...                     90              Critical
8   REQ0000017  pending_customer               P0  Request SLA breached; Severe complaint; Angry/...                    100              Critical
11  REQ0000020       in_progress               P0  Request SLA breached; Escalated or severe tick...                     55              Moderate
16  REQ0000025          resolved               P0  Ticket SLA breached; Escalated or severe ticke...                    100              Critical

Sample records — P1

   request_id    request_status request_priority                                    priority_reason  customer_impact_score customer_impact_level
0  REQ0000009       in_progress               P1  Request SLA breached; Request or ticket remain...                     30              Moderate
1  REQ0000010  pending_customer               P1  Request SLA breached; Request or ticket remain...                     30              Moderate
4  REQ0000013            closed               P1                               Request SLA breached                     30              Moderate
6  REQ0000015          resolved               P1  Request SLA breached; SLA near breach or delay...                     45              Moderate
9  REQ0000018          resolved               P1                               Request SLA breached                     30              Moderate

Sample records — P2

     request_id request_status request_priority                                    priority_reason  customer_impact_score customer_impact_level
5    REQ0000014         closed               P2  Moderate complaint severity; Repeated customer...                     20                   Low
104  REQ0000113       resolved               P2  Moderate complaint severity; Unresolved compla...                     30              Moderate
590  REQ0000599       resolved               P2  Moderate complaint severity; Unresolved compla...                     30              Moderate
696  REQ0000705       resolved               P2  Moderate complaint severity; Unresolved compla...                     40              Moderate
718  REQ0000727       resolved               P2  Moderate complaint severity; Unresolved complaint                     20                   Low

Sample records — P3

     request_id request_status request_priority                                  priority_reason  customer_impact_score customer_impact_level
22   REQ0000031       resolved               P3     Ticket linked; no higher-level risk detected                      0                   Low
76   REQ0000085       resolved               P3  Complaint linked; no higher-level risk detected                      0                   Low
80   REQ0000089       resolved               P3     Ticket linked; no higher-level risk detected                      0                   Low
146  REQ0000155       resolved               P3     Ticket linked; no higher-level risk detected                      0                   Low
823  REQ0000832       resolved               P3     Ticket linked; no higher-level risk detected                      0                   Low

Sample records — No Issue

    request_id request_status request_priority                                    priority_reason  customer_impact_score customer_impact_level
2   REQ0000011         closed         No Issue  No identified SLA, complaint, escalation, or r...                      0                   Low
15  REQ0000024       resolved         No Issue  No identified SLA, complaint, escalation, or r...                      0                   Low
27  REQ0000036       resolved         No Issue  No identified SLA, complaint, escalation, or r...                      0                   Low
31  REQ0000040         closed         No Issue  No identified SLA, complaint, escalation, or r...                      0                   Low
32  REQ0000041       resolved         No Issue  No identified SLA, complaint, escalation, or r...                      0                   Low

### Expected Output — Section 14: Request Priority Classification

**Datasets to use:**

- Final feature table from Section 13

**How to approach:**

- Implement priority rules from the PRD.
- Apply hierarchy in this exact order: **P0 > P1 > P2 > P3 > No Issue**.
- Generate both `request_priority` and `priority_reason`.
- Every request must receive exactly one priority label.
- Calculate `customer_impact_score` and `customer_impact_level`.

**Expected output format:**

Create columns:

| Column | Meaning |
|---|---|
| `request_priority` | `P0`, `P1`, `P2`, `P3`, or `No Issue` |
| `priority_reason` | Business-readable reason for the assigned priority |
| `customer_impact_score` | Numeric score capped at 100 |
| `customer_impact_level` | Low/Moderate/High/Critical |

Show:

- `value_counts()` for `request_priority`.
- Sample P0, P1, P2, P3, and No Issue rows.

**Hint:** Avoid flat logic that misses important business rules. Write helper functions for P0/P1/P2/P3 checks or keep the logic very readable.

In [ ]:
import pandas as pd
import numpy as np

if "final_feature_df" not in globals():
    raise NameError(
        "final_feature_df not found. Run Section 13 and Section 14 first."
    )

if "request_id" not in final_feature_df.columns:
    raise KeyError("final_feature_df must contain 'request_id'.")

if "request_priority" not in final_feature_df.columns:
    raise KeyError(
        "request_priority not found. Run Section 14 first."
    )

action_df = final_feature_df.copy(deep=True)


def get_text(row, *columns):
    """Return the first non-empty value from available columns."""
    for column in columns:
        if column in row.index:
            value = row.get(column)

            if pd.notna(value):
                value = str(value).strip()
                if value and value.lower() not in {
                    "nan", "none", "nat", "<na>", "unknown"
                }:
                    return value

    return ""


def get_flag(row, *columns):
    """Safely interpret boolean, numeric and text-based flags."""
    true_values = {
        "true", "1", "yes", "y", "t", "flagged",
        "breached", "breach", "escalated"
    }

    for column in columns:
        if column not in row.index:
            continue

        value = row.get(column)

        if pd.isna(value):
            continue

        if isinstance(value, (bool, np.bool_)):
            if value:
                return True
            continue

        if isinstance(value, (int, float, np.integer, np.floating)):
            if value == 1:
                return True
            continue

        if str(value).strip().lower() in true_values:
            return True

    return False


def contains_any(value, keywords):
    """Check whether a normalized text contains any keyword."""
    value = str(value).strip().lower()
    return any(keyword in value for keyword in keywords)

def recommend_action(row):

    priority = get_text(row, "request_priority").upper()

    # SLA indicators
    sla_status = get_text(
        row, "sla_status", "sla_category", "sla_breach_risk"
    ).lower()

    sla_breached = (
        get_flag(row, "sla_breached_flag", "sla_breach_flag")
        or contains_any(
            sla_status,
            ["breach", "overdue", "missed", "violated"]
        )
    )

    near_breach = (
        get_flag(row, "near_breach_flag", "sla_near_breach_flag")
        or contains_any(
            sla_status,
            ["near breach", "near_breach", "at risk", "warning"]
        )
    )

    complaint_severity = get_text(
        row, "complaint_severity"
    ).lower()

    sentiment = get_text(
        row, "sentiment_tag", "complaint_sentiment"
    ).lower()

    complaint_status = get_text(
        row, "complaint_status"
    ).lower()

    severe_complaint = (
        contains_any(
            complaint_severity,
            ["severe", "critical", "high"]
        )
        or contains_any(
            sentiment,
            ["angry", "negative", "very_negative", "very negative"]
        )
        or get_flag(row, "angry_complaint_flag")
    )

    unresolved_complaint = (
        get_flag(row, "unresolved_complaint_flag")
        or (
            bool(complaint_status)
            and contains_any(
                complaint_status,
                ["open", "pending", "unresolved", "in progress"]
            )
        )
    )

    repeated_complaint = get_flag(
        row,
        "repeated_complaint_flag",
        "repeat_complaint_flag"
    )

    reopened_complaint = get_flag(
        row, "reopened_complaint_flag"
    )

    # Ticket indicators
    ticket_severity = get_text(
        row, "ticket_severity"
    ).lower()

    ticket_status = get_text(
        row, "ticket_status"
    ).lower()

    ticket_team = get_text(
        row, "assigned_team_ticket", "assigned_team"
    )

    ticket_breached = get_flag(
        row, "ticket_sla_breached_flag",
        "ticket_breach_flag"
    )

    ticket_escalated = get_flag(
        row, "escalation_flag",
        "ticket_escalation_flag"
    ) or contains_any(
        ticket_status, ["escalated"]
    )

    active_ticket = (
        bool(ticket_status)
        and contains_any(
            ticket_status,
            ["open", "pending", "in progress", "in_progress",
             "reopened", "escalated", "under review"]
        )
    )

    request_status = get_text(
        row, "request_status"
    ).lower()

    request_category = get_text(
        row, "request_category", "request_subcategory"
    )

    customer_segment = get_text(
        row, "customer_segment"
    )

    branch_name = get_text(
        row, "branch_name"
    )

    branch_city = get_text(
        row, "branch_city"
    )

    branch_description = branch_name or branch_city or "responsible branch"

    duplicate_flag = get_flag(
        row,
        "duplicate_suspected",
        "duplicate_id_flag",
        "same_day_repeat_flag",
        "recurring_issue_flag"
    )

    active_request = contains_any(
        request_status,
        ["open", "pending", "in progress", "in_progress",
         "reopened", "escalated", "under review"]
    )

    explicit_escalation = ticket_escalated or get_flag(
        row, "escalation_flag"
    )

    category_lower = request_category.lower()

    if priority == "P0":
        if severe_complaint:
            return (
                "Immediate manager callback; assign the Grievance Desk "
                "owner, acknowledge the complaint, and review the SLA "
                "breach today."
            )

        if sla_breached and explicit_escalation:
            return (
                "Immediately alert the operations manager; assign an "
                "accountable resolution owner, recover the SLA breach, "
                "and provide the customer with a same-day update."
            )

        if ticket_breached and explicit_escalation:
            team_action = (
                f" Route the case to {ticket_team} with escalation notes."
                if ticket_team else
                " Route the case to the responsible ticket owner with "
                "escalation notes."
            )
            return (
                "Prioritize the breached ticket for immediate resolution; "
                "notify the operations manager and confirm the recovery "
                "plan today." + team_action
            )

        return (
            "Arrange immediate supervisor review; assign a named owner, "
            "confirm the main service risk, and communicate the next "
            "resolution milestone to the customer today."
        )

    if severe_complaint:
        return (
            "Contact the customer promptly; assign the Grievance Desk or "
            "senior support owner, investigate the complaint, and record "
            "the corrective action and follow-up commitment."
        )

    if sla_breached:
        return (
            "Route the request to the responsible operations team for "
            "SLA recovery; confirm the delay reason, assign a resolution "
            "deadline, and update the customer today."
        )

    if ticket_breached or explicit_escalation:
        team_action = (
            f" Route to {ticket_team} and request a status update with "
            "escalation notes."
            if ticket_team else
            " Route to the responsible ticket owner and request a "
            "documented status update with escalation notes."
        )
        return (
            "Review the escalated support ticket, confirm ownership, "
            "and agree on the next resolution milestone." + team_action
        )

    if reopened_complaint:
        return (
            "Review why the complaint was reopened, verify the previous "
            "resolution, assign a corrective-action owner, and confirm "
            "the outcome with the customer."
        )

    if unresolved_complaint:
        return (
            "Assign the unresolved complaint to its responsible owner; "
            "review pending work, document the next step, and send the "
            "customer a progress update."
        )

    if duplicate_flag:
        return (
            "Verify whether this request duplicates an existing case; "
            "check linked request IDs and prior actions before merging "
            "or closing anything. Preserve the audit trail."
        )

    if near_breach:
        return (
            "Contact the assigned team, prioritize the pending work "
            "before the SLA deadline, and notify the customer if a delay "
            "is likely."
        )

    if repeated_complaint:
        return (
            "Review the customer's previous complaints, identify the "
            "recurring cause, and assign a single owner to coordinate "
            "resolution and follow-up."
        )


    if contains_any(category_lower, ["kyc", "identity", "document", "verification"]):
        return (
            "Route to KYC Operations; verify the required documents, "
            "record any missing information, and provide the customer "
            "with a status update within the same business day."
        )

    if active_ticket:
        team_action = (
            f" Contact {ticket_team} for a documented status update."
            if ticket_team else
            " Contact the assigned support team for a documented status update."
        )
        return (
            "Review the active support ticket, confirm the pending "
            "resolution step, and check the next follow-up date." + team_action
        )

    if active_request or priority in {"P1", "P2", "P3"}:
        branch_action = (
            f" Coordinate with {branch_description}."
            if branch_name or branch_city else ""
        )

        if customer_segment and contains_any(
            customer_segment, ["premium", "priority", "high value"]
        ):
            return (
                "Assign a named service owner, prioritize the customer "
                "update, and confirm the expected resolution timeline."
                + branch_action
            )

        return (
            "Review the current request status, confirm the next pending "
            "step with the responsible team, and update the customer "
            "if action is outstanding." + branch_action
        )

    return (
        "No immediate action required; continue standard service "
        "monitoring and retain the request record for audit purposes."
    )

action_df["recommended_action"] = action_df.apply(
    recommend_action, axis=1
)

assert len(action_df) == len(final_feature_df), (
    "Row count changed while generating recommendations."
)

assert action_df["request_id"].is_unique, (
    "Duplicate request IDs detected in the final feature table."
)

assert action_df["recommended_action"].notna().all(), (
    "Some requests have no recommended action."
)

assert action_df["recommended_action"].astype(str).str.strip().ne("").all(), (
    "Some recommended actions are blank."
)

final_feature_df = action_df.copy(deep=True)

print("SECTION 15: RECOMMENDED ACTION GENERATOR")


print("Status: PASSED")
print(f"Total requests: {len(final_feature_df)}")
print(
    "Unique request IDs:",
    final_feature_df["request_id"].nunique()
)
print(
    "Missing recommended actions:",
    final_feature_df["recommended_action"].isna().sum()
)
print(
    "Unique action messages:",
    final_feature_df["recommended_action"].nunique()
)

print("\nRecommended action examples:")
display(
    final_feature_df[
        ["request_id", "request_priority", "recommended_action"]
    ].head(10)
)

print("\nPriority-wise action coverage:")
display(
    final_feature_df.groupby(
        "request_priority", dropna=False
    ).agg(
        request_count=("request_id", "size"),
        unique_actions=("recommended_action", "nunique")
    ).reset_index()
)

print("\nSection 15 validation completed successfully.")

SECTION 15: RECOMMENDED ACTION GENERATOR
Status: PASSED
Total requests: 4992
Unique request IDs: 4992
Missing recommended actions: 0
Unique action messages: 58

Recommended action examples:

   request_id request_priority                                 recommended_action
0  REQ0000009               P1  Route the request to the responsible operation...
1  REQ0000010               P1  Route the request to the responsible operation...
2  REQ0000011         No Issue  No immediate action required; continue standar...
3  REQ0000012               P0  Arrange immediate supervisor review; assign a ...
4  REQ0000013               P1  Route the request to the responsible operation...
5  REQ0000014               P2  Review the customer's previous complaints, ide...
6  REQ0000015               P1  Route the request to the responsible operation...
7  REQ0000016               P0  Arrange immediate supervisor review; assign a ...
8  REQ0000017               P0  Immediate manager callback; assign the Grievan...
9  REQ0000018               P1  Route the request to the responsible operation...

Priority-wise action coverage:

  request_priority  request_count  unique_actions
0         No Issue            571               2
1               P0           1956              30
2               P1           2418               6
3               P2             27               4
4               P3             20              17

Section 15 validation completed successfully.

### Expected Output — Section 15: Recommended Action Generator

**Datasets to use:**

- Final table with `request_priority`, SLA issue, complaint severity, ticket severity, customer segment, duplicate flag, and branch details.

**How to approach:**

- Convert business rules into readable action messages.
- Recommended actions should help a support or operations user decide the next step.
- Do not return only generic values like `Escalate` or `Check manually`.

**Expected output format:**

Create a column:

| Column | Meaning |
|---|---|
| `recommended_action` | Clear next action for operations team |

Examples of acceptable action style:

- `Immediate manager callback; assign Grievance Desk owner and review SLA breach today.`
- `Escalate to KYC Operations; verify documents and provide customer update within same day.`
- `Route to ticket owner team and request status update with escalation notes.`
- `No immediate action required; continue standard service monitoring.`

**Hint:** Recommended action should be based on the strongest issue in the case, not just the priority label.

In [ ]:
import pandas as pd
import numpy as np

if "final_feature_df" not in globals():
    raise NameError(
        "final_feature_df not found. Run Sections 13-15 first."
    )

required_columns = [
    "request_id",
    "request_priority",
    "recommended_action"
]

missing_columns = [
    col for col in required_columns
    if col not in final_feature_df.columns
]

if missing_columns:
    raise KeyError(
        f"Missing required columns: {missing_columns}"
    )

ai_df = final_feature_df.copy(deep=True)

def safe_value(row, *columns, default="Not available"):
    """Return the first meaningful value from available columns."""
    for col in columns:
        if col not in row.index:
            continue

        value = row.get(col)

        if pd.isna(value):
            continue

        value = str(value).strip()

        if value and value.lower() not in {
            "nan", "none", "nat", "<na>", "unknown"
        }:
            return value

    return default


def safe_flag(row, *columns):
    """Interpret common boolean, numeric and text flags."""
    true_values = {
        "true", "1", "yes", "y", "flagged",
        "breached", "breach", "escalated"
    }

    for col in columns:
        if col not in row.index:
            continue

        value = row.get(col)

        if pd.isna(value):
            continue

        if isinstance(value, (bool, np.bool_)):
            if value:
                return True
            continue

        if isinstance(value, (int, float, np.integer, np.floating)):
            if value == 1:
                return True
            continue

        if str(value).strip().lower() in true_values:
            return True

    return False


def safe_count(row, *columns):
    """Return the first valid non-negative numeric count."""
    for col in columns:
        if col not in row.index:
            continue

        value = pd.to_numeric(
            pd.Series([row.get(col)]), errors="coerce"
        ).iloc[0]

        if pd.notna(value):
            return max(0, int(value))

    return 0

def generate_ai_support_prompt(row):

    priority = safe_value(
        row, "request_priority", default=""
    ).upper()

    if priority not in {"P0", "P1", "P2"}:
        return ""

    request_id = safe_value(
        row, "request_id", default="Not available"
    )

    request_status = safe_value(
        row, "request_status"
    )

    request_category = safe_value(
        row, "request_category"
    )

    request_subcategory = safe_value(
        row, "request_subcategory"
    )

    sla_status = safe_value(
        row, "sla_status",
        "sla_category",
        "sla_breach_risk"
    )

    sla_breached = (
        safe_flag(
            row, "sla_breached_flag", "sla_breach_flag"
        )
        or any(
            word in sla_status.lower()
            for word in ["breach", "overdue", "missed"]
        )
    )

    near_breach = (
        safe_flag(
            row, "near_breach_flag", "sla_near_breach_flag"
        )
        or any(
            word in sla_status.lower()
            for word in ["near breach", "near_breach", "at risk", "warning"]
        )
    )

    complaint_severity = safe_value(
        row, "complaint_severity"
    )

    complaint_status = safe_value(
        row, "complaint_status"
    )

    sentiment = safe_value(
        row, "sentiment_tag", "complaint_sentiment"
    )

    ticket_severity = safe_value(
        row, "ticket_severity"
    )

    ticket_status = safe_value(
        row, "ticket_status"
    )

    ticket_team = safe_value(
        row, "assigned_team_ticket", "assigned_team"
    )

    ticket_escalated = safe_flag(
        row, "escalation_flag", "ticket_escalation_flag"
    )

    repeated_complaint = safe_flag(
        row, "repeated_complaint_flag"
    )

    unresolved_complaint = safe_flag(
        row, "unresolved_complaint_flag"
    )

    recommended_action = safe_value(
        row,
        "recommended_action",
        default="Review the case and determine the appropriate next step."
    )

    issue_signals = []

    if sla_breached:
        issue_signals.append("SLA breach indicated")

    if near_breach:
        issue_signals.append("SLA deadline may be approaching")

    if complaint_severity.lower() not in {
        "not available", "none", "low", "nan"
    }:
        issue_signals.append(
            f"Complaint severity: {complaint_severity}"
        )

    if sentiment.lower() not in {
        "not available", "none", "nan"
    }:
        issue_signals.append(
            f"Recorded complaint sentiment: {sentiment}"
        )

    if unresolved_complaint:
        issue_signals.append("Unresolved complaint flagged")

    if repeated_complaint:
        issue_signals.append("Repeated complaint flagged")

    if ticket_escalated:
        issue_signals.append("Ticket escalation flagged")

    if ticket_severity.lower() not in {
        "not available", "none", "low", "nan"
    }:
        issue_signals.append(
            f"Ticket severity: {ticket_severity}"
        )

    if not issue_signals:
        issue_signals.append(
            "Review the available case information to identify the issue"
        )

    issue_summary = "; ".join(issue_signals)

    if priority == "P0":
        response_guidance = (
            "Treat this as a critical case. Use an empathetic, calm tone, "
            "acknowledge the reported issue, and explain the immediate "
            "follow-up step. Do not claim that the issue is resolved."
        )
    elif priority == "P1":
        response_guidance = (
            "Treat this as a high-priority case. Acknowledge the impact, "
            "explain the next operational step, and communicate only a "
            "verified update or confirmed timeline."
        )
    else:
        response_guidance = (
            "Treat this as a medium-priority case. Acknowledge the concern, "
            "explain the next step clearly, and provide a follow-up "
            "commitment only if it is supported by verified information."
        )

    prompt = f"""
ROLE:
You are a professional customer-support communication assistant.

TASK:
Draft a concise, empathetic customer response for the support executive
to review and send after verifying the facts.

CASE CONTEXT:
- Request reference: {request_id}
- Priority: {priority}
- Request category: {request_category}
- Request subcategory: {request_subcategory}
- Current request status: {request_status}
- SLA status: {sla_status}
- Complaint status: {complaint_status}
- Ticket status: {ticket_status}
- Ticket owner/team: {ticket_team}
- Identified issue signals: {issue_summary}

RECOMMENDED INTERNAL NEXT ACTION:
{recommended_action}

RESPONSE GUIDANCE:
{response_guidance}

OUTPUT REQUIREMENTS:
1. Draft a short, professional customer-facing message.
2. Acknowledge the concern without admitting unverified fault.
3. Explain the next step in plain language.
4. Do not invent facts, investigation results, deadlines, or resolutions.
5. Do not promise compensation, refunds, or a specific resolution time
   unless verified information explicitly supports it.
6. Do not include full customer names, account numbers, passwords,
   confidential internal notes, or unnecessary personal information.
7. Do not expose internal priority labels, risk scores, or internal
   escalation logic to the customer.
8. If information is missing, use a neutral statement or a placeholder
   for the support executive to verify.
9. Return only the draft customer message, not the analysis or instructions.
""".strip()

    return prompt

priority_mask = (
    ai_df["request_priority"]
    .astype("string")
    .str.strip()
    .str.upper()
    .isin(["P0", "P1", "P2"])
)

ai_df["ai_support_prompt"] = ""

ai_df.loc[priority_mask, "ai_support_prompt"] = (
    ai_df.loc[priority_mask]
    .apply(generate_ai_support_prompt, axis=1)
)

reason_columns = [
    col for col in [
        "priority_reason",
        "sla_status",
        "sla_category",
        "complaint_severity",
        "ticket_severity",
        "ticket_status",
        "complaint_status"
    ]
    if col in ai_df.columns
]

def build_reason(row):
    parts = []

    priority_reason = safe_value(
        row, "priority_reason", default=""
    )

    if priority_reason:
        parts.append(priority_reason)

    if safe_flag(row, "sla_breached_flag", "sla_breach_flag"):
        parts.append("SLA breach")

    if safe_flag(row, "near_breach_flag", "sla_near_breach_flag"):
        parts.append("Near SLA breach")

    severity = safe_value(
        row, "complaint_severity", default=""
    )
    if severity and severity.lower() not in {"not available", "none", "low"}:
        parts.append(f"Complaint severity: {severity}")

    ticket_severity_value = safe_value(
        row, "ticket_severity", default=""
    )
    if ticket_severity_value and ticket_severity_value.lower() not in {
        "not available", "none", "low"
    }:
        parts.append(f"Ticket severity: {ticket_severity_value}")

    if safe_flag(row, "escalation_flag", "ticket_escalation_flag"):
        parts.append("Escalation flagged")

    return "; ".join(dict.fromkeys(parts)) or (
        "Priority assigned by Section 14 rules; review case indicators."
    )


ai_df["ai_prompt_reason"] = ai_df.apply(build_reason, axis=1)

ai_support_prompts = ai_df.loc[
    priority_mask,
    [
        "request_id",
        "request_priority",
        "ai_prompt_reason",
        "recommended_action",
        "ai_support_prompt"
    ]
].copy()

ai_support_prompts = ai_support_prompts.rename(
    columns={"ai_prompt_reason": "reason"}
).reset_index(drop=True)


assert len(ai_df) == len(final_feature_df), (
    "Row count changed during prompt generation."
)

assert ai_df["request_id"].is_unique, (
    "Duplicate request IDs found in the final table."
)

assert ai_df.loc[
    ~priority_mask, "ai_support_prompt"
].eq("").all(), (
    "Prompts should only be generated for P0, P1 and P2."
)

assert ai_df.loc[
    priority_mask, "ai_support_prompt"
].str.strip().ne("").all(), (
    "A P0/P1/P2 case has an empty prompt."
)

final_feature_df = ai_df.copy(deep=True)

print("SECTION 16: AI-READY SUPPORT PROMPT GENERATOR")


print("Status: PASSED")
print("External AI API calls: 0")
print(f"Total requests: {len(final_feature_df)}")
print(f"P0/P1/P2 prompts generated: {len(ai_support_prompts)}")
print(
    "Prompts generated for other priorities:",
    int((~priority_mask).sum() * 0)
)

print("\nPrompt count by priority:")
display(
    ai_support_prompts.groupby("request_priority")
    .size()
    .reindex(["P0", "P1", "P2"], fill_value=0)
    .rename("prompt_count")
    .reset_index()
)

print("\nVisible AI support prompt review table:")
display(ai_support_prompts.head(10))

print("\nSection 16 validation completed successfully.")

SECTION 16: AI-READY SUPPORT PROMPT GENERATOR
Status: PASSED
External AI API calls: 0
Total requests: 4992
P0/P1/P2 prompts generated: 4401
Prompts generated for other priorities: 0

Prompt count by priority:

  request_priority  prompt_count
0               P0          1956
1               P1          2418
2               P2            27

Visible AI support prompt review table:

,request_id,request_priority,reason,recommended_action,ai_support_prompt
0,REQ0000009,P1,Request SLA breached; Request or ticket remain...,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
1,REQ0000010,P1,Request SLA breached; Request or ticket remain...,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
2,REQ0000012,P0,Request SLA breached; Ticket SLA breached; Esc...,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...
3,REQ0000013,P1,Request SLA breached,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
4,REQ0000014,P2,Moderate complaint severity; Repeated customer...,"Review the customer's previous complaints, ide...",ROLE:\nYou are a professional customer-support...
5,REQ0000015,P1,Request SLA breached; SLA near breach or delay...,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
6,REQ0000016,P0,Request SLA breached; Ticket SLA breached; Esc...,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...
7,REQ0000017,P0,Request SLA breached; Severe complaint; Angry/...,Immediate manager callback; assign the Grievan...,ROLE:\nYou are a professional customer-support...
8,REQ0000018,P1,Request SLA breached,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
9,REQ0000019,P1,Request SLA breached; Request or ticket remain...,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...

Section 16 validation completed successfully.

### Expected Output — Section 16: AI-Ready Support Prompt Generator

**Datasets to use:**

- Final report table with priority, SLA, complaint, ticket, and recommended action columns.

**How to approach:**

- Generate prompts only for `P0`, `P1`, and `P2` cases.
- The prompt should help a support executive draft a customer response.
- Do not include unnecessary personal information such as full customer name if not required.
- Keep prompts professional and safe: no false promises, no confidential details, no unsupported claims.
- Do not call an external AI API.

**Expected output format:**

Create a column:

| Column | Meaning |
|---|---|
| `ai_support_prompt` | Structured prompt for an AI assistant |

Also create a visible `ai_support_prompts` table with request ID, priority, reason, recommended action, and prompt text.

**Hint:** The output prompt is part of the product. The AI prompt usage log is a separate deliverable that explains how you used AI while building the notebook.

In [ ]:
import pandas as pd
import IPython
import ipywidgets as widgets

from IPython.display import display, clear_output


if "final_feature_df" not in globals():
    raise NameError(
        "final_feature_df not found. Run Sections 13-16 first."
    )

if not isinstance(final_feature_df, pd.DataFrame):
    raise TypeError("final_feature_df must be a pandas DataFrame.")

gui_df = final_feature_df.copy(deep=True)

if "request_id" not in gui_df.columns:
    raise KeyError("The final report must contain request_id.")

preferred_columns = [
    "request_id",
    "customer_id",
    "customer_segment",
    "request_category",
    "request_subcategory",
    "request_status",
    "request_priority",
    "priority_reason",
    "recommended_action",
    "sla_status",
    "sla_category",
    "complaint_severity",
    "complaint_count",
    "ticket_severity",
    "ticket_status",
    "assigned_team",
    "assigned_team_ticket",
    "branch_id",
    "branch_name",
    "branch_city",
    "branch_state",
    "branch_zone",
    "branch_type",
    "customer_impact_score",
    "customer_impact_level",
    "ai_support_prompt"
]

display_columns = [
    col for col in preferred_columns if col in gui_df.columns
]

if "request_id" not in display_columns:
    display_columns.insert(0, "request_id")

def available_values(column):
    """Return sorted non-empty filter values."""
    if column not in gui_df.columns:
        return []

    values = (
        gui_df[column]
        .dropna()
        .astype(str)
        .str.strip()
    )

    values = values[
        (values != "")
        & (~values.str.lower().isin(["nan", "none", "<na>"]))
    ]

    return sorted(values.unique().tolist(), key=str.casefold)


def make_options(column, include_all=True):
    values = available_values(column)

    if include_all:
        return [("All", "__ALL__")] + [
            (value, value) for value in values
        ]

    return [(value, value) for value in values]


def normalize_for_search(series):
    return series.astype("string").fillna("").str.strip().str.casefold()

request_id_input = widgets.Text(
    value="",
    placeholder="Enter a request ID",
    description="Request ID:",
    layout=widgets.Layout(width="48%"),
    style={"description_width": "100px"}
)

customer_id_input = widgets.Text(
    value="",
    placeholder="Enter a customer ID",
    description="Customer ID:",
    layout=widgets.Layout(width="48%"),
    style={"description_width": "100px"}
)

priority_filter = widgets.Dropdown(
    options=make_options("request_priority"),
    value="__ALL__",
    description="Priority:",
    layout=widgets.Layout(width="48%"),
    style={"description_width": "100px"}
)

status_filter = widgets.Dropdown(
    options=make_options("request_status"),
    value="__ALL__",
    description="Request status:",
    layout=widgets.Layout(width="48%"),
    style={"description_width": "100px"}
)

category_filter = widgets.Dropdown(
    options=make_options("request_category"),
    value="__ALL__",
    description="Category:",
    layout=widgets.Layout(width="48%"),
    style={"description_width": "100px"}
)

branch_zone_filter = widgets.Dropdown(
    options=make_options("branch_zone"),
    value="__ALL__",
    description="Branch zone:",
    layout=widgets.Layout(width="48%"),
    style={"description_width": "100px"}
)

team_column = (
    "assigned_team_ticket"
    if "assigned_team_ticket" in gui_df.columns
    else "assigned_team"
)

team_filter = widgets.Dropdown(
    options=make_options(team_column),
    value="__ALL__",
    description="Assigned team:",
    layout=widgets.Layout(width="48%"),
    style={"description_width": "100px"}
)

limit_filter = widgets.Dropdown(
    options=[
        ("25 records", 25),
        ("50 records", 50),
        ("100 records", 100),
        ("All matching records", 0)
    ],
    value=25,
    description="Display limit:",
    layout=widgets.Layout(width="48%"),
    style={"description_width": "100px"}
)

search_button = widgets.Button(
    description="Search / Apply Filters",
    button_style="primary",
    icon="search",
    tooltip="Search service requests using the selected criteria"
)

reset_button = widgets.Button(
    description="Reset Filters",
    button_style="",
    icon="refresh",
    tooltip="Clear search fields and reset filters"
)

output = widgets.Output(
    layout=widgets.Layout(
        width="100%",
        max_height="650px",
        overflow="auto"
    )
)

def run_search(_=None):
    with output:
        clear_output(wait=True)

        filtered_df = gui_df.copy(deep=True)

        request_query = request_id_input.value.strip()
        customer_query = customer_id_input.value.strip()

        if request_query:
            request_values = normalize_for_search(
                filtered_df["request_id"]
            )

            filtered_df = filtered_df.loc[
                request_values == request_query.casefold()
            ]

        if customer_query:
            if "customer_id" not in filtered_df.columns:
                display(widgets.HTML(
                    "<b>Customer ID search is unavailable:</b> "
                    "the final report has no customer_id column."
                ))
                return

            customer_values = normalize_for_search(
                filtered_df["customer_id"]
            )

            filtered_df = filtered_df.loc[
                customer_values == customer_query.casefold()
            ]

        filter_config = [
            ("request_priority", priority_filter.value),
            ("request_status", status_filter.value),
            ("request_category", category_filter.value),
            ("branch_zone", branch_zone_filter.value),
            (team_column, team_filter.value)
        ]

        for column, selected_value in filter_config:
            if selected_value == "__ALL__":
                continue

            if column not in filtered_df.columns:
                continue

            filtered_df = filtered_df.loc[
                filtered_df[column]
                .astype("string")
                .fillna("")
                .str.strip()
                == selected_value
            ]

        if filtered_df.empty:
            display(widgets.HTML(
                "<div style='padding:10px; color:#b42318;'>"
                "<b>No matching service requests found.</b>"
                "<br>Check the request/customer ID or relax your filters."
                "</div>"
            ))
            return

        display(widgets.HTML(
            f"<b>Matching service requests: {len(filtered_df):,}</b>"
        ))

        columns_to_show = [
            col for col in display_columns
            if col in filtered_df.columns
        ]

        result_df = filtered_df[columns_to_show].copy()

        for col in result_df.columns:
            if pd.api.types.is_datetime64_any_dtype(result_df[col]):
                result_df[col] = result_df[col].dt.strftime("%Y-%m-%d")
                result_df[col] = result_df[col].fillna("")

        display_limit = limit_filter.value

        if display_limit:
            result_to_display = result_df.head(display_limit)
        else:
            result_to_display = result_df

        display(
            result_to_display.style
            .hide(axis="index")
            .set_properties(**{
                "text-align": "left",
                "white-space": "normal",
                "max-width": "350px"
            })
        )

        if display_limit and len(result_df) > display_limit:
            print(
                f"\nShowing {display_limit} of {len(result_df)} "
                "matching records. Increase the display limit to see more."
            )

def reset_filters(_=None):
    request_id_input.value = ""
    customer_id_input.value = ""
    priority_filter.value = "__ALL__"
    status_filter.value = "__ALL__"
    category_filter.value = "__ALL__"
    branch_zone_filter.value = "__ALL__"
    team_filter.value = "__ALL__"
    limit_filter.value = 25

    with output:
        clear_output(wait=True)
        display(widgets.HTML(
            "Filters reset. Enter an ID or choose filters, then click "
            "<b>Search / Apply Filters</b>."
        ))


search_button.on_click(run_search)
reset_button.on_click(reset_filters)

header = widgets.HTML(
    """
    <div style="padding:12px 0;">
      <h3>Service Request Resolution Explorer</h3>
      <p>Search a request or customer, or combine filters to investigate
      cases. This interface does not modify the master dataset.</p>
    </div>
    """
)

search_row = widgets.HBox(
    [request_id_input, customer_id_input],
    layout=widgets.Layout(flex_flow="row wrap", width="100%")
)

filter_row_1 = widgets.HBox(
    [priority_filter, status_filter],
    layout=widgets.Layout(flex_flow="row wrap", width="100%")
)

filter_row_2 = widgets.HBox(
    [category_filter, branch_zone_filter],
    layout=widgets.Layout(flex_flow="row wrap", width="100%")
)

filter_row_3 = widgets.HBox(
    [team_filter, limit_filter],
    layout=widgets.Layout(flex_flow="row wrap", width="100%")
)

button_row = widgets.HBox([search_button, reset_button])

gui = widgets.VBox([
    header,
    search_row,
    filter_row_1,
    filter_row_2,
    filter_row_3,
    button_row,
    output
], layout=widgets.Layout(width="100%"))

display(gui)

with output:
    display(widgets.HTML(
        "Enter a request ID or customer ID, or select filters, "
        "then click <b>Search / Apply Filters</b>."
    ))

assert len(gui_df) == len(final_feature_df), (
    "GUI snapshot row count differs from the master table."
)

print("Section 17 setup: PASSED")
print(f"Records available to search: {len(gui_df):,}")
print(f"Business-readable columns available: {len(display_columns)}")
print("Master dataset modified: No")

VBox(children=(HTML(value='\n    <div style="padding:12px 0;">\n      <h3>Service Request Resolution Explorer<…

Section 17 setup: PASSED
Records available to search: 4,992
Business-readable columns available: 25
Master dataset modified: No

### Expected Output — Section 17: Colab Customer/Request Search and Filter GUI

**Datasets to use:**

- Final service request resolution report DataFrame.

**How to approach:**

- Use `ipywidgets` for a simple Colab interface.
- Provide request ID and customer ID search.
- Provide filters for priority, request status, category, branch zone, and/or assigned team.
- Handle invalid request IDs and empty filters with friendly messages.
- Display only business-readable columns in the GUI output.

**Expected output format:**

The GUI should allow an operations user to:

| User Action | Expected Result |
|---|---|
| Enter valid request ID | Shows service request case summary |
| Enter invalid request ID | Shows friendly `No matching service requests found` message |
| Select priority filter | Shows matching priority cases |
| Select multiple filters | Shows filtered records without modifying master dataset |

**Hint:** Keep the GUI simple. This is not a web app. It only needs to work inside Colab without editing backend variables.

In [ ]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

if "final_feature_df" not in globals():
    raise NameError(
        "final_feature_df not found. Run Sections 13-16 first."
    )

if not isinstance(final_feature_df, pd.DataFrame):
    raise TypeError("final_feature_df must be a pandas DataFrame.")

OUTPUT_DIR = Path("hdfc_service_request_outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

final_service_request_resolution_report = (
    final_feature_df.copy(deep=True)
)

print("=" * 75)
print("SECTION 18: REPORT EXPORT AND REPORT PREVIEW")
print("=" * 75)
print(f"Output directory: {OUTPUT_DIR.resolve()}")
print(
    "Final report rows:",
    len(final_service_request_resolution_report)
)

def find_dataframe(*candidate_names):
    """Return the first available DataFrame from candidate names."""
    for name in candidate_names:
        obj = globals().get(name)

        if isinstance(obj, pd.DataFrame):
            return obj.copy(deep=True)

    return None


def find_first_column(df, candidates):
    """Find the first matching column name."""
    for column in candidates:
        if column in df.columns:
            return column
    return None


def as_bool(series):
    """Convert common boolean, numeric, and text flags safely."""
    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False)

    if pd.api.types.is_numeric_dtype(series):
        return pd.to_numeric(series, errors="coerce").eq(1)

    return (
        series.astype("string")
        .fillna("")
        .str.strip()
        .str.lower()
        .isin(["true", "1", "yes", "y", "flagged", "breached"])
    )


def preview_report(report_name, report_df, max_rows=10):
    """Display a concise notebook preview."""
    display(Markdown(f"### {report_name}"))
    print(f"Rows: {len(report_df):,} | Columns: {len(report_df.columns)}")

    if report_df.empty:
        print("No matching records in this report.")
    else:
        display(report_df.head(max_rows))

sla_source = find_dataframe(
    "service_request_sla_analysis",
    "sla_analysis_df",
    "sla_analysis"
)

if sla_source is None:
    sla_source = final_service_request_resolution_report.copy(deep=True)

sla_breach_report = sla_source.copy(deep=True)

breach_flag_col = find_first_column(
    sla_breach_report,
    ["sla_breached_flag", "sla_breach_flag", "sla_breached"]
)

sla_status_col = find_first_column(
    sla_breach_report,
    ["sla_status", "sla_category", "sla_breach_risk"]
)

if breach_flag_col:
    breach_mask = as_bool(sla_breach_report[breach_flag_col])
elif sla_status_col:
    breach_mask = (
        sla_breach_report[sla_status_col]
        .astype("string")
        .fillna("")
        .str.lower()
        .str.contains(r"breach|overdue|missed", regex=True)
    )
else:
    breach_mask = pd.Series(
        False, index=sla_breach_report.index
    )
    print(
        "WARNING: No SLA breach indicator found. "
        "sla_breach_report will contain zero rows rather than "
        "guessing which requests breached SLA."
    )

sla_breach_report = sla_breach_report.loc[breach_mask].copy()

branch_issue_summary = find_dataframe(
    "branch_issue_summary",
    "branch_summary",
    "branch_analysis_summary"
)

if branch_issue_summary is None:
    branch_issue_summary = pd.DataFrame(
        columns=[
            "branch_id", "branch_name", "branch_city",
            "total_requests", "sla_breach_rate",
            "pending_rate", "branch_risk_score"
        ]
    )
    print(
        "WARNING: Branch issue summary was not found. "
        "Run Section 9 to populate it."
    )


category_status_summary = find_dataframe(
    "category_status_summary",
    "category_summary",
    "request_category_status_summary"
)

if category_status_summary is None:
    category_col = find_first_column(
        final_service_request_resolution_report,
        ["request_category"]
    )
    status_col = find_first_column(
        final_service_request_resolution_report,
        ["request_status"]
    )

    if category_col and status_col:
        category_status_summary = (
            final_service_request_resolution_report
            .groupby(
                [category_col, status_col],
                dropna=False
            )
            .size()
            .reset_index(name="request_count")
        )
    else:
        category_status_summary = pd.DataFrame(
            columns=[
                "request_category", "request_status", "request_count"
            ]
        )
        print(
            "WARNING: Category/status fields unavailable; "
            "the summary could not be derived."
        )


pending_source = final_service_request_resolution_report.copy(deep=True)

status_col = find_first_column(
    pending_source,
    ["request_status", "current_status", "status"]
)

if status_col:
    pending_status = (
        pending_source[status_col]
        .astype("string")
        .fillna("")
        .str.strip()
        .str.lower()
    )

    pending_mask = pending_status.isin([
        "open", "pending", "in progress", "in_progress",
        "in review", "in_review", "reopened", "escalated",
        "awaiting customer", "awaiting_customer",
        "on hold", "on_hold"
    ])

    pending_request_report = pending_source.loc[
        pending_mask
    ].copy()
else:
    pending_request_report = pd.DataFrame(
        columns=pending_source.columns
    )
    print(
        "WARNING: No request status column found. "
        "Pending request report contains zero rows."
    )


if "request_priority" in final_service_request_resolution_report.columns:
    priorities = (
        final_service_request_resolution_report["request_priority"]
        .astype("string")
        .str.strip()
        .str.upper()
    )

    p0_p1_priority_cases = (
        final_service_request_resolution_report.loc[
            priorities.isin(["P0", "P1"])
        ].copy()
    )
else:
    p0_p1_priority_cases = pd.DataFrame(
        columns=final_service_request_resolution_report.columns
    )
    print("WARNING: request_priority column is unavailable.")


ai_support_prompts = find_dataframe("ai_support_prompts")

if ai_support_prompts is None:
    if "ai_support_prompt" in final_service_request_resolution_report.columns:
        ai_source = final_service_request_resolution_report.copy()

        priority_col = find_first_column(
            ai_source, ["request_priority"]
        )

        if priority_col:
            ai_priority = (
                ai_source[priority_col]
                .astype("string")
                .str.strip()
                .str.upper()
            )

            ai_source = ai_source.loc[
                ai_priority.isin(["P0", "P1", "P2"])
            ].copy()

        selected_columns = [
            col for col in [
                "request_id",
                "request_priority",
                "priority_reason",
                "recommended_action",
                "ai_support_prompt"
            ]
            if col in ai_source.columns
        ]

        ai_support_prompts = ai_source[selected_columns].copy()

        if "priority_reason" in ai_support_prompts.columns:
            ai_support_prompts = ai_support_prompts.rename(
                columns={"priority_reason": "reason"}
            )
    else:
        ai_support_prompts = pd.DataFrame(
            columns=[
                "request_id", "request_priority", "reason",
                "recommended_action", "ai_support_prompt"
            ]
        )
        print(
            "WARNING: AI prompt column unavailable. "
            "Run Section 16 to generate prompts."
        )

data_validation_report = find_dataframe(
    "data_validation_report",
    "validation_report",
    "validation_results",
    "data_quality_report",
    "section6_validation_report",
    "validation_summary"
)

if data_validation_report is None:
    data_validation_report = pd.DataFrame([{
        "check_name": "Section 18 source availability",
        "status": "REVIEW REQUIRED",
        "details": (
            "No existing data validation report DataFrame was found. "
            "Run the data validation section and export its actual results."
        )
    }])
    print(
        "WARNING: No prior validation report DataFrame found. "
        "A review-required notice will be exported."
    )



debug_fix_log_df = find_dataframe(
    "debug_fix_log_df",
    "debug_log_df",
    "debug_log",
    "debug_fix_log",
    "debug_fix_log_table"
)

if debug_fix_log_df is None:

    debug_fix_log_df = pd.DataFrame([{
        "issue_id": "LOG-REVIEW",
        "code_section": "Section 18",
        "issue_type": "Missing source log",
        "issue_description": (
            "No existing debug fix log DataFrame was found in the session."
        ),
        "root_cause": "Expected log variable unavailable",
        "fix_summary": (
            "Locate the notebook's actual debug log and rerun Section 18."
        ),
        "tested_status": "REVIEW REQUIRED",
        "remarks": "This is a notice, not a historical bug-fix record."
    }])
    print(
        "WARNING: Debug fix log not found. "
        "A review-required notice will be exported."
    )


service_request_health_summary = find_dataframe(
    "service_request_health_summary",
    "request_health_summary",
    "health_summary"
)

if service_request_health_summary is None:
    health_source = final_service_request_resolution_report
    health_rows = []

    health_rows.append({
        "metric": "total_requests",
        "value": len(health_source)
    })

    if "request_status" in health_source.columns:
        status = (
            health_source["request_status"]
            .astype("string")
            .fillna("")
            .str.lower()
        )

        health_rows.extend([
            {
                "metric": "pending_requests",
                "value": int(status.isin([
                    "open", "pending", "in progress", "in_progress",
                    "reopened", "escalated", "in review", "in_review"
                ]).sum())
            },
            {
                "metric": "resolved_requests",
                "value": int(status.isin([
                    "resolved", "closed", "completed"
                ]).sum())
            }
        ])

    if "request_priority" in health_source.columns:
        priority_values = (
            health_source["request_priority"]
            .astype("string")
            .str.upper()
        )

        for priority in ["P0", "P1", "P2", "P3", "NO ISSUE"]:
            health_rows.append({
                "metric": f"priority_{priority.lower().replace(' ', '_')}",
                "value": int((priority_values == priority).sum())
            })

    service_request_health_summary = pd.DataFrame(health_rows)



reports = {
    "final_service_request_resolution_report":
        final_service_request_resolution_report,

    "sla_breach_report":
        sla_breach_report,

    "branch_issue_summary":
        branch_issue_summary,

    "category_status_summary":
        category_status_summary,

    "pending_request_report":
        pending_request_report,

    "p0_p1_priority_cases":
        p0_p1_priority_cases,

    "ai_support_prompts":
        ai_support_prompts,

    "data_validation_report":
        data_validation_report,

    "debug_fix_log_df":
        debug_fix_log_df,

    "service_request_health_summary":
        service_request_health_summary
}


export_results = []

for report_name, report_df in reports.items():

    if not isinstance(report_df, pd.DataFrame):
        print(
            f"WARNING: {report_name} is not a DataFrame; "
            "skipping export."
        )
        continue

    export_df = report_df.copy(deep=True).reset_index(drop=True)

    output_path = OUTPUT_DIR / f"{report_name}.csv"

    export_df.to_csv(
        output_path,
        index=False,
        encoding="utf-8-sig"
    )

    if not output_path.exists():
        raise IOError(f"Export failed: {output_path}")

    export_results.append({
        "report_variable": report_name,
        "file_name": output_path.name,
        "row_count": len(export_df),
        "column_count": len(export_df.columns),
        "export_status": "PASSED",
        "file_size_bytes": output_path.stat().st_size
    })

    preview_report(report_name, export_df, max_rows=10)


export_manifest = pd.DataFrame(export_results)

manifest_path = OUTPUT_DIR / "report_export_manifest.csv"
export_manifest.to_csv(
    manifest_path,
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 75)
print("REPORT EXPORT SUMMARY")
print("=" * 75)

display(export_manifest)

print(f"\nReports exported: {len(export_manifest)}")
print(f"Output folder: {OUTPUT_DIR.resolve()}")
print(f"Manifest: {manifest_path.name}")

if len(export_manifest) == 10 and (
    export_manifest["export_status"] == "PASSED"
).all():
    print("Section 18 export checks: PASSED")
else:
    print(
        "Section 18 export checks: REVIEW REQUIRED — "
        "check the manifest and warnings above."
    )

print(
    "\nNote: Any REVIEW REQUIRED placeholder reports must be replaced "
    "with the actual upstream report before final submission."
)

===========================================================================
SECTION 18: REPORT EXPORT AND REPORT PREVIEW
===========================================================================
Output directory: /content/hdfc_service_request_outputs
Final report rows: 4992

### final_service_request_resolution_report

Rows: 4,992 | Columns: 76

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,customer_name,customer_segment,account_type,relationship_age_days,preferred_branch_id,branch_name,branch_city,branch_state,branch_zone,branch_type,sla_status,elapsed_hours,complaint_count,customer_complaint_count,complaint_status,complaint_type,sentiment_tag,complaint_severity,repeated_complaint_flag,reopened_complaint_flag,angry_complaint_flag,unresolved_complaint_flag,ticket_count,ticket_status,assigned_team_ticket,escalation_flag,max_ticket_age_hours,ticket_severity,ticket_issue_tag,ticket_sla_breached_flag,ticket_delay_warning_flag,slow_resolution_flag,duplicate_suspected,duplicate_group_key,duplicate_reason,duplicate_id_flag,same_day_repeat_flag,recurring_issue_flag,unresolved_repeat_count,status_update_count,last_update_date,latest_status_from_update,reassignment_count,total_requests,pending_requests,sla_breaches,branch_risk_score,near_sla_breaches,avg_elapsed_hours,pending_rate_pct,sla_breach_rate_pct,near_breach_rate_pct,request_priority,priority_reason,customer_impact_score,customer_impact_level,recommended_action,ai_support_prompt,ai_prompt_reason
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,Vikram Khan,Corporate,Savings,499,BR0574,HDFC Jodhpur Service Branch 0566,Jodhpur,Rajasthan,North,Urban,Breached,1536.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,10.0,6.0,8.0,58.00,0.0,1243.200000,60.000000,80.000000,0.000000,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
1,REQ0000010,CUST000649,BR0980,2026-05-17,22:31:00,Card,Failed ATM Withdrawal,WhatsApp,pending_customer,36,Cards Operations,24383.2,2026-05-18,NaT,False,False,False,Vivaan Mehta,Corporate,NRI Savings,3430,BR0458,HDFC Kozhikode Service Branch 0980,Kozhikode,Kerala,South,Metro,Breached,1056.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,9.0,5.0,6.0,50.00,0.0,1157.333333,55.555556,66.666667,0.000000,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
2,REQ0000011,CUST000817,BR0045,2026-06-19,04:47:00,Digital Banking,NetBanking Login,Email,closed,24,Digital Banking Support,193459.78,2026-06-19,2026-06-19,False,False,False,Vivaan Agarwal,Senior Citizen,Current,872,BR0509,HDFC Noida Service Branch 0045,Noida,Delhi NCR,North,Semi-Urban,Within SLA,0.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,1,2026-07-01,resolved,0,5.0,2.0,3.0,46.00,1.0,720.000000,40.000000,60.000000,20.000000,No Issue,"No identified SLA, complaint, escalation, or r...",0,Low,No immediate action required; continue standar...,,"No identified SLA, complaint, escalation, or r..."
3,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,Reyansh Malhotra,NRI,Savings,2590,BR0622,HDFC Hyderabad Service Branch 0335,Hyderabad,Telangana,South,Rural,Breached,1704.0,0,0,No Complaint,None,None,None,False,False,False,False,1,open,Customer Care,False,1704.0,Severe,Ticket SLA Breach; Active Ticket,True,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,1.0,2.0,32.50,0.0,456.000000,25.000000,50.000000,0.000000,P0,Request SLA breached; Ticket SLA breached; Esc...,75,High,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Ticket SLA breached; Esc...
4,REQ0000013,CUST001137,BR0081,2026-06-13,07:18:00,Account,Balance Mismatch,NetBanking,closed,48,Account Servicing,<NA>,2026-06-16,2026-06-16,False,False,False,Saanvi Iyer,Corporate,Loan Account,950,BR0144,HDFC Kochi Service Branch 0081,Kochi,Kerala,South,Urban,Breached,72.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,5.0,0.0,1.0,14.00,1.0,38.400000,0.000000,20.000000,20.000000,P1,Request SLA breached,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached
5,REQ0000014,CUST000892,BR0091,2026-04-25,06:03:00,KYC,Document Rejected,Call Center,closed,72,KYC Operations,<NA>,2026-04-26,2026-04-26,False,False,False,Aditya Chopra,Senior Citizen,Salary,801,BR0772,HDFC Mysuru Service Branch 0091,Mysuru,Karnataka,South,Semi-Urban,Within SLA,24.0,1,2,resolved,loan_servicing,neutral,Moderate,True,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,3.0,2.0,2.0,53.33,0.0,1616.000000,66.666667,66.666667,0.000000,P2,Moderate complaint severity; Repeated customer...,20,Low,"Review the customer's previous complaints, ide...",ROLE:\nYou are a professional customer-support...,Moderate complaint severity; Repeated customer...
6,REQ0000015,CUST001118,BR0262,2026-02-22,19:15:00,Account,Account Freeze,Email,resolved,48,Account Servicing,<NA>,2026-02-25,2026-02-24,False,False,False,Sai Bhat,Preferred,NRI Savings,3178,BR0894,HDFC Coimbatore Service Branch 0262,Coimbatore,TAMIL NADU,South,Metro,Near Breach,48.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,7.0,2.0,4.0,40.00,1.0,466.285714,28.571429,57.142857,14.285714,P1,Request SLA breached; SLA near breach or delay...,45,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; SLA near breach or delay...
7,REQ0000016,CUST000669,BR0422,2026-05-25,15:46:00,Account,Account Freeze,Branch,resolved,48,Account Servicing,<NA>,2026-05-27,2026-05-27,False,False,False,Saanvi Nair,Preferred,NRI Savings,884,BR0874,HDFC Lucknow Service Branch 0422,Lucknow,Uttar Pradesh,North,Rural,Near Breach,48.0,0,0,No Complaint,None,None,None,False,False,False,False,1,open,Grievance Desk,False,744.0,Severe,Ticket SLA Breach; Active Ticket,True,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,6.0,3.0,4.0,51.67,1.0,1272.000000,50.000000,66.666667,16.666667,P0,Request SLA breached; Ticket SLA breached; Esc...,90,Critical,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Ticket SLA breached; Esc...
8,REQ0000017,CUST000492,BR0179,2026-04-21,18:52:00,Digital Banking,NetBanking Login,WhatsApp,pending_customer,24,Digital Banking Support,158525.74,2026-04-22,NaT,False,False,False,Dev Singh,Student,Savings,811,BR0121,HDFC Thiruvananthapuram Service Branch 0179,Thiruvananthapuram,Kerala,South,Digital Service Hub,Breached,1680.0,1,3,in_review,sla_delay,negative,Severe,True,False,True,True,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,2.0,3.0,52.50,0.0,558.000000,50.000000,75.000000,0.000000,P0,Request SLA breached; Severe complaint; Angry/...,100,Critical,Immediate manager callback; assign the Grievan...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Severe complaint; Angry/...
9,REQ0000018,CUST000133,BR0198,2026-04-24,02:08:00,Complaint,Fraud Concern,WhatsApp,resolved,72,Customer Grievance,13453.42,2026-04-28,2026-04-28,False,False,False,Navya Sharma,Senior Citizen,NRI Savings,199,BR0587,HDFC Salem Service Branch 0198,Salem,Tamil Nadu,South,Digital Service Hub,Breached,96.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,12.0,7.0,9.0,56.67,1.0,1940.000000,58.333333,75.000000,8.333333,P1,Request SLA breached,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached

### sla_breach_report

Rows: 3,432 | Columns: 32

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,invalid_created_date_flag,is_resolved_or_closed,is_pending_unresolved,elapsed_time_basis,elapsed_end_date,missing_resolved_date_flag,elapsed_hours,negative_elapsed_flag,invalid_elapsed_flag,invalid_sla_flag,sla_assessable_flag,sla_breached,near_sla_breach,sla_status,category_for_summary
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,1536.0,False,False,False,True,True,False,Breached,Complaint
1,REQ0000010,CUST000649,BR0980,2026-05-17,22:31:00,Card,Failed ATM Withdrawal,WhatsApp,pending_customer,36,Cards Operations,24383.2,2026-05-18,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,1056.0,False,False,False,True,True,False,Breached,Card
2,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,1704.0,False,False,False,True,True,False,Breached,Complaint
3,REQ0000013,CUST001137,BR0081,2026-06-13,07:18:00,Account,Balance Mismatch,NetBanking,closed,48,Account Servicing,<NA>,2026-06-16,2026-06-16,False,False,False,False,True,False,resolved_date,2026-06-16,False,72.0,False,False,False,True,True,False,Breached,Account
4,REQ0000017,CUST000492,BR0179,2026-04-21,18:52:00,Digital Banking,NetBanking Login,WhatsApp,pending_customer,24,Digital Banking Support,158525.74,2026-04-22,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,1680.0,False,False,False,True,True,False,Breached,Digital Banking
5,REQ0000018,CUST000133,BR0198,2026-04-24,02:08:00,Complaint,Fraud Concern,WhatsApp,resolved,72,Customer Grievance,13453.42,2026-04-28,2026-04-28,False,False,False,False,True,False,resolved_date,2026-04-28,False,96.0,False,False,False,True,True,False,Breached,Complaint
6,REQ0000019,CUST001087,BR0469,2026-04-25,06:45:00,Account,Account Freeze,NetBanking,pending_customer,48,Account Servicing,<NA>,2026-04-29,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,1584.0,False,False,False,True,True,False,Breached,Account
7,REQ0000020,CUST000348,BR0426,2026-05-18,23:33:00,Card,PIN Reset,Branch,in_progress,36,Cards Operations,44625.89,2026-05-19,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,1032.0,False,False,False,True,True,False,Breached,Card
8,REQ0000022,CUST000988,BR0051,2026-06-09,17:45:00,Account,Address Change,Branch,closed,48,Account Servicing,<NA>,2026-06-13,2026-06-13,False,False,False,False,True,False,resolved_date,2026-06-13,False,96.0,False,False,False,True,True,False,Breached,Account
9,REQ0000023,CUST000455,BR0653,2026-02-11,06:38:00,KYC,CKYC Pending,Branch,open,72,KYC Operations,<NA>,2026-02-14,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,3336.0,False,False,False,True,True,False,Breached,KYC

### branch_issue_summary

Rows: 1,000 | Columns: 13

,branch_id,branch_name,branch_city,branch_zone,total_requests,pending_requests,sla_breaches,branch_risk_score,near_sla_breaches,avg_elapsed_hours,pending_rate_pct,sla_breach_rate_pct,near_breach_rate_pct
0,BR0002,HDFC Kanpur Service Branch 0002,Kanpur,North,3,3,3,80.0,0,2744.0,100.0,100.0,0.0
1,BR0978,HDFC Nagpur Service Branch 0978,Nagpur,West,2,2,2,80.0,0,2652.0,100.0,100.0,0.0
2,BR0976,HDFC Noida Service Branch 0976,Noida,North,4,4,4,80.0,0,2298.0,100.0,100.0,0.0
3,BR0453,HDFC Varanasi Service Branch 0453,Varanasi,North,1,1,1,80.0,0,264.0,100.0,100.0,0.0
4,BR0462,HDFC Noida Service Branch 0462,Noida,North,3,3,3,80.0,0,2872.0,100.0,100.0,0.0
5,BR0037,HDFC Rajkot Service Branch 0037,Rajkot,West,2,2,2,80.0,0,3948.0,100.0,100.0,0.0
6,BR0048,HDFC Noida Service Branch 0048,Noida,North,3,3,3,80.0,0,2800.0,100.0,100.0,0.0
7,BR0482,HDFC Jaipur Service Branch 0482,Jaipur,North,2,2,2,80.0,0,2400.0,100.0,100.0,0.0
8,BR0402,HDFC Warangal Service Branch 0402,Warangal,South,1,1,1,80.0,0,1872.0,100.0,100.0,0.0
9,BR0403,HDFC Kolkata Service Branch 0403,Kolkata,East,3,3,3,80.0,0,2192.0,100.0,100.0,0.0

### category_status_summary

Rows: 36 | Columns: 6

  request_category    request_status  total_requests  pending_requests  sla_breaches  avg_elapsed_hours
0  Digital Banking       in_progress             232               232           232            2301.62
1          Account       in_progress             216               216           216            2352.56
2             Card       in_progress             215               215           214            2358.14
3              KYC       in_progress             198               198           198            2351.64
4        Complaint       in_progress             191               191           191            2128.08
5             Loan       in_progress             191               191           191            2282.89
6             Card          resolved             249                 0           115              33.29
7          Account              open             108               108           108            2203.78
8          Account  pending_customer              98                98            98            2175.67
9             Loan          resolved             258                 0            96              86.01

### pending_request_report

Rows: 2,116 | Columns: 76

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,customer_name,customer_segment,account_type,relationship_age_days,preferred_branch_id,branch_name,branch_city,branch_state,branch_zone,branch_type,sla_status,elapsed_hours,complaint_count,customer_complaint_count,complaint_status,complaint_type,sentiment_tag,complaint_severity,repeated_complaint_flag,reopened_complaint_flag,angry_complaint_flag,unresolved_complaint_flag,ticket_count,ticket_status,assigned_team_ticket,escalation_flag,max_ticket_age_hours,ticket_severity,ticket_issue_tag,ticket_sla_breached_flag,ticket_delay_warning_flag,slow_resolution_flag,duplicate_suspected,duplicate_group_key,duplicate_reason,duplicate_id_flag,same_day_repeat_flag,recurring_issue_flag,unresolved_repeat_count,status_update_count,last_update_date,latest_status_from_update,reassignment_count,total_requests,pending_requests,sla_breaches,branch_risk_score,near_sla_breaches,avg_elapsed_hours,pending_rate_pct,sla_breach_rate_pct,near_breach_rate_pct,request_priority,priority_reason,customer_impact_score,customer_impact_level,recommended_action,ai_support_prompt,ai_prompt_reason
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,Vikram Khan,Corporate,Savings,499,BR0574,HDFC Jodhpur Service Branch 0566,Jodhpur,Rajasthan,North,Urban,Breached,1536.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,10.0,6.0,8.0,58.00,0.0,1243.200000,60.000000,80.000000,0.000000,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
1,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,Reyansh Malhotra,NRI,Savings,2590,BR0622,HDFC Hyderabad Service Branch 0335,Hyderabad,Telangana,South,Rural,Breached,1704.0,0,0,No Complaint,None,None,None,False,False,False,False,1,open,Customer Care,False,1704.0,Severe,Ticket SLA Breach; Active Ticket,True,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,1.0,2.0,32.50,0.0,456.000000,25.000000,50.000000,0.000000,P0,Request SLA breached; Ticket SLA breached; Esc...,75,High,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Ticket SLA breached; Esc...
2,REQ0000020,CUST000348,BR0426,2026-05-18,23:33:00,Card,PIN Reset,Branch,in_progress,36,Cards Operations,44625.89,2026-05-19,NaT,False,False,False,Neha Patel,Senior Citizen,Current,3302,BR0063,HDFC Hyderabad Service Branch 0426,Hyderabad,Telangana,South,Digital Service Hub,Breached,1032.0,0,0,No Complaint,None,None,None,False,False,False,False,1,closed,Customer Care,True,<NA>,Severe,Escalated Case; Missing Resolution Time,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,2,2026-05-22,closed,0,7.0,6.0,7.0,75.71,0.0,1683.428571,85.714286,100.000000,0.000000,P0,Request SLA breached; Escalated or severe tick...,55,Moderate,Immediately alert the operations manager; assi...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Escalated or severe tick...
3,REQ0000023,CUST000455,BR0653,2026-02-11,06:38:00,KYC,CKYC Pending,Branch,open,72,KYC Operations,<NA>,2026-02-14,NaT,False,False,False,Amit Malhotra,Classic,Current,2936,BR0615,HDFC Noida Service Branch 0653,Noida,Uttar Pradesh,North,Semi-Urban,Breached,3336.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,1,2026-02-12,escalated,1,8.0,5.0,6.0,58.75,1.0,1602.000000,62.500000,75.000000,12.500000,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
4,REQ0000026,CUST000979,BR0338,2026-03-11,09:46:00,Account,Account Freeze,NetBanking,in_progress,48,Account Servicing,<NA>,2026-03-14,NaT,False,False,False,Amit Sharma,Imperia,Current,1845,BR0556,HDFC Rajkot Service Branch 0338,Rajkot,Gujarat,West,Urban,Breached,2664.0,1,3,open,wrong_information,negative,Severe,True,False,True,True,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,5.0,4.0,5.0,74.00,0.0,1699.200000,80.000000,100.000000,0.000000,P0,Request SLA breached; Severe complaint; Angry/...,100,Critical,Immediate manager callback; assign the Grievan...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Severe complaint; Angry/...
5,REQ0000032,CUST000866,BR0149,2026-01-30,15:08:00,Account,Statement Issue,Branch,in_progress,48,Account Servicing,<NA>,2026-02-02,NaT,False,False,False,Sai Gupta,Senior Citizen,Loan Account,506,BR0548,HDFC Hubballi Service Branch 0149,Hubballi,Karnataka,South,Digital Service Hub,Breached,3624.0,0,0,No Complaint,None,None,None,False,False,False,False,1,closed,Grievance Desk,False,<NA>,Low,Missing Resolution Time,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,1,2026-02-01,closed,0,9.0,7.0,7.0,64.44,1.0,1682.666667,77.777778,77.777778,11.111111,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
6,REQ0000034,CUST001193,BR0462,2026-01-27,03:20:00,Card,Failed ATM Withdrawal,NetBanking,in_progress,36,Cards Operations,209699.19,2026-01-28,NaT,False,False,False,Kabir Iyer,Imperia,Savings,3099,BR0047,HDFC Noida Service Branch 0462,Noida,Delhi NCR,North,Urban,Breached,3696.0,1,5,in_review,loan_servicing,neutral,Moderate,True,False,False,True,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,3.0,3.0,3.0,80.00,0.0,2872.000000,100.000000,100.000000,0.000000,P1,Request SLA breached; Moderate complaint sever...,70,High,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Moderate complaint sever...
7,REQ0000037,CUST000698,BR0629,2026-04-13,11:32:00,Complaint,Service Delay,Email,in_progress,72,Customer Grievance,27701.64,2026-04-15,NaT,False,False,False,Neha Agarwal,Classic,Current,1586,BR0408,HDFC Mysuru Service Branch 0629,Mysuru,Karnataka,South,Urban,Breached,1872.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,7.0,3.0,5.0,48.57,0.0,757.714286,42.857143,71.428571,0.000000,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
8,REQ0000039,CUST000339,BR0433,2026-03-07,16:09:00,KYC,Document Rejected,Call Center,open,72,KYC Operations,<NA>,2026-03-11,NaT,False,False,False,Aditya Iyer,Imperia,Loan Account,2659,BR0983,HDFC Hubballi Service Branch 0433,Hubballi,Karnataka,South,Metro,Breached,2760.0,1,3,escalated,refund/charge_concern,angry,Severe,True,False,True,True,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,3.0,4.0,72.50,0.0,1428.000000,75.000000,100.000000,0.000000,P0,Request SLA breached; Severe complaint; Angry/...,100,Critical,Immediate manager callback; assign the Grievan...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Severe complaint; Angry/...
9,REQ0000043,CUST000605,BR0926,2026-03-04,08:24:00,Account,Address Change,Email,in_progress,48,Account Servicing,<NA>,2026-03-06,NaT,False,False,False,Neha Bhat,Senior Citizen,Salary,1314,BR0170,HDFC Hubballi Service Branch 0926,Hubballi,Karnataka,South,Semi-Urban,Breached,2832.0,1,1,closed,loan_servicing,neutral,Low,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,9.0,3.0,5.0,40.00,1.0,920.000000,33.333333,55.555556,11.111111,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...

### p0_p1_priority_cases

Rows: 4,374 | Columns: 76

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,customer_name,customer_segment,account_type,relationship_age_days,preferred_branch_id,branch_name,branch_city,branch_state,branch_zone,branch_type,sla_status,elapsed_hours,complaint_count,customer_complaint_count,complaint_status,complaint_type,sentiment_tag,complaint_severity,repeated_complaint_flag,reopened_complaint_flag,angry_complaint_flag,unresolved_complaint_flag,ticket_count,ticket_status,assigned_team_ticket,escalation_flag,max_ticket_age_hours,ticket_severity,ticket_issue_tag,ticket_sla_breached_flag,ticket_delay_warning_flag,slow_resolution_flag,duplicate_suspected,duplicate_group_key,duplicate_reason,duplicate_id_flag,same_day_repeat_flag,recurring_issue_flag,unresolved_repeat_count,status_update_count,last_update_date,latest_status_from_update,reassignment_count,total_requests,pending_requests,sla_breaches,branch_risk_score,near_sla_breaches,avg_elapsed_hours,pending_rate_pct,sla_breach_rate_pct,near_breach_rate_pct,request_priority,priority_reason,customer_impact_score,customer_impact_level,recommended_action,ai_support_prompt,ai_prompt_reason
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,Vikram Khan,Corporate,Savings,499,BR0574,HDFC Jodhpur Service Branch 0566,Jodhpur,Rajasthan,North,Urban,Breached,1536.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,10.0,6.0,8.0,58.00,0.0,1243.200000,60.000000,80.000000,0.000000,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
1,REQ0000010,CUST000649,BR0980,2026-05-17,22:31:00,Card,Failed ATM Withdrawal,WhatsApp,pending_customer,36,Cards Operations,24383.2,2026-05-18,NaT,False,False,False,Vivaan Mehta,Corporate,NRI Savings,3430,BR0458,HDFC Kozhikode Service Branch 0980,Kozhikode,Kerala,South,Metro,Breached,1056.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,9.0,5.0,6.0,50.00,0.0,1157.333333,55.555556,66.666667,0.000000,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
2,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,Reyansh Malhotra,NRI,Savings,2590,BR0622,HDFC Hyderabad Service Branch 0335,Hyderabad,Telangana,South,Rural,Breached,1704.0,0,0,No Complaint,None,None,None,False,False,False,False,1,open,Customer Care,False,1704.0,Severe,Ticket SLA Breach; Active Ticket,True,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,1.0,2.0,32.50,0.0,456.000000,25.000000,50.000000,0.000000,P0,Request SLA breached; Ticket SLA breached; Esc...,75,High,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Ticket SLA breached; Esc...
3,REQ0000013,CUST001137,BR0081,2026-06-13,07:18:00,Account,Balance Mismatch,NetBanking,closed,48,Account Servicing,<NA>,2026-06-16,2026-06-16,False,False,False,Saanvi Iyer,Corporate,Loan Account,950,BR0144,HDFC Kochi Service Branch 0081,Kochi,Kerala,South,Urban,Breached,72.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,5.0,0.0,1.0,14.00,1.0,38.400000,0.000000,20.000000,20.000000,P1,Request SLA breached,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached
4,REQ0000015,CUST001118,BR0262,2026-02-22,19:15:00,Account,Account Freeze,Email,resolved,48,Account Servicing,<NA>,2026-02-25,2026-02-24,False,False,False,Sai Bhat,Preferred,NRI Savings,3178,BR0894,HDFC Coimbatore Service Branch 0262,Coimbatore,TAMIL NADU,South,Metro,Near Breach,48.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,7.0,2.0,4.0,40.00,1.0,466.285714,28.571429,57.142857,14.285714,P1,Request SLA breached; SLA near breach or delay...,45,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; SLA near breach or delay...
5,REQ0000016,CUST000669,BR0422,2026-05-25,15:46:00,Account,Account Freeze,Branch,resolved,48,Account Servicing,<NA>,2026-05-27,2026-05-27,False,False,False,Saanvi Nair,Preferred,NRI Savings,884,BR0874,HDFC Lucknow Service Branch 0422,Lucknow,Uttar Pradesh,North,Rural,Near Breach,48.0,0,0,No Complaint,None,None,None,False,False,False,False,1,open,Grievance Desk,False,744.0,Severe,Ticket SLA Breach; Active Ticket,True,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,6.0,3.0,4.0,51.67,1.0,1272.000000,50.000000,66.666667,16.666667,P0,Request SLA breached; Ticket SLA breached; Esc...,90,Critical,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Ticket SLA breached; Esc...
6,REQ0000017,CUST000492,BR0179,2026-04-21,18:52:00,Digital Banking,NetBanking Login,WhatsApp,pending_customer,24,Digital Banking Support,158525.74,2026-04-22,NaT,False,False,False,Dev Singh,Student,Savings,811,BR0121,HDFC Thiruvananthapuram Service Branch 0179,Thiruvananthapuram,Kerala,South,Digital Service Hub,Breached,1680.0,1,3,in_review,sla_delay,negative,Severe,True,False,True,True,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,2.0,3.0,52.50,0.0,558.000000,50.000000,75.000000,0.000000,P0,Request SLA breached; Severe complaint; Angry/...,100,Critical,Immediate manager callback; assign the Grievan...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Severe complaint; Angry/...
7,REQ0000018,CUST000133,BR0198,2026-04-24,02:08:00,Complaint,Fraud Concern,WhatsApp,resolved,72,Customer Grievance,13453.42,2026-04-28,2026-04-28,False,False,False,Navya Sharma,Senior Citizen,NRI Savings,199,BR0587,HDFC Salem Service Branch 0198,Salem,Tamil Nadu,South,Digital Service Hub,Breached,96.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,12.0,7.0,9.0,56.67,1.0,1940.000000,58.333333,75.000000,8.333333,P1,Request SLA breached,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached
8,REQ0000019,CUST001087,BR0469,2026-04-25,06:45:00,Account,Account Freeze,NetBanking,pending_customer,48,Account Servicing,<NA>,2026-04-29,NaT,False,False,False,Aditya Malhotra,Senior Citizen,NRI Savings,1831,BR0370,HDFC Nagpur Service Branch 0469,Nagpur,Maharashtra,West,Metro,Breached,1584.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,1,2026-05-02,resolved,1,7.0,2.0,4.0,40.00,1.0,456.000000,28.571429,57.142857,14.285714,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
9,REQ0000020,CUST000348,BR0426,2026-05-18,23:33:00,Card,PIN Reset,Branch,in_progress,36,Cards Operations,44625.89,2026-05-19,NaT,False,False,False,Neha Patel,Senior Citizen,Current,3302,BR0063,HDFC Hyderabad Service Branch 0426,Hyderabad,Telangana,South,Digital Service Hub,Breached,1032.0,0,0,No Complaint,None,None,None,False,False,False,False,1,closed,Customer Care,True,<NA>,Severe,Escalated Case; Missing Resolution Time,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,2,2026-05-22,closed,0,7.0,6.0,7.0,75.71,0.0,1683.428571,85.714286,100.000000,0.000000,P0,Request SLA breached; Escalated or severe tick...,55,Moderate,Immediately alert the operations manager; assi...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Escalated or severe tick...

### ai_support_prompts

Rows: 4,401 | Columns: 5

,request_id,request_priority,reason,recommended_action,ai_support_prompt
0,REQ0000009,P1,Request SLA breached; Request or ticket remain...,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
1,REQ0000010,P1,Request SLA breached; Request or ticket remain...,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
2,REQ0000012,P0,Request SLA breached; Ticket SLA breached; Esc...,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...
3,REQ0000013,P1,Request SLA breached,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
4,REQ0000014,P2,Moderate complaint severity; Repeated customer...,"Review the customer's previous complaints, ide...",ROLE:\nYou are a professional customer-support...
5,REQ0000015,P1,Request SLA breached; SLA near breach or delay...,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
6,REQ0000016,P0,Request SLA breached; Ticket SLA breached; Esc...,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...
7,REQ0000017,P0,Request SLA breached; Severe complaint; Angry/...,Immediate manager callback; assign the Grievan...,ROLE:\nYou are a professional customer-support...
8,REQ0000018,P1,Request SLA breached,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
9,REQ0000019,P1,Request SLA breached; Request or ticket remain...,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...

### data_validation_report

Rows: 60 | Columns: 7

            dataset        check_type         column_or_key  issue_count  severity  status                                            message
0  service_requests  Required Columns          All required            0  Critical  Passed                  All required columns are present.
1  service_requests     Extra Columns                     -            0   Warning  Passed                 Schema matches configured columns.
2  service_requests    Critical Nulls            request_id            0  Critical  Passed                      No missing identifier values.
3  service_requests    Critical Nulls           customer_id            0  Critical  Passed                      No missing identifier values.
4  service_requests    Critical Nulls             branch_id            0  Critical  Passed                      No missing identifier values.
5  service_requests     Duplicate IDs            request_id            0  Critical  Passed                           Primary keys are unique.
6  service_requests     Invalid Dates  request_created_date            0   Warning  Passed  No invalid non-missing dates remain in working...
7  service_requests     Invalid Dates     last_updated_date            0   Warning  Passed  No invalid non-missing dates remain in working...
8  service_requests     Invalid Dates         resolved_date            0   Warning  Passed  No invalid non-missing dates remain in working...
9           updates  Required Columns          All required            0  Critical  Passed                  All required columns are present.

### debug_fix_log_df

Rows: 1 | Columns: 8

,issue_id,code_section,issue_type,issue_description,root_cause,fix_summary,tested_status,remarks
0,BUG-001,Section 4 - Debug Log Setup,OOP,The original logging function captured only fo...,The function parameters and stored records did...,Implemented a reusable logging function with a...,Passed,No dataset required. Export will be performed ...

### service_request_health_summary

Rows: 7 | Columns: 2

                         Metric  Value
0                total_requests   4992
1   resolved_or_closed_requests   2360
2   pending_unresolved_requests   2632
3         sla_breached_requests   3432
4      near_sla_breach_requests    522
5  invalid_created_date_records      6
6     unassessable_sla_requests      8

===========================================================================
REPORT EXPORT SUMMARY
===========================================================================

                           report_variable                                    file_name  row_count  column_count export_status  file_size_bytes
0  final_service_request_resolution_report  final_service_request_resolution_report.csv       4992            76        PASSED         12186977
1                        sla_breach_report                        sla_breach_report.csv       3432            32        PASSED           881545
2                     branch_issue_summary                     branch_issue_summary.csv       1000            13        PASSED           102473
3                  category_status_summary                  category_status_summary.csv         36             6        PASSED             1354
4                   pending_request_report                   pending_request_report.csv       2116            76        PASSED          5605820
5                     p0_p1_priority_cases                     p0_p1_priority_cases.csv       4374            76        PASSED         11635090
6                       ai_support_prompts                       ai_support_prompts.csv       4401             5        PASSED          8920981
7                   data_validation_report                   data_validation_report.csv         60             7        PASSED             5909
8                         debug_fix_log_df                         debug_fix_log_df.csv          1             8        PASSED              498
9           service_request_health_summary           service_request_health_summary.csv          7             2        PASSED              217

Reports exported: 10
Output folder: /content/hdfc_service_request_outputs
Manifest: report_export_manifest.csv
Section 18 export checks: PASSED

Note: Any REVIEW REQUIRED placeholder reports must be replaced with the actual upstream report before final submission.

### Expected Output — Section 18: Report Export and Report Preview

**Datasets to use:**

- Final service request resolution report
- SLA breach report
- Branch issue summary
- Category/status summary
- Pending request report
- P0/P1 priority cases
- AI support prompts
- Data validation report
- Debug fix log
- Service request health summary

**How to approach:**

- Create the output folder before exporting.
- Use consistent file names from the PRD.
- Export CSV reports.
- Display a preview of each major report inside the notebook because the final submission is the notebook itself.

**Expected output format:**

Generate and preview these reports:

| Report Variable | Output File |
|---|---|
| `final_service_request_resolution_report` | `final_service_request_resolution_report.csv` |
| `sla_breach_report` | `sla_breach_report.csv` |
| `branch_issue_summary` | `branch_issue_summary.csv` |
| `category_status_summary` | `category_status_summary.csv` |
| `pending_request_report` | `pending_request_report.csv` |
| `p0_p1_priority_cases` | `p0_p1_priority_cases.csv` |
| `ai_support_prompts` | `ai_support_prompts.csv` |
| `data_validation_report` | `data_validation_report.csv` |
| `debug_fix_log_df` | `debug_fix_log_df.csv` |
| `service_request_health_summary` | `service_request_health_summary.csv` |

**Hint:** Even though CSV files are generated, your evaluator should be able to see report previews directly in this notebook.

In [ ]:

import pandas as pd
from pathlib import Path

# Create the required debug-log structure
debug_columns = [
    "issue_id",
    "code_section",
    "issue_type",
    "issue_description",
    "root_cause",
    "fix_summary",
    "tested_status",
    "remarks"
]

# Candidate issues based on the debugging work completed so far.
# Verify each entry against your actual code and test results.
debug_entries = [
    {
        "issue_id": "BUG-001",
        "code_section": "Section 5 - DataLoader",
        "issue_type": "Runtime / File Handling",
        "issue_description": "Excel loader used the wrong file-reading method.",
        "root_cause": "Excel files were being read with a CSV-reading function.",
        "fix_summary": "Used the appropriate Excel-reading function.",
        "tested_status": "Verify",
        "remarks": "Confirm the Excel loader runs successfully."
    },
    {
        "issue_id": "BUG-002",
        "code_section": "Section 5 - DataLoader",
        "issue_type": "JSON Parsing",
        "issue_description": "JSON loader expected line-delimited JSON.",
        "root_cause": "The JSON file contained a JSON list rather than JSON Lines.",
        "fix_summary": "Adjusted JSON loading to match the file format.",
        "tested_status": "Verify",
        "remarks": "Confirm customer_complaints.json loads correctly."
    },
    {
        "issue_id": "BUG-003",
        "code_section": "Section 5 - DataLoader",
        "issue_type": "Text File Handling",
        "issue_description": "Text-file loading needed consistent encoding and line cleanup.",
        "root_cause": "Text input was not being normalized consistently.",
        "fix_summary": "Added suitable encoding and cleaned text lines.",
        "tested_status": "Verify",
        "remarks": "Confirm status_notes.txt loads correctly."
    },
    {
        "issue_id": "BUG-004",
        "code_section": "Section 6 - Validation",
        "issue_type": "Schema Validation",
        "issue_description": "Required columns and dataset structures needed validation.",
        "root_cause": "Input tables could be processed without all required fields.",
        "fix_summary": "Validated required columns before downstream processing.",
        "tested_status": "Verify",
        "remarks": "Check required-column validation results."
    },
    {
        "issue_id": "BUG-005",
        "code_section": "Section 8 - SLA Analysis",
        "issue_type": "Missing Derived Column",
        "issue_description": "The SLA analysis output lacked sla_status.",
        "root_cause": "SLA flags existed, but the categorical status was not generated.",
        "fix_summary": "Added Breached, Near Breach, Within SLA, and Not Assessable labels.",
        "tested_status": "Verify",
        "remarks": "Confirm sla_status exists and its values follow the rules."
    },
    {
        "issue_id": "BUG-006",
        "code_section": "Section 10 - Complaint Analysis",
        "issue_type": "Merge Cardinality",
        "issue_description": "Complaint records needed aggregation before joining requests.",
        "root_cause": "Multiple complaint records per request can multiply request rows.",
        "fix_summary": "Aggregated complaint features by request before merging.",
        "tested_status": "Verify",
        "remarks": "Confirm request count remains 4992."
    },
    {
        "issue_id": "BUG-007",
        "code_section": "Section 11 - Ticket Analysis",
        "issue_type": "Merge Cardinality",
        "issue_description": "Ticket records needed aggregation before joining requests.",
        "root_cause": "Multiple tickets per request can multiply request rows.",
        "fix_summary": "Aggregated ticket features by request before merging.",
        "tested_status": "Verify",
        "remarks": "Confirm request count remains 4992."
    },
    {
        "issue_id": "BUG-008",
        "code_section": "Section 12 - Duplicate Detection",
        "issue_type": "Data Quality",
        "issue_description": "Duplicate detection needed to preserve the working request table.",
        "root_cause": "Removing flagged records during detection could reduce the request count.",
        "fix_summary": "Kept duplicate detection separate from destructive row removal.",
        "tested_status": "Verify",
        "remarks": "Confirm final request IDs remain unique."
    },
    {
        "issue_id": "BUG-009",
        "code_section": "Section 13 - Feature Engineering",
        "issue_type": "Data Integration",
        "issue_description": "Final features needed to be merged without losing request rows.",
        "root_cause": "Uncontrolled merge cardinality can change the request-level row count.",
        "fix_summary": "Integrated aggregated features and checked final table cardinality.",
        "tested_status": "Verify",
        "remarks": "Confirm final_feature_df contains 4992 rows."
    },
    {
        "issue_id": "BUG-010",
        "code_section": "Section 18 - Report Export",
        "issue_type": "Export Validation",
        "issue_description": "Exported reports needed explicit file-existence and row-count checks.",
        "root_cause": "A successful export call alone does not verify all expected outputs.",
        "fix_summary": "Added output manifest and export validation checks.",
        "tested_status": "Verify",
        "remarks": "Confirm all expected report files exist."
    }
]

debug_fix_log_df = pd.DataFrame(debug_entries, columns=debug_columns)

print("Debug log rows:", len(debug_fix_log_df))
print("Required columns present:",
      all(col in debug_fix_log_df.columns for col in debug_columns))

display(debug_fix_log_df)

# Save the updated log
output_dir = Path("hdfc_service_request_outputs")
output_dir.mkdir(parents=True, exist_ok=True)

debug_fix_log_df.to_csv(
    output_dir / "debug_fix_log_df.csv",
    index=False
)

print("Saved:", output_dir / "debug_fix_log_df.csv")

Debug log rows: 10
Required columns present: True

,issue_id,code_section,issue_type,issue_description,root_cause,fix_summary,tested_status,remarks
0,BUG-001,Section 5 - DataLoader,Runtime / File Handling,Excel loader used the wrong file-reading method.,Excel files were being read with a CSV-reading...,Used the appropriate Excel-reading function.,Verify,Confirm the Excel loader runs successfully.
1,BUG-002,Section 5 - DataLoader,JSON Parsing,JSON loader expected line-delimited JSON.,The JSON file contained a JSON list rather tha...,Adjusted JSON loading to match the file format.,Verify,Confirm customer_complaints.json loads correctly.
2,BUG-003,Section 5 - DataLoader,Text File Handling,Text-file loading needed consistent encoding a...,Text input was not being normalized consistently.,Added suitable encoding and cleaned text lines.,Verify,Confirm status_notes.txt loads correctly.
3,BUG-004,Section 6 - Validation,Schema Validation,Required columns and dataset structures needed...,Input tables could be processed without all re...,Validated required columns before downstream p...,Verify,Check required-column validation results.
4,BUG-005,Section 8 - SLA Analysis,Missing Derived Column,The SLA analysis output lacked sla_status.,"SLA flags existed, but the categorical status ...","Added Breached, Near Breach, Within SLA, and N...",Verify,Confirm sla_status exists and its values follo...
5,BUG-006,Section 10 - Complaint Analysis,Merge Cardinality,Complaint records needed aggregation before jo...,Multiple complaint records per request can mul...,Aggregated complaint features by request befor...,Verify,Confirm request count remains 4992.
6,BUG-007,Section 11 - Ticket Analysis,Merge Cardinality,Ticket records needed aggregation before joini...,Multiple tickets per request can multiply requ...,Aggregated ticket features by request before m...,Verify,Confirm request count remains 4992.
7,BUG-008,Section 12 - Duplicate Detection,Data Quality,Duplicate detection needed to preserve the wor...,Removing flagged records during detection coul...,Kept duplicate detection separate from destruc...,Verify,Confirm final request IDs remain unique.
8,BUG-009,Section 13 - Feature Engineering,Data Integration,Final features needed to be merged without los...,Uncontrolled merge cardinality can change the ...,Integrated aggregated features and checked fin...,Verify,Confirm final_feature_df contains 4992 rows.
9,BUG-010,Section 18 - Report Export,Export Validation,Exported reports needed explicit file-existenc...,A successful export call alone does not verify...,Added output manifest and export validation ch...,Verify,Confirm all expected report files exist.

Saved: hdfc_service_request_outputs/debug_fix_log_df.csv

In [ ]:

import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display, Markdown

# ------------------------------------------------------------
# 1. Initialize validation framework
# ------------------------------------------------------------
validation_results = []

def add_check(
    check_name,
    expected_result,
    actual_result,
    passed=None,
    review_required=False
):
    """
    Record a validation check.
    Missing evidence is marked Review Required, not Passed.
    """
    if review_required:
        status = "Review Required"
    elif passed is True:
        status = "Passed"
    elif passed is False:
        status = "Failed"
    else:
        status = "Review Required"

    validation_results.append({
        "check_name": check_name,
        "expected_result": expected_result,
        "actual_result": str(actual_result),
        "status": status
    })


def get_dataframe(*names):
    """Return the first available DataFrame among candidate names."""
    for name in names:
        value = globals().get(name)
        if isinstance(value, pd.DataFrame):
            return value, name
    return None, None


def truthy_flag(series):
    """Normalize common representations of Boolean flags."""
    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False)

    if pd.api.types.is_numeric_dtype(series):
        return pd.to_numeric(series, errors="coerce").eq(1)

    return (
        series.astype("string")
        .fillna("")
        .str.strip()
        .str.lower()
        .isin(["true", "1", "yes", "y", "flagged", "breached"])
    )


# ------------------------------------------------------------
# 2. Locate final report
# ------------------------------------------------------------
final_report_df, final_report_source = get_dataframe(
    "final_service_request_resolution_report",
    "final_feature_df"
)

if final_report_df is None:
    add_check(
        "Final report exists",
        "Final report DataFrame created",
        "No final report DataFrame found",
        passed=False
    )
else:
    add_check(
        "Final report exists",
        "Final report DataFrame created",
        f"{final_report_source}: {len(final_report_df)} rows",
        passed=(
            "request_id" in final_report_df.columns
            and len(final_report_df) > 0
        )
    )

# Prefer the Section 18 report when it exists; otherwise use the master.
if final_report_df is None:
    final_report_df = pd.DataFrame()


# ------------------------------------------------------------
# 3. Required final report columns
# ------------------------------------------------------------
required_final_columns = [
    "request_id",
    "customer_id",
    "branch_id",
    "request_category",
    "request_status",
    "sla_status",
    "request_priority",
    "priority_reason",
    "recommended_action",
    "ai_support_prompt"
]

if final_report_df.empty and len(final_report_df.columns) == 0:
    missing_final_cols = required_final_columns.copy()
else:
    missing_final_cols = [
        col for col in required_final_columns
        if col not in final_report_df.columns
    ]

add_check(
    "Required columns present",
    f"All {len(required_final_columns)} required columns",
    (
        "All required columns present"
        if not missing_final_cols
        else f"Missing: {missing_final_cols}"
    ),
    passed=(len(missing_final_cols) == 0)
)


# ------------------------------------------------------------
# 4. Row count and request ID uniqueness
# ------------------------------------------------------------
if "request_id" in final_report_df.columns:
    row_count = len(final_report_df)
    unique_ids = final_report_df["request_id"].nunique(dropna=True)
    missing_ids = int(final_report_df["request_id"].isna().sum())

    add_check(
        "Request IDs are unique",
        "One row per request; no missing request IDs",
        (
            f"Rows={row_count}; unique IDs={unique_ids}; "
            f"missing IDs={missing_ids}"
        ),
        passed=(
            row_count > 0
            and unique_ids == row_count
            and missing_ids == 0
        )
    )
else:
    row_count = len(final_report_df)

    add_check(
        "Request IDs are unique",
        "One row per request; no missing request IDs",
        "Cannot check: request_id column missing",
        passed=False
    )

# Compare with the upstream master table when available.
master_df, master_name = get_dataframe("final_feature_df")

if master_df is not None and "request_id" in master_df.columns:
    same_rows = len(final_report_df) == len(master_df)

    same_request_set = (
        "request_id" in final_report_df.columns
        and set(final_report_df["request_id"].dropna().astype(str))
        == set(master_df["request_id"].dropna().astype(str))
    )

    add_check(
        "Final report matches master table",
        "Same request count and request ID set",
        (
            f"Report rows={len(final_report_df)}; "
            f"master rows={len(master_df)}; "
            f"same ID set={same_request_set}"
        ),
        passed=(same_rows and same_request_set)
    )
else:
    add_check(
        "Final report matches master table",
        "Same request count and request ID set",
        "Master table unavailable",
        review_required=True
    )


# ------------------------------------------------------------
# 5. Validate priority labels
# ------------------------------------------------------------
allowed_priorities = {
    "P0", "P1", "P2", "P3", "NO ISSUE"
}

if "request_priority" in final_report_df.columns:
    priority_values = (
        final_report_df["request_priority"]
        .astype("string")
        .str.strip()
        .str.upper()
    )

    invalid_priority_mask = (
        priority_values.isna()
        | ~priority_values.isin(allowed_priorities)
    )

    invalid_priority_count = int(invalid_priority_mask.sum())

    add_check(
        "Valid priorities only",
        "P0/P1/P2/P3/No Issue; one label per request",
        (
            f"Invalid or missing labels: {invalid_priority_count}; "
            f"labels found: {sorted(priority_values.dropna().unique().tolist())}"
        ),
        passed=(invalid_priority_count == 0 and row_count > 0)
    )
else:
    priority_values = pd.Series(dtype="string")
    add_check(
        "Valid priorities only",
        "P0/P1/P2/P3/No Issue",
        "request_priority column missing",
        passed=False
    )


# ------------------------------------------------------------
# 6. Priority reasons required for P0/P1/P2/P3
# ------------------------------------------------------------
if (
    "request_priority" in final_report_df.columns
    and "priority_reason" in final_report_df.columns
):
    requires_reason = priority_values.isin(["P0", "P1", "P2", "P3"])

    reason_values = (
        final_report_df["priority_reason"]
        .astype("string")
        .fillna("")
        .str.strip()
    )

    missing_reason_mask = requires_reason & (
        reason_values.eq("")
        | reason_values.str.lower().isin(
            ["nan", "none", "not available", "unknown"]
        )
    )

    missing_reason_count = int(missing_reason_mask.sum())

    add_check(
        "Priority reasons present",
        "Every P0/P1/P2/P3 case has a reason",
        f"Cases missing reasons: {missing_reason_count}",
        passed=(missing_reason_count == 0)
    )
else:
    add_check(
        "Priority reasons present",
        "Every P0/P1/P2/P3 case has a reason",
        "Priority or reason column missing",
        passed=False
    )


# ------------------------------------------------------------
# 7. Recommended action completeness
# ------------------------------------------------------------
if "recommended_action" in final_report_df.columns:
    action_values = (
        final_report_df["recommended_action"]
        .astype("string")
        .fillna("")
        .str.strip()
    )

    missing_actions = int(
        (
            action_values.eq("")
            | action_values.str.lower().isin(
                ["nan", "none", "check manually"]
            )
        ).sum()
    )

    add_check(
        "Recommended actions present",
        "Every request has a meaningful next action",
        f"Blank or generic actions: {missing_actions}",
        passed=(missing_actions == 0 and row_count > 0)
    )
else:
    add_check(
        "Recommended actions present",
        "Every request has a meaningful next action",
        "recommended_action column missing",
        passed=False
    )


# ------------------------------------------------------------
# 8. AI prompts for P0/P1/P2 only
# ------------------------------------------------------------
if (
    "request_priority" in final_report_df.columns
    and "ai_support_prompt" in final_report_df.columns
):
    ai_prompts = (
        final_report_df["ai_support_prompt"]
        .astype("string")
        .fillna("")
        .str.strip()
    )

    p012_mask = priority_values.isin(["P0", "P1", "P2"])
    p3_no_issue_mask = priority_values.isin(["P3", "NO ISSUE"])

    missing_required_prompts = int(
        (p012_mask & ai_prompts.eq("")).sum()
    )

    unexpected_prompts = int(
        (p3_no_issue_mask & ai_prompts.ne("")).sum()
    )

    add_check(
        "AI prompts generated",
        "Non-empty prompts for P0/P1/P2 only",
        (
            f"Missing P0/P1/P2 prompts={missing_required_prompts}; "
            f"Unexpected P3/No Issue prompts={unexpected_prompts}"
        ),
        passed=(
            missing_required_prompts == 0
            and unexpected_prompts == 0
        )
    )
else:
    add_check(
        "AI prompts generated",
        "Non-empty prompts for P0/P1/P2 only",
        "Required priority or prompt column missing",
        passed=False
    )


# ------------------------------------------------------------
# 9. Check required output files
# ------------------------------------------------------------
output_dir = Path("hdfc_service_request_outputs")

required_output_files = [
    "final_service_request_resolution_report.csv",
    "sla_breach_report.csv",
    "branch_issue_summary.csv",
    "category_status_summary.csv",
    "pending_request_report.csv",
    "p0_p1_priority_cases.csv",
    "ai_support_prompts.csv",
    "data_validation_report.csv",
    "debug_fix_log_df.csv",
    "service_request_health_summary.csv"
]

missing_output_files = [
    filename for filename in required_output_files
    if not (output_dir / filename).is_file()
]

add_check(
    "Output files created",
    f"All {len(required_output_files)} required CSV files exist",
    (
        "All required CSV files found"
        if not missing_output_files
        else f"Missing files: {missing_output_files}"
    ),
    passed=(len(missing_output_files) == 0)
)


# ------------------------------------------------------------
# 10. Check debug fix log length
# ------------------------------------------------------------
debug_log_df, debug_log_name = get_dataframe(
    "debug_fix_log_df",
    "debug_log_df",
    "debug_log",
    "debug_fix_log",
    "debug_fix_log_table"
)

if debug_log_df is not None:
    debug_log_rows = len(debug_log_df)

    add_check(
        "Debug log length",
        "At least 10 documented debug entries",
        f"{debug_log_name}: {debug_log_rows} rows",
        passed=(debug_log_rows >= 10)
    )
else:
    add_check(
        "Debug log length",
        "At least 10 documented debug entries",
        "No debug log DataFrame found",
        review_required=True
    )


# ------------------------------------------------------------
# 11. Check AI prompt usage log
# ------------------------------------------------------------
ai_usage_log_df, ai_usage_log_name = get_dataframe(
    "ai_prompt_usage_log",
    "ai_prompt_usage_log_df",
    "prompt_usage_log",
    "prompt_usage_log_df",
    "ai_prompt_log",
    "ai_prompt_log_df"
)

if ai_usage_log_df is not None:
    add_check(
        "AI prompt usage log",
        "Separate AI development/prompt usage log exists",
        f"{ai_usage_log_name}: {len(ai_usage_log_df)} rows",
        passed=(len(ai_usage_log_df) > 0)
    )
else:
    add_check(
        "AI prompt usage log",
        "Separate AI development/prompt usage log exists",
        "No separate usage-log DataFrame found",
        review_required=True
    )


# ------------------------------------------------------------
# 12. Check PRD completion mapping
# ------------------------------------------------------------
prd_mapping_df, prd_mapping_name = get_dataframe(
    "prd_completion_mapping",
    "prd_completion_mapping_df",
    "prd_mapping",
    "prd_mapping_df",
    "prd_checklist_df",
    "prd_checklist"
)

if prd_mapping_df is not None:
    mapping_rows = len(prd_mapping_df)

    status_column = next(
        (
            col for col in [
                "status", "completion_status",
                "implementation_status", "result"
            ]
            if col in prd_mapping_df.columns
        ),
        None
    )

    if status_column:
        statuses = (
            prd_mapping_df[status_column]
            .astype("string")
            .fillna("")
            .str.strip()
            .str.lower()
        )

        incomplete_count = int(
            statuses.isin([
                "failed", "incomplete", "not done",
                "not implemented", "pending", "review required"
            ]).sum()
        )

        add_check(
            "PRD completion mapping",
            "PRD requirements mapped and complete",
            (
                f"{prd_mapping_name}: {mapping_rows} rows; "
                f"incomplete/review entries={incomplete_count}"
            ),
            passed=(mapping_rows > 0 and incomplete_count == 0)
        )
    else:
        add_check(
            "PRD completion mapping",
            "PRD requirements mapped with a completion status",
            (
                f"{prd_mapping_name}: {mapping_rows} rows; "
                "no recognizable status column"
            ),
            review_required=True
        )
else:
    add_check(
        "PRD completion mapping",
        "PRD requirements mapped and complete",
        "No PRD mapping DataFrame found",
        review_required=True
    )


# ------------------------------------------------------------
# 13. Check Section 18 export manifest
# ------------------------------------------------------------
manifest_df, manifest_name = get_dataframe("export_manifest")

manifest_file = output_dir / "report_export_manifest.csv"

if manifest_df is not None:
    manifest_count = len(manifest_df)

    add_check(
        "Export manifest",
        "Manifest lists all 10 required reports",
        f"{manifest_name}: {manifest_count} rows",
        passed=(manifest_count >= 10)
    )
elif manifest_file.is_file():
    try:
        manifest_disk_df = pd.read_csv(manifest_file)

        add_check(
            "Export manifest",
            "Manifest lists all 10 required reports",
            f"File found with {len(manifest_disk_df)} rows",
            passed=(len(manifest_disk_df) >= 10)
        )
    except Exception as exc:
        add_check(
            "Export manifest",
            "Readable manifest with all required reports",
            f"Could not read manifest: {exc}",
            passed=False
        )
else:
    add_check(
        "Export manifest",
        "Manifest lists all 10 required reports",
        "Manifest not found",
        passed=False
    )


# ------------------------------------------------------------
# 14. Check priority report row counts against the final report
# ------------------------------------------------------------
p0p1_file = output_dir / "p0_p1_priority_cases.csv"

if (
    p0p1_file.is_file()
    and "request_priority" in final_report_df.columns
):
    try:
        exported_p0p1 = pd.read_csv(p0p1_file)

        expected_p0p1_count = int(
            priority_values.isin(["P0", "P1"]).sum()
        )

        add_check(
            "P0/P1 export row count",
            f"{expected_p0p1_count} P0/P1 cases",
            f"{len(exported_p0p1)} exported rows",
            passed=(len(exported_p0p1) == expected_p0p1_count)
        )
    except Exception as exc:
        add_check(
            "P0/P1 export row count",
            "Exported count matches final report",
            f"Unable to validate exported CSV: {exc}",
            passed=False
        )
else:
    add_check(
        "P0/P1 export row count",
        "Exported count matches final report",
        "File or priority column unavailable",
        review_required=True
    )


# ------------------------------------------------------------
# 15. Record end-to-end execution limitation
# ------------------------------------------------------------
add_check(
    "Notebook top-to-bottom execution",
    "Restart runtime and run every cell in order without errors",
    (
        "Cannot be proven by this cell alone; perform a clean "
        "Runtime Restart and Run All before submission."
    ),
    review_required=True
)


# ------------------------------------------------------------
# 16. Create visible final validation summary
# ------------------------------------------------------------
final_validation_summary = pd.DataFrame(validation_results)

status_order = ["Failed", "Review Required", "Passed"]

summary_counts = (
    final_validation_summary["status"]
    .value_counts()
    .reindex(status_order, fill_value=0)
)

print("=" * 75)
print("SECTION 19: FINAL VALIDATION SUMMARY")
print("=" * 75)

display(final_validation_summary)

print("\nValidation totals:")
display(
    summary_counts.rename("check_count").reset_index()
    .rename(columns={"index": "status"})
)

failed_count = int(
    (final_validation_summary["status"] == "Failed").sum()
)

review_count = int(
    (final_validation_summary["status"] == "Review Required").sum()
)

passed_count = int(
    (final_validation_summary["status"] == "Passed").sum()
)

print(f"\nPassed: {passed_count}")
print(f"Failed: {failed_count}")
print(f"Review Required: {review_count}")

if failed_count == 0 and review_count == 0:
    print("\nFINAL STATUS: PASSED — all recorded checks passed.")
elif failed_count > 0:
    print(
        "\nFINAL STATUS: NOT READY — fix failed checks and rerun Section 19."
    )
else:
    print(
        "\nFINAL STATUS: REVIEW REQUIRED — resolve outstanding evidence "
        "checks before submission."
    )

# Save the validation evidence for submission.
validation_output_path = output_dir / "final_validation_summary.csv"
output_dir.mkdir(parents=True, exist_ok=True)

final_validation_summary.to_csv(
    validation_output_path,
    index=False,
    encoding="utf-8-sig"
)

print(
    "\nValidation summary exported to:",
    str(validation_output_path)
)

===========================================================================
SECTION 19: FINAL VALIDATION SUMMARY
===========================================================================

                           check_name                                    expected_result                                      actual_result           status
0                 Final report exists                     Final report DataFrame created  final_service_request_resolution_report: 4992 ...           Passed
1            Required columns present                            All 10 required columns                       All required columns present           Passed
2              Request IDs are unique        One row per request; no missing request IDs          Rows=4992; unique IDs=4992; missing IDs=0           Passed
3   Final report matches master table              Same request count and request ID set  Report rows=4992; master rows=4992; same ID se...           Passed
4               Valid priorities only        P0/P1/P2/P3/No Issue; one label per request  Invalid or missing labels: 0; labels found: ['...           Passed
5            Priority reasons present                Every P0/P1/P2/P3 case has a reason                           Cases missing reasons: 0           Passed
6         Recommended actions present         Every request has a meaningful next action                        Blank or generic actions: 0           Passed
7                AI prompts generated                Non-empty prompts for P0/P1/P2 only  Missing P0/P1/P2 prompts=0; Unexpected P3/No I...           Passed
8                Output files created                    All 10 required CSV files exist                       All required CSV files found           Passed
9                    Debug log length               At least 10 documented debug entries                          debug_fix_log_df: 10 rows           Passed
10                AI prompt usage log    Separate AI development/prompt usage log exists                     ai_prompt_usage_log_df: 2 rows           Passed
11             PRD completion mapping               PRD requirements mapped and complete  prd_completion_mapping_df: 11 rows; incomplete...           Passed
12                    Export manifest             Manifest lists all 10 required reports                           export_manifest: 10 rows           Passed
13             P0/P1 export row count                                   4374 P0/P1 cases                                 4374 exported rows           Passed
14   Notebook top-to-bottom execution  Restart runtime and run every cell in order wi...  Cannot be proven by this cell alone; perform a...  Review Required

Validation totals:

            status  check_count
0           Failed            0
1  Review Required            1
2           Passed           14

Passed: 14
Failed: 0
Review Required: 1

FINAL STATUS: REVIEW REQUIRED — resolve outstanding evidence checks before submission.

Validation summary exported to: hdfc_service_request_outputs/final_validation_summary.csv

### Expected Output — Section 19: Final Validation Checks

**Datasets to use:**

- Final report DataFrames
- Exported output folder
- Debug log
- AI prompt usage log
- PRD completion mapping

**How to approach:**

- Write validation checks that prove the notebook is ready for submission.
- Check required columns, row counts, priority labels, priority reasons, recommended actions, AI prompts, output files, and debug log length.
- Show a final validation summary table with Passed/Failed status.

**Expected output format:**

Create a visible `final_validation_summary` table like:

| check_name | expected_result | actual_result | status |
|---|---|---|---|
| Final report exists | DataFrame created | Created with 5000 rows | Passed |
| Required columns present | 20+ required columns | All present | Passed |
| Valid priorities only | P0/P1/P2/P3/No Issue | Valid | Passed |
| Priority reasons present | Required for P0-P3 | Present | Passed |
| AI prompts generated | Required for P0/P1/P2 | Present | Passed |
| Debug log length | At least 10 rows | 10+ rows | Passed |
| Output files created | All required files | All present | Passed |

**Hint:** A notebook that produces reports but has no validation evidence is not evaluation-ready.

# Required In-Notebook Deliverable Workspaces

Your final submission is **one completed Colab notebook only**. Because you are not submitting separate documents, you must complete the following deliverable sections directly inside this notebook.

Each section below gives you the required format. Replace placeholder rows with your actual work and keep the outputs visible.

## Deliverable 1 — Debug Fix Log

**Purpose:** Show how you debugged and completed the resigned developer's unfinished codebase.

**Where to use it:** Update this log throughout Sections 4–19.

**Minimum requirement:** At least **10 meaningful fixes**.

**Expected output format:** Fill the table below and display it as `debug_fix_log_df`.

In [ ]:
# ============================================================
# Deliverable 1 Placeholder: Debug Fix Log
# Replace sample rows with your actual debugging evidence.
# Keep this output visible in your final submitted notebook.
# ============================================================

debug_fix_log_df = pd.DataFrame([
    {
        "issue_id": "BUG-001",
        "code_section": "Section 5 - DataLoader",
        "issue_type": "Runtime / File Handling",
        "issue_description": "Example: Excel file loader was using the wrong Pandas function.",
        "root_cause": "Example: Previous developer used pd.read_csv() for request_status_updates.xlsx.",
        "fix_summary": "Example: Replaced with pd.read_excel() and added file existence handling.",
        "tested_status": "Passed",
        "remarks": "Replace this sample row with your actual fix notes."
    },
    {
        "issue_id": "BUG-002",
        "code_section": "Section __ - ______",
        "issue_type": "Logic / Data / OOP / Export / GUI",
        "issue_description": "Write what was broken.",
        "root_cause": "Write why it happened.",
        "fix_summary": "Write what you changed.",
        "tested_status": "Passed / Failed",
        "remarks": "Add evidence or notes."
    }
])

debug_fix_log_df

,issue_id,code_section,issue_type,issue_description,root_cause,fix_summary,tested_status,remarks
0,BUG-001,Section 5 - DataLoader,Runtime / File Handling,Example: Excel file loader was using the wrong...,Example: Previous developer used pd.read_csv()...,Example: Replaced with pd.read_excel() and add...,Passed,Replace this sample row with your actual fix n...
1,BUG-002,Section __ - ______,Logic / Data / OOP / Export / GUI,Write what was broken.,Write why it happened.,Write what you changed.,Passed / Failed,Add evidence or notes.

## Deliverable 2 — AI Prompt Usage Log

**Purpose:** Since AI usage is allowed, document how you used AI responsibly.

**What to include:** Prompts used for debugging, logic design, Pandas grouping, GUI building, validation checks, or report formatting.

**Important:** Do not just paste AI answers blindly. Show how you verified or modified them.

**Expected output format:** Fill the table below and display it as `ai_prompt_usage_log_df`.

In [ ]:
# ============================================================
# Deliverable 2 Placeholder: AI Prompt Usage Log
# Add the actual prompts you used while solving this notebook.
# ============================================================

ai_prompt_usage_log_df = pd.DataFrame([
    {
        "prompt_id": "AI-001",
        "section_used": "Section 8 - SLA Logic",
        "prompt_goal": "Example: Understand how to calculate SLA breach using created/resolved dates.",
        "prompt_used": "Example: I have created date, resolved date, status, and SLA hours. How should I calculate SLA breach safely in Pandas?",
        "ai_output_summary": "Example: AI suggested using resolved date when available and analysis date for unresolved records.",
        "accepted_or_modified": "Modified",
        "verification_notes": "Example: I checked value counts and manually tested a few breached and non-breached records."
    },
    {
        "prompt_id": "AI-002",
        "section_used": "Section __ - ______",
        "prompt_goal": "What were you trying to solve?",
        "prompt_used": "Paste your actual prompt here.",
        "ai_output_summary": "Summarize what AI suggested.",
        "accepted_or_modified": "Accepted / Modified / Rejected",
        "verification_notes": "How did you verify the answer?"
    }
])

ai_prompt_usage_log_df

,prompt_id,section_used,prompt_goal,prompt_used,ai_output_summary,accepted_or_modified,verification_notes
0,AI-001,Section 8 - SLA Logic,Example: Understand how to calculate SLA breac...,"Example: I have created date, resolved date, s...",Example: AI suggested using resolved date when...,Modified,Example: I checked value counts and manually t...
1,AI-002,Section __ - ______,What were you trying to solve?,Paste your actual prompt here.,Summarize what AI suggested.,Accepted / Modified / Rejected,How did you verify the answer?

## Deliverable 3 — PRD Completion Mapping

**Purpose:** Prove that your implementation matches the PRD and is not just random analysis.

**How to approach:** Map each PRD requirement to the notebook section where you implemented it.

**Expected output format:** Fill the table below and display it as `prd_completion_mapping_df`.

In [ ]:
# ============================================================
# Deliverable 3 Placeholder: PRD Completion Mapping
# Map PRD requirements to your completed notebook sections.
# ============================================================

prd_completion_mapping_df = pd.DataFrame([
    {"prd_requirement": "FR-01 Multi-File Data Loader", "notebook_section": "Section 5", "implementation_summary": "Loads CSV, Excel, JSON, and TXT files with status table.", "status": "Completed", "evidence_output": "Loading summary table visible"},
    {"prd_requirement": "FR-02 Data Validation Engine", "notebook_section": "Section 6", "implementation_summary": "Required column and data quality checks implemented.", "status": "Completed / Partial / Pending", "evidence_output": "data_validation_report displayed"},
    {"prd_requirement": "FR-03 Data Cleaning and Standardization", "notebook_section": "Section 7", "implementation_summary": "Describe your cleaning logic.", "status": "Completed / Partial / Pending", "evidence_output": "Before/after value counts displayed"},
    {"prd_requirement": "FR-04 SLA Breach Analysis", "notebook_section": "Section 8", "implementation_summary": "Describe your SLA logic.", "status": "Completed / Partial / Pending", "evidence_output": "service_request_health_summary displayed"},
    {"prd_requirement": "FR-05 Branch-Wise Analysis", "notebook_section": "Section 9", "implementation_summary": "Describe branch risk logic.", "status": "Completed / Partial / Pending", "evidence_output": "branch_issue_summary displayed"},
    {"prd_requirement": "FR-06 Complaint Linking Engine", "notebook_section": "Section 10", "implementation_summary": "Describe complaint aggregation and linking.", "status": "Completed / Partial / Pending", "evidence_output": "Complaint summary displayed"},
    {"prd_requirement": "FR-07 Support Ticket Mapping", "notebook_section": "Section 11", "implementation_summary": "Describe ticket SLA mapping.", "status": "Completed / Partial / Pending", "evidence_output": "Ticket severity counts displayed"},
    {"prd_requirement": "FR-08 Repeat/Duplicate Request Detection", "notebook_section": "Section 12", "implementation_summary": "Describe duplicate suspicion logic.", "status": "Completed / Partial / Pending", "evidence_output": "Duplicate suspected cases displayed"},
    {"prd_requirement": "FR-09 Request Priority Classification", "notebook_section": "Section 14", "implementation_summary": "Describe P0/P1/P2/P3 logic.", "status": "Completed / Partial / Pending", "evidence_output": "Priority distribution displayed"},
    {"prd_requirement": "FR-10 Customer Impact Score", "notebook_section": "Section 14", "implementation_summary": "Describe impact score logic.", "status": "Completed / Partial / Pending", "evidence_output": "Impact score columns visible"},
    {"prd_requirement": "FR-11 to FR-19 Reports and GUI", "notebook_section": "Sections 15-19", "implementation_summary": "Describe outputs.", "status": "Completed / Partial / Pending", "evidence_output": "Reports, GUI, validation visible"}
])

prd_completion_mapping_df

,prd_requirement,notebook_section,implementation_summary,status,evidence_output
0,FR-01 Multi-File Data Loader,Section 5,"Loads CSV, Excel, JSON, and TXT files with sta...",Completed,Loading summary table visible
1,FR-02 Data Validation Engine,Section 6,Required column and data quality checks implem...,Completed / Partial / Pending,data_validation_report displayed
2,FR-03 Data Cleaning and Standardization,Section 7,Describe your cleaning logic.,Completed / Partial / Pending,Before/after value counts displayed
3,FR-04 SLA Breach Analysis,Section 8,Describe your SLA logic.,Completed / Partial / Pending,service_request_health_summary displayed
4,FR-05 Branch-Wise Analysis,Section 9,Describe branch risk logic.,Completed / Partial / Pending,branch_issue_summary displayed
5,FR-06 Complaint Linking Engine,Section 10,Describe complaint aggregation and linking.,Completed / Partial / Pending,Complaint summary displayed
6,FR-07 Support Ticket Mapping,Section 11,Describe ticket SLA mapping.,Completed / Partial / Pending,Ticket severity counts displayed
7,FR-08 Repeat/Duplicate Request Detection,Section 12,Describe duplicate suspicion logic.,Completed / Partial / Pending,Duplicate suspected cases displayed
8,FR-09 Request Priority Classification,Section 14,Describe P0/P1/P2/P3 logic.,Completed / Partial / Pending,Priority distribution displayed
9,FR-10 Customer Impact Score,Section 14,Describe impact score logic.,Completed / Partial / Pending,Impact score columns visible
10,FR-11 to FR-19 Reports and GUI,Sections 15-19,Describe outputs.,Completed / Partial / Pending,"Reports, GUI, validation visible"

## Deliverable 4 — Assumption and Limitation Log

**Purpose:** In real engineering work, assumptions must be visible. If you make a business or technical decision not explicitly stated in the PRD, document it here.

**Expected output format:** Fill the table below and display it as `assumption_limitation_log_df`.

In [ ]:
# ============================================================
# Deliverable 4 Placeholder: Assumption and Limitation Log
# ============================================================

assumption_limitation_log_df = pd.DataFrame([
    {
        "item_id": "ASM-001",
        "type": "Assumption",
        "section": "Section 8 - SLA Logic",
        "description": "Example: For unresolved requests, elapsed hours are calculated from request_created_date to ANALYSIS_DATE.",
        "reason": "PRD requires reproducible analysis using fixed analysis date.",
        "impact": "Ensures pending SLA breach detection is consistent."
    },
    {
        "item_id": "LIM-001",
        "type": "Limitation",
        "section": "Section 17 - GUI",
        "description": "Example: GUI works inside Colab only and is not a production web dashboard.",
        "reason": "Out of scope includes Flask/Streamlit/deployment.",
        "impact": "Suitable for internal notebook workflow only."
    }
])

assumption_limitation_log_df

,item_id,type,section,description,reason,impact
0,ASM-001,Assumption,Section 8 - SLA Logic,"Example: For unresolved requests, elapsed hour...",PRD requires reproducible analysis using fixed...,Ensures pending SLA breach detection is consis...
1,LIM-001,Limitation,Section 17 - GUI,Example: GUI works inside Colab only and is no...,Out of scope includes Flask/Streamlit/deployment.,Suitable for internal notebook workflow only.

## Deliverable 5 — Final Report Preview Evidence

**Purpose:** Since the final submission is only this notebook, preview the final reports here.

**How to approach:** After exporting reports, display the shape and first few rows of each key report.

**Expected output format:** Run this after your final report variables are created. Add/remove report variables only if your names differ, but keep the evidence visible.

In [ ]:
# ============================================================
# Deliverable 5 Placeholder: Final Report Preview Evidence
# Run after creating final report DataFrames.
# ============================================================

report_objects = {
    "final_service_request_resolution_report": globals().get("final_service_request_resolution_report"),
    "sla_breach_report": globals().get("sla_breach_report"),
    "branch_issue_summary": globals().get("branch_issue_summary"),
    "category_status_summary": globals().get("category_status_summary"),
    "pending_request_report": globals().get("pending_request_report"),
    "p0_p1_priority_cases": globals().get("p0_p1_priority_cases"),
    "ai_support_prompts": globals().get("ai_support_prompts"),
    "data_validation_report": globals().get("data_validation_report"),
    "service_request_health_summary": globals().get("service_request_health_summary"),
}

for report_name, report_df in report_objects.items():
    print("\n" + "="*80)
    print(report_name)
    if isinstance(report_df, pd.DataFrame):
        print("Shape:", report_df.shape)
        display(report_df.head())
    else:
        print("Not created yet. Create this report before final submission.")

================================================================================
final_service_request_resolution_report
Shape: (4992, 76)

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,customer_name,customer_segment,account_type,relationship_age_days,preferred_branch_id,branch_name,branch_city,branch_state,branch_zone,branch_type,sla_status,elapsed_hours,complaint_count,customer_complaint_count,complaint_status,complaint_type,sentiment_tag,complaint_severity,repeated_complaint_flag,reopened_complaint_flag,angry_complaint_flag,unresolved_complaint_flag,ticket_count,ticket_status,assigned_team_ticket,escalation_flag,max_ticket_age_hours,ticket_severity,ticket_issue_tag,ticket_sla_breached_flag,ticket_delay_warning_flag,slow_resolution_flag,duplicate_suspected,duplicate_group_key,duplicate_reason,duplicate_id_flag,same_day_repeat_flag,recurring_issue_flag,unresolved_repeat_count,status_update_count,last_update_date,latest_status_from_update,reassignment_count,total_requests,pending_requests,sla_breaches,branch_risk_score,near_sla_breaches,avg_elapsed_hours,pending_rate_pct,sla_breach_rate_pct,near_breach_rate_pct,request_priority,priority_reason,customer_impact_score,customer_impact_level,recommended_action,ai_support_prompt,ai_prompt_reason
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,Vikram Khan,Corporate,Savings,499,BR0574,HDFC Jodhpur Service Branch 0566,Jodhpur,Rajasthan,North,Urban,Breached,1536.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,10.0,6.0,8.0,58.0,0.0,1243.200000,60.000000,80.000000,0.0,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
1,REQ0000010,CUST000649,BR0980,2026-05-17,22:31:00,Card,Failed ATM Withdrawal,WhatsApp,pending_customer,36,Cards Operations,24383.2,2026-05-18,NaT,False,False,False,Vivaan Mehta,Corporate,NRI Savings,3430,BR0458,HDFC Kozhikode Service Branch 0980,Kozhikode,Kerala,South,Metro,Breached,1056.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,9.0,5.0,6.0,50.0,0.0,1157.333333,55.555556,66.666667,0.0,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
2,REQ0000011,CUST000817,BR0045,2026-06-19,04:47:00,Digital Banking,NetBanking Login,Email,closed,24,Digital Banking Support,193459.78,2026-06-19,2026-06-19,False,False,False,Vivaan Agarwal,Senior Citizen,Current,872,BR0509,HDFC Noida Service Branch 0045,Noida,Delhi NCR,North,Semi-Urban,Within SLA,0.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,1,2026-07-01,resolved,0,5.0,2.0,3.0,46.0,1.0,720.000000,40.000000,60.000000,20.0,No Issue,"No identified SLA, complaint, escalation, or r...",0,Low,No immediate action required; continue standar...,,"No identified SLA, complaint, escalation, or r..."
3,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,Reyansh Malhotra,NRI,Savings,2590,BR0622,HDFC Hyderabad Service Branch 0335,Hyderabad,Telangana,South,Rural,Breached,1704.0,0,0,No Complaint,None,None,None,False,False,False,False,1,open,Customer Care,False,1704.0,Severe,Ticket SLA Breach; Active Ticket,True,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,1.0,2.0,32.5,0.0,456.000000,25.000000,50.000000,0.0,P0,Request SLA breached; Ticket SLA breached; Esc...,75,High,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Ticket SLA breached; Esc...
4,REQ0000013,CUST001137,BR0081,2026-06-13,07:18:00,Account,Balance Mismatch,NetBanking,closed,48,Account Servicing,<NA>,2026-06-16,2026-06-16,False,False,False,Saanvi Iyer,Corporate,Loan Account,950,BR0144,HDFC Kochi Service Branch 0081,Kochi,Kerala,South,Urban,Breached,72.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,5.0,0.0,1.0,14.0,1.0,38.400000,0.000000,20.000000,20.0,P1,Request SLA breached,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached

================================================================================
sla_breach_report
Shape: (3432, 32)

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,invalid_created_date_flag,is_resolved_or_closed,is_pending_unresolved,elapsed_time_basis,elapsed_end_date,missing_resolved_date_flag,elapsed_hours,negative_elapsed_flag,invalid_elapsed_flag,invalid_sla_flag,sla_assessable_flag,sla_breached,near_sla_breach,sla_status,category_for_summary
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,1536.0,False,False,False,True,True,False,Breached,Complaint
1,REQ0000010,CUST000649,BR0980,2026-05-17,22:31:00,Card,Failed ATM Withdrawal,WhatsApp,pending_customer,36,Cards Operations,24383.2,2026-05-18,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,1056.0,False,False,False,True,True,False,Breached,Card
3,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,1704.0,False,False,False,True,True,False,Breached,Complaint
4,REQ0000013,CUST001137,BR0081,2026-06-13,07:18:00,Account,Balance Mismatch,NetBanking,closed,48,Account Servicing,<NA>,2026-06-16,2026-06-16,False,False,False,False,True,False,resolved_date,2026-06-16,False,72.0,False,False,False,True,True,False,Breached,Account
8,REQ0000017,CUST000492,BR0179,2026-04-21,18:52:00,Digital Banking,NetBanking Login,WhatsApp,pending_customer,24,Digital Banking Support,158525.74,2026-04-22,NaT,False,False,False,False,False,True,ANALYSIS_DATE,2026-06-30,False,1680.0,False,False,False,True,True,False,Breached,Digital Banking

================================================================================
branch_issue_summary
Shape: (1000, 13)

,branch_id,branch_name,branch_city,branch_zone,total_requests,pending_requests,sla_breaches,branch_risk_score,near_sla_breaches,avg_elapsed_hours,pending_rate_pct,sla_breach_rate_pct,near_breach_rate_pct
0,BR0002,HDFC Kanpur Service Branch 0002,Kanpur,North,3,3,3,80.0,0,2744.0,100.0,100.0,0.0
1,BR0978,HDFC Nagpur Service Branch 0978,Nagpur,West,2,2,2,80.0,0,2652.0,100.0,100.0,0.0
2,BR0976,HDFC Noida Service Branch 0976,Noida,North,4,4,4,80.0,0,2298.0,100.0,100.0,0.0
3,BR0453,HDFC Varanasi Service Branch 0453,Varanasi,North,1,1,1,80.0,0,264.0,100.0,100.0,0.0
4,BR0462,HDFC Noida Service Branch 0462,Noida,North,3,3,3,80.0,0,2872.0,100.0,100.0,0.0

================================================================================
category_status_summary
Shape: (36, 6)

  request_category request_status  total_requests  pending_requests  sla_breaches  avg_elapsed_hours
0  Digital Banking    in_progress             232               232           232            2301.62
1          Account    in_progress             216               216           216            2352.56
2             Card    in_progress             215               215           214            2358.14
3              KYC    in_progress             198               198           198            2351.64
4        Complaint    in_progress             191               191           191            2128.08

================================================================================
pending_request_report
Shape: (2116, 76)

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,customer_name,customer_segment,account_type,relationship_age_days,preferred_branch_id,branch_name,branch_city,branch_state,branch_zone,branch_type,sla_status,elapsed_hours,complaint_count,customer_complaint_count,complaint_status,complaint_type,sentiment_tag,complaint_severity,repeated_complaint_flag,reopened_complaint_flag,angry_complaint_flag,unresolved_complaint_flag,ticket_count,ticket_status,assigned_team_ticket,escalation_flag,max_ticket_age_hours,ticket_severity,ticket_issue_tag,ticket_sla_breached_flag,ticket_delay_warning_flag,slow_resolution_flag,duplicate_suspected,duplicate_group_key,duplicate_reason,duplicate_id_flag,same_day_repeat_flag,recurring_issue_flag,unresolved_repeat_count,status_update_count,last_update_date,latest_status_from_update,reassignment_count,total_requests,pending_requests,sla_breaches,branch_risk_score,near_sla_breaches,avg_elapsed_hours,pending_rate_pct,sla_breach_rate_pct,near_breach_rate_pct,request_priority,priority_reason,customer_impact_score,customer_impact_level,recommended_action,ai_support_prompt,ai_prompt_reason
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,Vikram Khan,Corporate,Savings,499,BR0574,HDFC Jodhpur Service Branch 0566,Jodhpur,Rajasthan,North,Urban,Breached,1536.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,10.0,6.0,8.0,58.00,0.0,1243.200000,60.000000,80.0,0.0,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
3,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,Reyansh Malhotra,NRI,Savings,2590,BR0622,HDFC Hyderabad Service Branch 0335,Hyderabad,Telangana,South,Rural,Breached,1704.0,0,0,No Complaint,None,None,None,False,False,False,False,1,open,Customer Care,False,1704.0,Severe,Ticket SLA Breach; Active Ticket,True,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,1.0,2.0,32.50,0.0,456.000000,25.000000,50.0,0.0,P0,Request SLA breached; Ticket SLA breached; Esc...,75,High,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Ticket SLA breached; Esc...
11,REQ0000020,CUST000348,BR0426,2026-05-18,23:33:00,Card,PIN Reset,Branch,in_progress,36,Cards Operations,44625.89,2026-05-19,NaT,False,False,False,Neha Patel,Senior Citizen,Current,3302,BR0063,HDFC Hyderabad Service Branch 0426,Hyderabad,Telangana,South,Digital Service Hub,Breached,1032.0,0,0,No Complaint,None,None,None,False,False,False,False,1,closed,Customer Care,True,<NA>,Severe,Escalated Case; Missing Resolution Time,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,2,2026-05-22,closed,0,7.0,6.0,7.0,75.71,0.0,1683.428571,85.714286,100.0,0.0,P0,Request SLA breached; Escalated or severe tick...,55,Moderate,Immediately alert the operations manager; assi...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Escalated or severe tick...
14,REQ0000023,CUST000455,BR0653,2026-02-11,06:38:00,KYC,CKYC Pending,Branch,open,72,KYC Operations,<NA>,2026-02-14,NaT,False,False,False,Amit Malhotra,Classic,Current,2936,BR0615,HDFC Noida Service Branch 0653,Noida,Uttar Pradesh,North,Semi-Urban,Breached,3336.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,1,2026-02-12,escalated,1,8.0,5.0,6.0,58.75,1.0,1602.000000,62.500000,75.0,12.5,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
17,REQ0000026,CUST000979,BR0338,2026-03-11,09:46:00,Account,Account Freeze,NetBanking,in_progress,48,Account Servicing,<NA>,2026-03-14,NaT,False,False,False,Amit Sharma,Imperia,Current,1845,BR0556,HDFC Rajkot Service Branch 0338,Rajkot,Gujarat,West,Urban,Breached,2664.0,1,3,open,wrong_information,negative,Severe,True,False,True,True,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,5.0,4.0,5.0,74.00,0.0,1699.200000,80.000000,100.0,0.0,P0,Request SLA breached; Severe complaint; Angry/...,100,Critical,Immediate manager callback; assign the Grievan...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Severe complaint; Angry/...

================================================================================
p0_p1_priority_cases
Shape: (4374, 76)

,request_id,customer_id,branch_id,request_created_date,request_created_time,request_category,request_subcategory,channel,request_status,sla_hours,assigned_team,reported_amount,last_updated_date,resolved_date,request_created_date_invalid_flag,last_updated_date_invalid_flag,resolved_date_invalid_flag,customer_name,customer_segment,account_type,relationship_age_days,preferred_branch_id,branch_name,branch_city,branch_state,branch_zone,branch_type,sla_status,elapsed_hours,complaint_count,customer_complaint_count,complaint_status,complaint_type,sentiment_tag,complaint_severity,repeated_complaint_flag,reopened_complaint_flag,angry_complaint_flag,unresolved_complaint_flag,ticket_count,ticket_status,assigned_team_ticket,escalation_flag,max_ticket_age_hours,ticket_severity,ticket_issue_tag,ticket_sla_breached_flag,ticket_delay_warning_flag,slow_resolution_flag,duplicate_suspected,duplicate_group_key,duplicate_reason,duplicate_id_flag,same_day_repeat_flag,recurring_issue_flag,unresolved_repeat_count,status_update_count,last_update_date,latest_status_from_update,reassignment_count,total_requests,pending_requests,sla_breaches,branch_risk_score,near_sla_breaches,avg_elapsed_hours,pending_rate_pct,sla_breach_rate_pct,near_breach_rate_pct,request_priority,priority_reason,customer_impact_score,customer_impact_level,recommended_action,ai_support_prompt,ai_prompt_reason
0,REQ0000009,CUST001111,BR0566,2026-04-27,04:20:00,Complaint,Service Delay,Branch,in_progress,72,Customer Grievance,240247.88,2026-04-27,NaT,False,False,False,Vikram Khan,Corporate,Savings,499,BR0574,HDFC Jodhpur Service Branch 0566,Jodhpur,Rajasthan,North,Urban,Breached,1536.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,10.0,6.0,8.0,58.0,0.0,1243.200000,60.000000,80.000000,0.000000,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
1,REQ0000010,CUST000649,BR0980,2026-05-17,22:31:00,Card,Failed ATM Withdrawal,WhatsApp,pending_customer,36,Cards Operations,24383.2,2026-05-18,NaT,False,False,False,Vivaan Mehta,Corporate,NRI Savings,3430,BR0458,HDFC Kozhikode Service Branch 0980,Kozhikode,Kerala,South,Metro,Breached,1056.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,9.0,5.0,6.0,50.0,0.0,1157.333333,55.555556,66.666667,0.000000,P1,Request SLA breached; Request or ticket remain...,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Request or ticket remain...
3,REQ0000012,CUST000212,BR0335,2026-04-20,03:36:00,Complaint,Fraud Concern,Email,in_progress,72,Customer Grievance,3879.56,2026-04-21,NaT,False,False,False,Reyansh Malhotra,NRI,Savings,2590,BR0622,HDFC Hyderabad Service Branch 0335,Hyderabad,Telangana,South,Rural,Breached,1704.0,0,0,No Complaint,None,None,None,False,False,False,False,1,open,Customer Care,False,1704.0,Severe,Ticket SLA Breach; Active Ticket,True,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,4.0,1.0,2.0,32.5,0.0,456.000000,25.000000,50.000000,0.000000,P0,Request SLA breached; Ticket SLA breached; Esc...,75,High,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...,Request SLA breached; Ticket SLA breached; Esc...
4,REQ0000013,CUST001137,BR0081,2026-06-13,07:18:00,Account,Balance Mismatch,NetBanking,closed,48,Account Servicing,<NA>,2026-06-16,2026-06-16,False,False,False,Saanvi Iyer,Corporate,Loan Account,950,BR0144,HDFC Kochi Service Branch 0081,Kochi,Kerala,South,Urban,Breached,72.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,5.0,0.0,1.0,14.0,1.0,38.400000,0.000000,20.000000,20.000000,P1,Request SLA breached,30,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached
6,REQ0000015,CUST001118,BR0262,2026-02-22,19:15:00,Account,Account Freeze,Email,resolved,48,Account Servicing,<NA>,2026-02-25,2026-02-24,False,False,False,Sai Bhat,Preferred,NRI Savings,3178,BR0894,HDFC Coimbatore Service Branch 0262,Coimbatore,TAMIL NADU,South,Metro,Near Breach,48.0,0,0,No Complaint,None,None,None,False,False,False,False,0,No Ticket,Unassigned,False,<NA>,None,No Ticket Issue,False,False,False,False,NaN,No duplicate pattern detected,False,False,False,0,0,NaT,NaN,0,7.0,2.0,4.0,40.0,1.0,466.285714,28.571429,57.142857,14.285714,P1,Request SLA breached; SLA near breach or delay...,45,Moderate,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...,Request SLA breached; SLA near breach or delay...

================================================================================
ai_support_prompts
Shape: (4401, 5)

,request_id,request_priority,reason,recommended_action,ai_support_prompt
0,REQ0000009,P1,Request SLA breached; Request or ticket remain...,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
1,REQ0000010,P1,Request SLA breached; Request or ticket remain...,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
2,REQ0000012,P0,Request SLA breached; Ticket SLA breached; Esc...,Arrange immediate supervisor review; assign a ...,ROLE:\nYou are a professional customer-support...
3,REQ0000013,P1,Request SLA breached,Route the request to the responsible operation...,ROLE:\nYou are a professional customer-support...
4,REQ0000014,P2,Moderate complaint severity; Repeated customer...,"Review the customer's previous complaints, ide...",ROLE:\nYou are a professional customer-support...

================================================================================
data_validation_report
Shape: (60, 7)

            dataset        check_type column_or_key  issue_count  severity  status                             message
0  service_requests  Required Columns  All required            0  Critical  Passed   All required columns are present.
1  service_requests     Extra Columns             -            0   Warning  Passed  Schema matches configured columns.
2  service_requests    Critical Nulls    request_id            0  Critical  Passed       No missing identifier values.
3  service_requests    Critical Nulls   customer_id            0  Critical  Passed       No missing identifier values.
4  service_requests    Critical Nulls     branch_id            0  Critical  Passed       No missing identifier values.

================================================================================
service_request_health_summary
Shape: (7, 2)

                        Metric  Value
0               total_requests   4992
1  resolved_or_closed_requests   2360
2  pending_unresolved_requests   2632
3        sla_breached_requests   3432
4     near_sla_breach_requests    522

## Deliverable 6 — Final Product Walkthrough

**Purpose:** Explain your completed product like a Python Developer handing over work to Product and Engineering.

**Expected format:** Replace the prompts below with your final explanation.

### Final Product Walkthrough — Student Response Placeholder

#### 1. Business Problem
Write 4–6 lines explaining the service request resolution problem and why the operations team needs this tool.

#### 2. Product Flow
Explain the final notebook flow:

1. Dataset upload and extraction
2. Multi-file loading
3. Validation
4. Cleaning
5. SLA, branch, complaint, ticket, and duplicate analysis
6. Priority classification
7. Recommended action and AI prompt generation
8. GUI search/filter
9. Report export and validation

#### 3. Major Bugs Fixed
Summarize the most important 5–7 bugs you fixed from the previous developer's codebase.

#### 4. Most Important Business Rules Implemented
Explain SLA breach, complaint severity, ticket severity, branch risk, priority hierarchy, customer impact score, and recommended action logic.

#### 5. Final Reports Generated
List the reports generated and what each report is used for.

#### 6. How an Operations User Will Use This Colab Product
Explain how a support executive, branch operations manager, or grievance analyst can use the search/filter/report sections.

#### 7. Assumptions and Limitations
Summarize the most important assumptions and limitations from your assumption log.

#### 8. Final Readiness Statement
Write whether the product is ready for internal simulated handoff and what evidence proves it.

## Deliverable 7 — Final Self-Check Before Submission

Use this section to prove that your single notebook submission is complete.

In [ ]:
# ============================================================
# Deliverable 7 Placeholder: Final Self-Check
# Update actual_result/status after your implementation is complete.
# ============================================================

final_self_check_df = pd.DataFrame([
    {"check_item": "Notebook runs from top to bottom", "expected_result": "No unresolved errors", "actual_result": "To be filled", "status": "Pending"},
    {"check_item": "All datasets loaded", "expected_result": "7 files loaded", "actual_result": "To be filled", "status": "Pending"},
    {"check_item": "Data validation report visible", "expected_result": "data_validation_report displayed", "actual_result": "To be filled", "status": "Pending"},
    {"check_item": "Debug fix log visible", "expected_result": "10+ meaningful rows", "actual_result": "To be filled", "status": "Pending"},
    {"check_item": "AI prompt usage log visible", "expected_result": "AI usage documented", "actual_result": "To be filled", "status": "Pending"},
    {"check_item": "PRD mapping visible", "expected_result": "Major FRs mapped", "actual_result": "To be filled", "status": "Pending"},
    {"check_item": "Final reports previewed", "expected_result": "Report shapes and previews visible", "actual_result": "To be filled", "status": "Pending"},
    {"check_item": "GUI works", "expected_result": "Search and filters usable in Colab", "actual_result": "To be filled", "status": "Pending"},
    {"check_item": "Final walkthrough completed", "expected_result": "Explanation written in notebook", "actual_result": "To be filled", "status": "Pending"},
])

final_self_check_df

                         check_item                     expected_result actual_result   status
0  Notebook runs from top to bottom                No unresolved errors  To be filled  Pending
1               All datasets loaded                      7 files loaded  To be filled  Pending
2    Data validation report visible    data_validation_report displayed  To be filled  Pending
3             Debug fix log visible                 10+ meaningful rows  To be filled  Pending
4       AI prompt usage log visible                 AI usage documented  To be filled  Pending
5               PRD mapping visible                    Major FRs mapped  To be filled  Pending
6           Final reports previewed  Report shapes and previews visible  To be filled  Pending
7                         GUI works  Search and filters usable in Colab  To be filled  Pending
8       Final walkthrough completed     Explanation written in notebook  To be filled  Pending

# Evaluation Rubric — 100 Marks

| No | Criteria | Marks | Expectation |
|---:|:---|---:|:---|
| 1 | Colab setup, file upload flow, and multi-file loading | 8 | Dataset ZIP upload/extraction works in Colab; all CSV/XLSX/JSON/TXT files load with clear status messages. |
| 2 | Data validation and defensive error handling | 10 | Required columns, duplicate keys, null critical fields, orphan records, invalid dates, and optional file warnings are handled without notebook crashes. |
| 3 | Data cleaning and standardization | 10 | Statuses, request categories, channels, dates, amounts, complaints, tickets, customers, and branches are cleaned correctly. |
| 4 | SLA breach and service request ageing logic | 10 | SLA breached, near breach, resolved late, invalid created date, and pending request cases are classified accurately. |
| 5 | Complaint and support ticket linking | 10 | Complaints/tickets are merged correctly; repeated complaints, unresolved complaints, escalations, ticket delays, and slow resolution cases are identified. |
| 6 | Branch analysis and request priority classification | 12 | Branch risk scores are generated; P0/P1/P2/P3/No Issue hierarchy is implemented with clear priority reasons. |
| 7 | Customer impact score and recommended action generation | 8 | Impact scores are capped at 100, impact levels are assigned, and every important case gets a business-readable recommended action. |
| 8 | Pandas analysis summaries and final report exports | 10 | Branch, category/status, SLA breach, pending, P0/P1, AI prompt, validation, debug, and health summary reports are generated correctly. |
| 9 | Colab GUI, customer/request search, filters, and usability | 12 | Search and filter interface works inside Colab with valid/invalid input handling and business-readable output. |
| 10 | Debug log, AI usage log, PRD mapping, assumptions, and self-check | 10 | All required in-notebook deliverable workspaces are completed with meaningful evidence. |
| 11 | Presentation & Explanation | 10 | Final walkthrough clearly explains business problem, code flow, bugs fixed, business rules, outputs, assumptions, and readiness. |
|  | **Total** | **100** |  |

**Final rubric item:** Presentation & Explanation — 10 marks

# Final Submission Checklist

Before submission, make sure your **single completed Colab notebook** contains:

- Fully fixed and runnable code
- All outputs visible after running the notebook
- Data loading, validation, cleaning, analysis, GUI, and export sections working
- Debug fix log completed in the notebook deliverable workspace
- AI prompt usage log completed in the notebook deliverable workspace
- PRD completion mapping completed in the notebook deliverable workspace
- Assumption and limitation log completed in the notebook deliverable workspace
- Final report previews visible inside the notebook
- Final validation summary visible inside the notebook
- Final product walkthrough completed inside the notebook
- Presentation/explanation notes completed inside the notebook

## Required submission format

Submit only the completed `.ipynb` file.

Do not submit CSV outputs, screenshots, PDFs, PPTs, or separate documents unless your instructor explicitly asks for them later.

## Important

A notebook with working code but missing logs, mapping, explanation, and visible outputs is **not complete** for this capstone.